# toy build system.
#
# Demo / training Ruby drivers live in demos/ and compile to native
# binaries via Spinel. CUDA / ggml acceleration is opt-in:
#
#   make                   # demos/train_minimal + demos/train_tinystories
#   make setup-ggml        # one-time clone + CPU build of vendored ggml
#   make setup-ggml-cuda   # one-time clone + CUDA build (needs CUDA toolkit)
#   make smoke             # tinynn FFI smoke test (4x3 ggml matmul demo)
#   make distilgpt2_demo_text  # → demos/distilgpt2_demo_text
#
# Vendored ggml lives at vendor/ggml/ (gitignored).
# The CUDA build expects sm_121 (NVIDIA GB10); override with
# GGML_CUDA_ARCH=NN on the command line.

SPINEL_DIR  ?= $(HOME)/sites/spinel
SPINEL      ?= $(SPINEL_DIR)/spinel

CC          ?= cc
CFLAGS      ?= -O2 -fPIC -Wall -Wextra
ARFLAGS      = rcs

# macOS Command Line Tools (as of 26.x) keep stale 2023 C++ stub headers
# at /Library/Developer/CommandLineTools/usr/include/c++/v1 which shadow
# the real headers in the SDK. Prepend the SDK's libc++ include path so
# ggml's C++ files can find <mutex>, <array>, etc. No-op on Linux.
UNAME_S := $(shell uname -s)
ifeq ($(UNAME_S),Darwin)
  CMAKE_ENV := CPLUS_INCLUDE_PATH=$(shell xcrun --show-sdk-path)/usr/include/c++/v1
  NJOBS     := $(shell sysctl -n hw.logicalcpu)
else
  CMAKE_ENV :=
  NJOBS     := $(shell nproc)
endif

# --- vendored ggml ----------------------------------------------------------
GGML_DIR    := vendor/ggml
GGML_REPO   := https://github.com/ggml-org/ggml.git
GGML_CUDA_ARCH ?= 121
CUDA_DIR    ?= /usr/local/cuda

# --- Tep sibling sync -------------------------------------------------------
# Tep is co-developed with this repo (sibling at ~/sites/tep); we
# track HEAD continuously. `prep/sync_tep.rb` rsyncs upstream Tep's
# lib/ into tep_demo/_tep_lib/ and substitutes the @TEP_*@
# placeholders that upstream's bin/tep handles at build time. Bails
# loud if a dependency (libpq, libsqlite3) is missing — never
# silently degrades. Run after pulling Tep changes, or via:
sync-tep:
	./prep/sync_tep.rb

# --- pure-Spinel drivers ----------------------------------------------------
# Source lives in demos/. We expose short top-level target names
# (`make train_minimal`, `make distilgpt2_demo_text`) that build into
# demos/. Run the resulting binaries from the repo root.
all: demos/train demos/smollm2

# --- examples/ getting-started entry points --------------------------------
# Compact, one-file demos covering the main use cases. See
# examples/README.md.
examples/example_inference: examples/01_inference.rb lib/arch.rb lib/transformer_lm.rb lib/toy_smollm2_ffi_kv.rb lib/toy_smollm2_loader.rb lib/transformer.rb lib/gpt2.rb lib/gguf_load.rb lib/tinynn.rb tinynn/libtinynn_ggml.a
	$(SPINEL) $< -o $@
example_inference: examples/example_inference

examples/example_train: examples/02_train_custom_gpt.rb lib/transformer.rb lib/training.rb lib/toy_trainer.rb lib/tinynn.rb tinynn/libtinynn_ggml.a
	$(SPINEL) $< -o $@
example_train: examples/example_train

examples/example_finetune: examples/03_finetune_lora.rb lib/llama_seq_forward_ffi.rb lib/toy_smollm2_loader.rb lib/transformer.rb lib/gpt2.rb lib/gguf_load.rb lib/tinynn.rb tinynn/libtinynn_ggml.a
	$(SPINEL) $< -o $@
example_finetune: examples/example_finetune

# CUDA mirror — same source, swap TinyNN → TinyNNCuda by including
# both libs. The example source uses TinyNN; the CUDA build link-step
# carries CUDA symbols too (no source change). For real GPU speedup
# users typically write a `_cuda` variant; this mirror is for the
# build-recipe story.
examples/example_finetune_cuda: examples/03_finetune_lora_cuda.rb lib/llama_seq_forward_ffi_cuda.rb lib/toy_smollm2_loader.rb lib/transformer.rb lib/gpt2.rb lib/gguf_load.rb lib/tinynn_cuda.rb tinynn/libtinynn_ggml.a tinynn/libtinynn_ggml_cuda.a
	$(SPINEL) --cc='cc -Wl,-u,tnn_cuda_force_link' $< -o $@
example_finetune_cuda: examples/example_finetune_cuda

examples/example_serve: examples/04_serve_http.rb tep_demo/_tep_lib/tep.rb lib/toy_smollm2_ffi_kv.rb lib/toy_smollm2_loader.rb lib/transformer.rb lib/gpt2.rb lib/gguf_load.rb lib/tinynn.rb tinynn/libtinynn_ggml.a
	$(SPINEL) $< -o $@
example_serve: examples/example_serve

examples/example_list_models: examples/05_list_models.rb lib/model_index.rb lib/arch.rb lib/tinynn.rb tinynn/libtinynn_ggml.a
	$(SPINEL) $< -o $@
example_list_models: examples/example_list_models

examples: example_inference example_train example_finetune example_finetune_cuda example_serve example_list_models

# Phase 0.6 — CUDA-mirror generator. The CPU file is the source of
# truth; the CUDA file is auto-generated by prep/gen_cuda_mirror.rb.
# `make verify-mirrors` exits non-zero if any committed CUDA mirror
# has drifted from what the generator would produce.
gen-mirrors:
	@ruby prep/gen_cuda_mirror.rb

verify-mirrors:
	@ruby prep/gen_cuda_mirror.rb --verify

# Parity-checks vs native TransformerLM.forward.

# Tep+Spinel HTTP server demos. See tep_demo/README.md. Builds bypass
# tep's translator (we use spinel directly on a layout-substituted
# copy of tep's lib in tep_demo/_tep_lib/).
tep_demo/hello: tep_demo/hello_api.rb tep_demo/_tep_lib/tep.rb
	$(SPINEL) tep_demo/hello_api.rb -o tep_demo/hello

# Inference API: /generate?n=N runs greedy generation via FullForwardFFICache.
tep_demo/api: tep_demo/inference_api.rb tep_demo/_tep_lib/tep.rb lib/transformer.rb lib/tinynn.rb tinynn/libtinynn_ggml.a
	$(SPINEL) tep_demo/inference_api.rb -o tep_demo/api

# OpenAI-compatible API backed by SmolLM2/Qwen-family models via the
# direct GGUF→FFI loader. Accepts pre-tokenized integer IDs (no
# server-side tokenizer — keeps the single-binary deployment story).
# Hard-codes the model GGUF path; copy + edit for other sizes.
tep_demo/openai_api_smollm2: tep_demo/openai_api_smollm2.rb tep_demo/_tep_lib/tep.rb lib/toy_smollm2_ffi_kv.rb lib/toy_smollm2_loader.rb tinynn/libtinynn_ggml.a
	$(SPINEL) tep_demo/openai_api_smollm2.rb -o tep_demo/openai_api_smollm2

# Larger-size variants of the same API. Per-binary GGUF path because
# Spinel mistypes env-var-driven constants — copy + sed-edit is the
# convention. Add new sizes by following the pattern (see
# tep_demo/openai_api_qwen25_1.5b.rb for the canonical 2-line diff).
OPENAI_QWEN_SOURCES   = $(wildcard tep_demo/openai_api_qwen25_*.rb)
OPENAI_QWEN_TARGETS   = $(OPENAI_QWEN_SOURCES:.rb=)
OPENAI_QWEN_DEPS      = tep_demo/_tep_lib/tep.rb \
                        lib/toy_smollm2_ffi_kv.rb \
                        lib/toy_smollm2_loader.rb \
                        tinynn/libtinynn_ggml.a

openai-qwen-all: $(OPENAI_QWEN_TARGETS)

tep_demo/openai_api_qwen25_%: tep_demo/openai_api_qwen25_%.rb $(OPENAI_QWEN_DEPS)
	$(SPINEL) $< -o $@

# --- ggml vendor ------------------------------------------------------------
# Vendor patches that must land before any ggml build target. See
# vendor-patches/README.md for the per-patch rationale.
GGML_PATCHES := \
	vendor-patches/0001-cuda-buffer_from_ptr.patch \
	vendor-patches/0002-cuda-buffer_from_ptr-reuse-iface.patch \
	vendor-patches/0003-cuda-buffer_from_ptr-copy-mode.patch \
	vendor-patches/0004-cuda-cpy-strided.patch \
	vendor-patches/0005-concat-backward.patch

# Sentinel file marking that all $(GGML_PATCHES) have been applied to
# the vendored tree. Build targets depend on it through CMakeLists.txt
# (which depends on this sentinel) so a fresh clone applies the patches
# exactly once, and re-runs of `make setup-ggml` are no-ops as long as
# the patch set is unchanged.
$(GGML_DIR)/.patched: $(GGML_DIR)/CMakeLists.txt $(GGML_PATCHES)
	@echo "  reset vendor/ggml to upstream HEAD (build/ untouched)"
	@cd $(GGML_DIR) && git reset --hard HEAD >/dev/null
	@cd $(GGML_DIR) && for p in $(GGML_PATCHES); do \
	  echo "  apply $$p"; \
	  git apply "$(CURDIR)/$$p" || { echo "    FAILED"; exit 1; }; \
	done
	touch $@

$(GGML_DIR)/CMakeLists.txt:
	mkdir -p vendor
	git clone --depth 1 $(GGML_REPO) $(GGML_DIR)

# GGML_OPENMP=OFF: avoid the libgomp link dependency. On macOS clang
# ships libomp (LLVM), not libgomp (GNU); ggml's own thread pool covers
# CPU parallelism either way. Same setting used on Linux for build
# parity (and so lib/tinynn.rb doesn't need ffi_lib "gomp").
setup-ggml: $(GGML_DIR)/.patched
	cd $(GGML_DIR) && $(CMAKE_ENV) cmake -B build \
	  -DBUILD_SHARED_LIBS=OFF -DGGML_STATIC=ON \
	  -DGGML_CUDA=OFF -DGGML_METAL=OFF -DGGML_VULKAN=OFF \
	  -DGGML_OPENCL=OFF -DGGML_BLAS=OFF -DGGML_OPENMP=OFF -DGGML_ACCELERATE=OFF \
	  -DGGML_BUILD_EXAMPLES=OFF -DGGML_BUILD_TESTS=OFF \
	  -DCMAKE_BUILD_TYPE=Release -DCMAKE_POSITION_INDEPENDENT_CODE=ON
	cd $(GGML_DIR) && $(CMAKE_ENV) cmake --build build -j$(NJOBS)

setup-ggml-cuda: $(GGML_DIR)/.patched
	cd $(GGML_DIR) && PATH=$(CUDA_DIR)/bin:$$PATH $(CMAKE_ENV) cmake -B build-cuda \
	  -DBUILD_SHARED_LIBS=OFF -DGGML_STATIC=ON \
	  -DGGML_CUDA=ON -DGGML_METAL=OFF -DGGML_VULKAN=OFF \
	  -DGGML_OPENCL=OFF -DGGML_BLAS=OFF -DGGML_OPENMP=OFF -DGGML_ACCELERATE=OFF \
	  -DGGML_BUILD_EXAMPLES=OFF -DGGML_BUILD_TESTS=OFF \
	  -DCMAKE_BUILD_TYPE=Release -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
	  -DCMAKE_CUDA_ARCHITECTURES=$(GGML_CUDA_ARCH) -DGGML_NATIVE=OFF
	cd $(GGML_DIR) && PATH=$(CUDA_DIR)/bin:$$PATH $(CMAKE_ENV) cmake --build build-cuda -j$(NJOBS)

# --- tinynn shim (CPU build) ------------------------------------------------
GGML_INC := -I$(GGML_DIR)/include -I$(GGML_DIR)/src

tinynn/tinynn_ggml.o: tinynn/tinynn_ggml.c tinynn/tinynn_ggml.h
	$(CC) $(CFLAGS) $(GGML_INC) -c $< -o $@

tinynn/tinynn_gguf.o: tinynn/tinynn_gguf.c tinynn/tinynn_gguf.h
	$(CC) $(CFLAGS) $(GGML_INC) -c $< -o $@

tinynn/libtinynn_ggml.a: tinynn/tinynn_ggml.o tinynn/tinynn_gguf.o
	ar $(ARFLAGS) $@ tinynn/tinynn_ggml.o tinynn/tinynn_gguf.o

# --- smoke test -------------------------------------------------------------
# Builds tinynn/smoke.rb against the CPU shim. Requires `setup-ggml` to have
# been run once first.
smoke: tinynn/smoke
	./tinynn/smoke

tinynn/smoke: tinynn/smoke.rb tinynn/libtinynn_ggml.a
	$(SPINEL) tinynn/smoke.rb -o tinynn/smoke

# A/B parity tests: native vs FFI (CPU) for one op each.
ab-smoke: tinynn/ab_smoke
	./tinynn/ab_smoke

ab-smoke-add: tinynn/ab_smoke_add
	./tinynn/ab_smoke_add

ab-smoke-gelu: tinynn/ab_smoke_gelu
	./tinynn/ab_smoke_gelu

# Llama-family ops (silu, mul, eventually rope) — added with the
# Toy::SmolLM2 FFI mirror work.
ab-smoke-silu: tinynn/ab_smoke_silu
	./tinynn/ab_smoke_silu

tinynn/ab_smoke_silu: tinynn/ab_smoke_silu.rb lib/toy_card.rb lib/toy.rb lib/transformer.rb lib/tinynn.rb tinynn/libtinynn_ggml.a
	$(SPINEL) $< -o $@

ab-smoke-mul: tinynn/ab_smoke_mul
	./tinynn/ab_smoke_mul

tinynn/ab_smoke_mul: tinynn/ab_smoke_mul.rb lib/toy_card.rb lib/toy.rb lib/transformer.rb lib/tinynn.rb tinynn/libtinynn_ggml.a
	$(SPINEL) $< -o $@

ab-smoke-rms-norm: tinynn/ab_smoke_rms_norm
	./tinynn/ab_smoke_rms_norm

ab-smoke-softmax: tinynn/ab_smoke_softmax
	./tinynn/ab_smoke_softmax

ab-smoke-transpose: tinynn/ab_smoke_transpose
	./tinynn/ab_smoke_transpose

ab-smoke-scale: tinynn/ab_smoke_scale
	./tinynn/ab_smoke_scale

# Chained-op pipeline: gelu(h·w1)·w2 in one ggml graph.
ab-smoke-pipeline: tinynn/ab_smoke_pipeline
	./tinynn/ab_smoke_pipeline

# Run every CPU smoke. (CUDA variants would need `make setup-ggml-cuda` first.)
# `ab-smoke-transpose` is omitted: ggml_cont(ggml_transpose(...)) trips
# the scheduler's buffer allocation; we fold transposes into consuming
# ops instead (see TinyNN.matmul's b-transposed upload).
test: smoke ab-smoke ab-smoke-add ab-smoke-gelu ab-smoke-rms-norm \
       ab-smoke-softmax ab-smoke-scale ab-smoke-pipeline \
       ab-smoke-matmul-variants ab-smoke-back ab-smoke-embed ab-smoke-sgd \
       ab-smoke-gelu-back ab-smoke-cegrad ab-smoke-adam

tinynn/ab_smoke: tinynn/ab_smoke.rb lib/transformer.rb lib/tinynn.rb tinynn/libtinynn_ggml.a
	$(SPINEL) tinynn/ab_smoke.rb -o tinynn/ab_smoke

tinynn/ab_smoke_add: tinynn/ab_smoke_add.rb lib/transformer.rb lib/tinynn.rb tinynn/libtinynn_ggml.a
	$(SPINEL) tinynn/ab_smoke_add.rb -o tinynn/ab_smoke_add

tinynn/ab_smoke_gelu: tinynn/ab_smoke_gelu.rb lib/transformer.rb lib/tinynn.rb tinynn/libtinynn_ggml.a
	$(SPINEL) tinynn/ab_smoke_gelu.rb -o tinynn/ab_smoke_gelu

tinynn/ab_smoke_rms_norm: tinynn/ab_smoke_rms_norm.rb lib/transformer.rb lib/tinynn.rb tinynn/libtinynn_ggml.a
	$(SPINEL) tinynn/ab_smoke_rms_norm.rb -o tinynn/ab_smoke_rms_norm

tinynn/ab_smoke_softmax: tinynn/ab_smoke_softmax.rb lib/transformer.rb lib/tinynn.rb tinynn/libtinynn_ggml.a
	$(SPINEL) tinynn/ab_smoke_softmax.rb -o tinynn/ab_smoke_softmax

tinynn/ab_smoke_transpose: tinynn/ab_smoke_transpose.rb lib/transformer.rb lib/tinynn.rb tinynn/libtinynn_ggml.a
	$(SPINEL) tinynn/ab_smoke_transpose.rb -o tinynn/ab_smoke_transpose

tinynn/ab_smoke_scale: tinynn/ab_smoke_scale.rb lib/transformer.rb lib/tinynn.rb tinynn/libtinynn_ggml.a
	$(SPINEL) tinynn/ab_smoke_scale.rb -o tinynn/ab_smoke_scale

tinynn/ab_smoke_pipeline: tinynn/ab_smoke_pipeline.rb lib/transformer.rb lib/tinynn.rb tinynn/libtinynn_ggml.a
	$(SPINEL) tinynn/ab_smoke_pipeline.rb -o tinynn/ab_smoke_pipeline

# Chained FFNFFICache parity: pre, hidden, out vs hand-rolled native.
ab-smoke-ffncache: tinynn/ab_smoke_ffncache
	./tinynn/ab_smoke_ffncache

tinynn/ab_smoke_ffncache: tinynn/ab_smoke_ffncache.rb lib/transformer.rb lib/tinynn.rb tinynn/libtinynn_ggml.a
	$(SPINEL) tinynn/ab_smoke_ffncache.rb -o tinynn/ab_smoke_ffncache

# ggml-native AdamW step (opt_step_adamw) parity vs project's plain-Adam.
ab-smoke-adamw-op: tinynn/ab_smoke_adamw_op
	./tinynn/ab_smoke_adamw_op

tinynn/ab_smoke_adamw_op: tinynn/ab_smoke_adamw_op.rb lib/transformer.rb lib/tinynn.rb tinynn/libtinynn_ggml.a
	$(SPINEL) tinynn/ab_smoke_adamw_op.rb -o tinynn/ab_smoke_adamw_op

# Persistent-tensor architecture check: data uploaded to a ctx_w tensor
# survives a compute cycle.
ab-smoke-persistent: tinynn/ab_smoke_persistent
	./tinynn/ab_smoke_persistent

tinynn/ab_smoke_persistent: tinynn/ab_smoke_persistent.rb lib/transformer.rb lib/tinynn.rb tinynn/libtinynn_ggml.a
	$(SPINEL) tinynn/ab_smoke_persistent.rb -o tinynn/ab_smoke_persistent

# Dual-cgraph + persistent-weights design check: forward reads t_w;
# adam mutates t_w in place; forward sees the new value.
ab-smoke-dual-graph: tinynn/ab_smoke_dual_graph
	./tinynn/ab_smoke_dual_graph

tinynn/ab_smoke_dual_graph: tinynn/ab_smoke_dual_graph.rb lib/transformer.rb lib/tinynn.rb tinynn/libtinynn_ggml.a
	$(SPINEL) tinynn/ab_smoke_dual_graph.rb -o tinynn/ab_smoke_dual_graph

# M2 foundation: view_2d + cpy to write a single row into a persistent
# (max_T, d_head) KV buffer at a runtime-baked position.
ab-smoke-kv-write: tinynn/ab_smoke_kv_write
	./tinynn/ab_smoke_kv_write

tinynn/ab_smoke_kv_write: tinynn/ab_smoke_kv_write.rb lib/transformer.rb lib/tinynn.rb tinynn/libtinynn_ggml.a
	$(SPINEL) tinynn/ab_smoke_kv_write.rb -o tinynn/ab_smoke_kv_write

# M2 prototype: single-step decode through a KV cache. Pre-fills K/V
# for positions 0..POS-1, writes k_new/v_new at POS, computes scores
# + soft_max_ext + head_out. Parity vs hand-rolled native.
ab-smoke-kv-attn: tinynn/ab_smoke_kv_attn
	./tinynn/ab_smoke_kv_attn

tinynn/ab_smoke_kv_attn: tinynn/ab_smoke_kv_attn.rb lib/transformer.rb lib/tinynn.rb tinynn/libtinynn_ggml.a
	$(SPINEL) tinynn/ab_smoke_kv_attn.rb -o tinynn/ab_smoke_kv_attn

# M1.2: full single-block forward through the persistent graph.
# Parity vs native TransformerLM.forward() at n_layers=1, n_heads=2.
ab-smoke-full-forward-block: tinynn/ab_smoke_full_forward_block
	./tinynn/ab_smoke_full_forward_block

tinynn/ab_smoke_full_forward_block: tinynn/ab_smoke_full_forward_block.rb lib/transformer.rb lib/tinynn.rb tinynn/libtinynn_ggml.a
	$(SPINEL) tinynn/ab_smoke_full_forward_block.rb -o tinynn/ab_smoke_full_forward_block

# Wallclock bench: native TransformerLM.forward vs FullForwardFFICache.
full-forward-bench: tinynn/full_forward_bench
	./tinynn/full_forward_bench

tinynn/full_forward_bench: tinynn/full_forward_bench.rb lib/transformer.rb lib/tinynn.rb tinynn/libtinynn_ggml.a
	$(SPINEL) tinynn/full_forward_bench.rb -o tinynn/full_forward_bench

full-forward-bench-cuda: tinynn/full_forward_bench_cuda
	./tinynn/full_forward_bench_cuda

tinynn/full_forward_bench_cuda: tinynn/full_forward_bench_cuda.rb lib/transformer.rb lib/tinynn_cuda.rb tinynn/libtinynn_ggml_cuda.a
	$(SPINEL) tinynn/full_forward_bench_cuda.rb -o tinynn/full_forward_bench_cuda

ab-smoke-dual-graph-cuda: tinynn/ab_smoke_dual_graph_cuda
	./tinynn/ab_smoke_dual_graph_cuda

tinynn/ab_smoke_dual_graph_cuda: tinynn/ab_smoke_dual_graph_cuda.rb lib/transformer.rb lib/tinynn_cuda.rb tinynn/libtinynn_ggml_cuda.a
	$(SPINEL) tinynn/ab_smoke_dual_graph_cuda.rb -o tinynn/ab_smoke_dual_graph_cuda

ab-smoke-adamw-op-cuda: tinynn/ab_smoke_adamw_op_cuda
	./tinynn/ab_smoke_adamw_op_cuda

tinynn/ab_smoke_adamw_op_cuda: tinynn/ab_smoke_adamw_op_cuda.rb lib/transformer.rb lib/tinynn_cuda.rb tinynn/libtinynn_ggml_cuda.a
	$(SPINEL) tinynn/ab_smoke_adamw_op_cuda.rb -o tinynn/ab_smoke_adamw_op_cuda

# Transformer-shape sized parity + wallclock comparison.
ab-smoke-big: tinynn/ab_smoke_big
	./tinynn/ab_smoke_big

tinynn/ab_smoke_big: tinynn/ab_smoke_big.rb lib/transformer.rb lib/tinynn.rb tinynn/libtinynn_ggml.a
	$(SPINEL) tinynn/ab_smoke_big.rb -o tinynn/ab_smoke_big

ab-smoke-matmul-variants: tinynn/ab_smoke_matmul_variants
	./tinynn/ab_smoke_matmul_variants

tinynn/ab_smoke_matmul_variants: tinynn/ab_smoke_matmul_variants.rb lib/transformer.rb lib/tinynn.rb tinynn/libtinynn_ggml.a
	$(SPINEL) tinynn/ab_smoke_matmul_variants.rb -o tinynn/ab_smoke_matmul_variants

ab-smoke-back: tinynn/ab_smoke_back
	./tinynn/ab_smoke_back

tinynn/ab_smoke_back: tinynn/ab_smoke_back.rb lib/transformer.rb lib/tinynn.rb tinynn/libtinynn_ggml.a
	$(SPINEL) tinynn/ab_smoke_back.rb -o tinynn/ab_smoke_back

ab-smoke-gelu-back: tinynn/ab_smoke_gelu_back
	./tinynn/ab_smoke_gelu_back

tinynn/ab_smoke_gelu_back: tinynn/ab_smoke_gelu_back.rb lib/transformer.rb lib/tinynn.rb tinynn/libtinynn_ggml.a
	$(SPINEL) tinynn/ab_smoke_gelu_back.rb -o tinynn/ab_smoke_gelu_back

ab-smoke-cegrad: tinynn/ab_smoke_cegrad
	./tinynn/ab_smoke_cegrad

tinynn/ab_smoke_cegrad: tinynn/ab_smoke_cegrad.rb lib/transformer.rb lib/tinynn.rb tinynn/libtinynn_ggml.a
	$(SPINEL) tinynn/ab_smoke_cegrad.rb -o tinynn/ab_smoke_cegrad

ab-smoke-adam: tinynn/ab_smoke_adam
	./tinynn/ab_smoke_adam

tinynn/ab_smoke_adam: tinynn/ab_smoke_adam.rb lib/transformer.rb lib/tinynn.rb tinynn/libtinynn_ggml.a
	$(SPINEL) tinynn/ab_smoke_adam.rb -o tinynn/ab_smoke_adam

gguf-smoke: tinynn/gguf_smoke
	./tinynn/gguf_smoke

tinynn/gguf_smoke: tinynn/gguf_smoke.rb lib/transformer.rb lib/tinynn.rb tinynn/libtinynn_ggml.a
	$(SPINEL) tinynn/gguf_smoke.rb -o tinynn/gguf_smoke

# Walks every tensor in data/distilgpt2-f32.gguf via tnn_gguf_*. Used to
# confirm large HF-converted GGUFs roundtrip through the project FFI.
gguf-inspect: tinynn/gguf_inspect
	./tinynn/gguf_inspect

tinynn/gguf_inspect: tinynn/gguf_inspect.rb lib/transformer.rb lib/tinynn.rb tinynn/libtinynn_ggml.a
	$(SPINEL) tinynn/gguf_inspect.rb -o tinynn/gguf_inspect

# GPT2LM build smoke: confirm lib/gpt2.rb Spinel-compiles and the
# forward shapes line up. Toy dims, random weights — values mean nothing.
gpt2-build-smoke: tinynn/gpt2_build_smoke
	./tinynn/gpt2_build_smoke

tinynn/gpt2_build_smoke: tinynn/gpt2_build_smoke.rb lib/transformer.rb lib/gpt2.rb
	$(SPINEL) tinynn/gpt2_build_smoke.rb -o tinynn/gpt2_build_smoke

# Load distilgpt2-f32.gguf into a GPT2LM and print sentinel weights
# per category. Verifies name mapping + per-head split before forward.
gpt2-load-smoke: tinynn/gpt2_load_smoke
	./tinynn/gpt2_load_smoke

tinynn/gpt2_load_smoke: tinynn/gpt2_load_smoke.rb lib/transformer.rb lib/gpt2.rb lib/gguf_load.rb lib/tinynn.rb tinynn/libtinynn_ggml.a
	$(SPINEL) tinynn/gpt2_load_smoke.rb -o tinynn/gpt2_load_smoke

# data/prompt_ids.txt, loads weights from data/distilgpt2-f32.gguf,
# greedy-generates N_NEW tokens via native Mat forward, writes the
# full ID sequence back. Decode with prep/tokens.py decode.

# Native Mat GPT-2 inference (DistilGPT2 / GPT-2 family).
#
gpt2:        demos/gpt2
demos/gpt2: demos/gpt2.rb lib/toy_card.rb lib/toy.rb lib/toy_gpt2.rb lib/toy_gpt2_loader.rb lib/transformer.rb lib/gpt2.rb lib/gguf_load.rb lib/tinynn.rb tinynn/libtinynn_ggml.a
	$(SPINEL) $< -o $@

# SmolLM2-135M (llama-family) inference via Toy::SmolLM2.
# Tokenization is host-side: ./prep/smollm2_tokens.py encode "..."
smollm2:        demos/smollm2
demos/smollm2: demos/smollm2.rb lib/toy_card.rb lib/toy.rb lib/toy_smollm2.rb lib/toy_smollm2_loader.rb lib/transformer.rb lib/gpt2.rb lib/gguf_load.rb lib/training.rb lib/tinynn.rb tinynn/libtinynn_ggml.a
	$(SPINEL) $< -o $@

# SmolLM2-135M FFI KV-cache (CPU).
smollm2_kv:        demos/smollm2_kv
demos/smollm2_kv: demos/smollm2_kv.rb lib/toy_card.rb lib/toy.rb lib/toy_smollm2.rb lib/toy_smollm2_loader.rb lib/toy_smollm2_ffi_kv.rb lib/transformer.rb lib/gpt2.rb lib/gguf_load.rb lib/training.rb lib/tinynn.rb tinynn/libtinynn_ggml.a
	$(SPINEL) $< -o $@

# Qwen2.5 Mat-mediated KV-cache (CPU). The slow, correct reference path.
# Run with `GGUF=data/qwen25-1.5b-f32.gguf ./demos/qwen25_kv` etc.
qwen25_kv:        demos/qwen25_kv
demos/qwen25_kv: demos/qwen25_kv.rb lib/toy_card.rb lib/toy.rb lib/toy_smollm2.rb lib/toy_smollm2_loader.rb lib/toy_smollm2_ffi_kv.rb lib/transformer.rb lib/gpt2.rb lib/gguf_load.rb lib/training.rb lib/tinynn.rb tinynn/libtinynn_ggml.a
	$(SPINEL) $< -o $@

# Qwen2.5 Phase-2 mmap inference (CPU). Canonical performance path.
qwen25_native_mmap:        demos/qwen25_native_mmap
demos/qwen25_native_mmap: demos/qwen25_native_mmap.rb lib/toy_smollm2_ffi_kv.rb lib/toy_smollm2_loader.rb lib/transformer.rb lib/gpt2.rb lib/gguf_load.rb lib/training.rb lib/tinynn.rb tinynn/libtinynn_ggml.a
	$(SPINEL) $< -o $@

# Phase 0.7 acceptance gates: 0.5B (f32 + Q8) + 1.5B + 3B greedy-decode
# parity against locked-in golden token-ID sequences. Run before tagging
# a release; see docs/design/phase-07-acceptance.md.
qwen25_acceptance:        demos/qwen25_acceptance
demos/qwen25_acceptance: demos/qwen25_acceptance.rb lib/arch.rb lib/transformer_lm.rb lib/toy_smollm2_ffi_kv.rb lib/toy_smollm2_loader.rb lib/transformer.rb lib/gpt2.rb lib/gguf_load.rb lib/tinynn.rb tinynn/libtinynn_ggml.a
	$(SPINEL) $< -o $@

# Inference bench (CPU). Long warmup + long prefill + per-token stats.
# Pick model via GGUF env; see docs/design/bench-cuda-2026-05-21.md.
qwen25_bench_cpu:        demos/qwen25_bench_cpu
demos/qwen25_bench_cpu: demos/qwen25_bench_cpu.rb lib/toy_smollm2_ffi_kv.rb lib/toy_smollm2_loader.rb lib/transformer.rb lib/gpt2.rb lib/gguf_load.rb lib/tinynn.rb tinynn/libtinynn_ggml.a
	$(SPINEL) $< -o $@

# Inference bench (CUDA). Same shape as the CPU bench for side-by-side.
qwen25_bench_cuda:        demos/qwen25_bench_cuda
demos/qwen25_bench_cuda: demos/qwen25_bench_cuda.rb lib/toy_smollm2_ffi_kv_cuda.rb lib/toy_smollm2_loader.rb lib/transformer.rb lib/gpt2.rb lib/gguf_load.rb lib/tinynn_cuda.rb tinynn/libtinynn_ggml.a tinynn/libtinynn_ggml_cuda.a
	$(SPINEL) --cc='cc -Wl,-u,tnn_cuda_force_link' $< -o $@

# F1.2 step 2: LoRA-Q forward-parity gate. Loads SmolLM2-135M twice
# (baseline + LoRA r=16 B=0), asserts bit-identical generated IDs.
smollm2_lora_forward:        demos/smollm2_lora_forward
demos/smollm2_lora_forward: demos/smollm2_lora_forward.rb lib/toy_smollm2_ffi_kv.rb lib/toy_smollm2_loader.rb lib/transformer.rb lib/gpt2.rb lib/gguf_load.rb lib/tinynn.rb tinynn/libtinynn_ggml.a
	$(SPINEL) $< -o $@

# F1.2 step 3: backward through the full SmolLM2 decode graph,
# layer-0 LoRA-Q updated via SGD. Requires the vendored CONCAT
# backward in vendor/ggml/src/ggml.c.
smollm2_lora_train_step:        demos/smollm2_lora_train_step
demos/smollm2_lora_train_step: demos/smollm2_lora_train_step.rb lib/toy_smollm2_ffi_kv.rb lib/toy_smollm2_loader.rb lib/transformer.rb lib/gpt2.rb lib/gguf_load.rb lib/tinynn.rb tinynn/libtinynn_ggml.a
	$(SPINEL) $< -o $@

# F1.2 step 4: all-layers LoRA-Q SGD on real CE loss against a rare
# target token. 540 opt_step nodes (30 layers × 9 heads × 2 params).
# Acceptance: monotonic decrease over 20 steps.
smollm2_lora_train_ce:        demos/smollm2_lora_train_ce
demos/smollm2_lora_train_ce: demos/smollm2_lora_train_ce.rb lib/toy_smollm2_ffi_kv.rb lib/toy_smollm2_loader.rb lib/transformer.rb lib/gpt2.rb lib/gguf_load.rb lib/tinynn.rb tinynn/libtinynn_ggml.a
	$(SPINEL) $< -o $@

# F2 step 1: CUDA mirror of the LoRA forward parity gate.
smollm2_lora_forward_cuda:        demos/smollm2_lora_forward_cuda
demos/smollm2_lora_forward_cuda: demos/smollm2_lora_forward_cuda.rb lib/toy_smollm2_ffi_kv_cuda.rb lib/toy_smollm2_loader.rb lib/transformer.rb lib/gpt2.rb lib/gguf_load.rb lib/tinynn_cuda.rb tinynn/libtinynn_ggml.a tinynn/libtinynn_ggml_cuda.a
	$(SPINEL) --cc='cc -Wl,-u,tnn_cuda_force_link' $< -o $@

# F2 step 2: CUDA mirror of the multi-layer SGD CE training smoke.
smollm2_lora_train_ce_cuda:        demos/smollm2_lora_train_ce_cuda
demos/smollm2_lora_train_ce_cuda: demos/smollm2_lora_train_ce_cuda.rb lib/toy_smollm2_ffi_kv_cuda.rb lib/toy_smollm2_loader.rb lib/transformer.rb lib/gpt2.rb lib/gguf_load.rb lib/tinynn_cuda.rb tinynn/libtinynn_ggml.a tinynn/libtinynn_ggml_cuda.a
	$(SPINEL) --cc='cc -Wl,-u,tnn_cuda_force_link' $< -o $@

# Task #70 diagnostic — same CE smoke but with every graph_b node
# pinned. Confirms sched intermediate-grad aliasing is the CPU
# divergence's root cause. See docs/design/task70-root-cause-2026-05-21.md.
smollm2_lora_train_ce_pinned:        demos/smollm2_lora_train_ce_pinned
demos/smollm2_lora_train_ce_pinned: demos/smollm2_lora_train_ce_pinned.rb lib/toy_smollm2_ffi_kv.rb lib/toy_smollm2_loader.rb lib/transformer.rb lib/gpt2.rb lib/gguf_load.rb lib/tinynn.rb tinynn/libtinynn_ggml.a
	$(SPINEL) $< -o $@

# F1.2 step 5: AdamW training with per-step m/v preservation via
# tnn_graph_reset_grads_only. Converges 7.5 → 0.09 in 20 SGD steps
# at LR=1e-3 — proper SFT-shaped learning curve.
smollm2_lora_train_adamw_cuda:        demos/smollm2_lora_train_adamw_cuda
demos/smollm2_lora_train_adamw_cuda: demos/smollm2_lora_train_adamw_cuda.rb lib/toy_smollm2_ffi_kv_cuda.rb lib/toy_smollm2_loader.rb lib/transformer.rb lib/gpt2.rb lib/gguf_load.rb lib/tinynn_cuda.rb tinynn/libtinynn_ggml.a tinynn/libtinynn_ggml_cuda.a
	$(SPINEL) --cc='cc -Wl,-u,tnn_cuda_force_link' $< -o $@

# F1.2 step 6a: multi-target AdamW SFT-shaped training. Cycles through
# 5 target tokens × 10 epochs at the same prefix; expects loss to
# drop on average + per-target. 10.8 → 3.6 in 10 epochs. Foundation
# for step 6b (multi-position) and step 7 (real alpaca dataset).
smollm2_lora_sft_multi_cuda:        demos/smollm2_lora_sft_multi_cuda
demos/smollm2_lora_sft_multi_cuda: demos/smollm2_lora_sft_multi_cuda.rb lib/toy_smollm2_ffi_kv_cuda.rb lib/toy_smollm2_loader.rb lib/transformer.rb lib/gpt2.rb lib/gguf_load.rb lib/tinynn_cuda.rb tinynn/libtinynn_ggml.a tinynn/libtinynn_ggml_cuda.a
	$(SPINEL) --cc='cc -Wl,-u,tnn_cuda_force_link' $< -o $@

# F1.2 step 6b — multi-position SFT (cycle pos4 / pos5). Validates
# that persistent Adam m/v (allocated by enable_lora_q_adamw! +
# realize_for_mmap) survive tnn_reset_for_rebuild between cycles.
smollm2_lora_sft_multipos_cuda:        demos/smollm2_lora_sft_multipos_cuda
demos/smollm2_lora_sft_multipos_cuda: demos/smollm2_lora_sft_multipos_cuda.rb lib/toy_smollm2_ffi_kv_cuda.rb lib/toy_smollm2_loader.rb lib/transformer.rb lib/gpt2.rb lib/gguf_load.rb lib/tinynn_cuda.rb tinynn/libtinynn_ggml.a tinynn/libtinynn_ggml_cuda.a
	$(SPINEL) --cc='cc -Wl,-u,tnn_cuda_force_link' $< -o $@

# M3 step 1 — sequence-mode forward parity at T=1.
# LlamaSeqForwardFFICache.forward([id], [0]) must match
# SmolLM2KVFFICache + decode_step(id, 0). See
# docs/design/m3-seq-forward-2026-05-21.md.
smollm2_seq_parity:        demos/smollm2_seq_parity
demos/smollm2_seq_parity: demos/smollm2_seq_parity.rb lib/llama_seq_forward_ffi.rb lib/toy_smollm2_ffi_kv.rb lib/toy_smollm2_loader.rb lib/transformer.rb lib/gpt2.rb lib/gguf_load.rb lib/tinynn.rb tinynn/libtinynn_ggml.a
	$(SPINEL) $< -o $@

# M3 step 2 — T=4 trajectory parity (CPU). Per-position seq logits must
# match the decode_step trajectory; proves causal-mask + multi-pos RoPE.
smollm2_seq_parity_t4:        demos/smollm2_seq_parity_t4
demos/smollm2_seq_parity_t4: demos/smollm2_seq_parity_t4.rb lib/llama_seq_forward_ffi.rb lib/toy_smollm2_ffi_kv.rb lib/toy_smollm2_loader.rb lib/transformer.rb lib/gpt2.rb lib/gguf_load.rb lib/tinynn.rb tinynn/libtinynn_ggml.a
	$(SPINEL) $< -o $@

# M3 step 2 — CUDA mirror. T=1 and T=4 vs CPU decode_step trajectory.
smollm2_seq_parity_cuda:        demos/smollm2_seq_parity_cuda
demos/smollm2_seq_parity_cuda: demos/smollm2_seq_parity_cuda.rb lib/llama_seq_forward_ffi_cuda.rb lib/toy_smollm2_ffi_kv.rb lib/toy_smollm2_loader.rb lib/transformer.rb lib/gpt2.rb lib/gguf_load.rb lib/tinynn.rb lib/tinynn_cuda.rb tinynn/libtinynn_ggml.a tinynn/libtinynn_ggml_cuda.a
	$(SPINEL) --cc='cc -Wl,-u,tnn_cuda_force_link' $< -o $@

smollm2_seq_parity_t4_cuda:        demos/smollm2_seq_parity_t4_cuda
demos/smollm2_seq_parity_t4_cuda: demos/smollm2_seq_parity_t4_cuda.rb lib/llama_seq_forward_ffi_cuda.rb lib/toy_smollm2_ffi_kv.rb lib/toy_smollm2_loader.rb lib/transformer.rb lib/gpt2.rb lib/gguf_load.rb lib/tinynn.rb lib/tinynn_cuda.rb tinynn/libtinynn_ggml.a tinynn/libtinynn_ggml_cuda.a
	$(SPINEL) --cc='cc -Wl,-u,tnn_cuda_force_link' $< -o $@

# M3 step 3 — seq-mode LoRA training smoke (CPU). One forward + backward
# + opt_step over T positions; loss should decrease over N steps.
smollm2_seq_train:        demos/smollm2_seq_train
demos/smollm2_seq_train: demos/smollm2_seq_train.rb lib/llama_seq_forward_ffi.rb lib/toy_smollm2_loader.rb lib/transformer.rb lib/gpt2.rb lib/gguf_load.rb lib/tinynn.rb tinynn/libtinynn_ggml.a
	$(SPINEL) $< -o $@

smollm2_seq_train_cuda:        demos/smollm2_seq_train_cuda
demos/smollm2_seq_train_cuda: demos/smollm2_seq_train_cuda.rb lib/llama_seq_forward_ffi_cuda.rb lib/toy_smollm2_loader.rb lib/transformer.rb lib/gpt2.rb lib/gguf_load.rb lib/tinynn.rb lib/tinynn_cuda.rb tinynn/libtinynn_ggml.a tinynn/libtinynn_ggml_cuda.a
	$(SPINEL) --cc='cc -Wl,-u,tnn_cuda_force_link' $< -o $@

# F3 — full fine-tune on CUDA. Every per-block weight tensor is
# writable F32 + AdamW state; opt_step on each. See
# docs/roadmap/f3-full-finetune-2026-05-21.md.
smollm2_seq_full_finetune_cuda:        demos/smollm2_seq_full_finetune_cuda
demos/smollm2_seq_full_finetune_cuda: demos/smollm2_seq_full_finetune_cuda.rb lib/llama_seq_forward_ffi_cuda.rb lib/toy_smollm2_loader.rb lib/transformer.rb lib/gpt2.rb lib/gguf_load.rb lib/tinynn.rb lib/tinynn_cuda.rb tinynn/libtinynn_ggml.a tinynn/libtinynn_ggml_cuda.a
	$(SPINEL) --cc='cc -Wl,-u,tnn_cuda_force_link' $< -o $@

# F4 (QLoRA) on CUDA via realize_for_q8_copy. Q8 base in standard
# CUDA buffer + F32 LoRA adapter; bypasses the BYO-pointer padding bug.
smollm2_seq_qlora_cuda:        demos/smollm2_seq_qlora_cuda
demos/smollm2_seq_qlora_cuda: demos/smollm2_seq_qlora_cuda.rb lib/llama_seq_forward_ffi_cuda.rb lib/toy_smollm2_loader.rb lib/transformer.rb lib/gpt2.rb lib/gguf_load.rb lib/tinynn.rb lib/tinynn_cuda.rb tinynn/libtinynn_ggml.a tinynn/libtinynn_ggml_cuda.a
	$(SPINEL) --cc='cc -Wl,-u,tnn_cuda_force_link' $< -o $@

# Per-phase training-step bench (CPU + CUDA). Times graph_reset /
# uploads / compute_backward / download separately. Doc:
# docs/design/bench-train-2026-05-21.md.
smollm2_lora_train_bench:        demos/smollm2_lora_train_bench
demos/smollm2_lora_train_bench: demos/smollm2_lora_train_bench.rb lib/toy_smollm2_ffi_kv.rb lib/toy_smollm2_loader.rb lib/transformer.rb lib/gpt2.rb lib/gguf_load.rb lib/tinynn.rb tinynn/libtinynn_ggml.a
	$(SPINEL) $< -o $@

smollm2_lora_train_bench_cuda:        demos/smollm2_lora_train_bench_cuda
demos/smollm2_lora_train_bench_cuda: demos/smollm2_lora_train_bench_cuda.rb lib/toy_smollm2_ffi_kv_cuda.rb lib/toy_smollm2_loader.rb lib/transformer.rb lib/gpt2.rb lib/gguf_load.rb lib/tinynn_cuda.rb tinynn/libtinynn_ggml.a tinynn/libtinynn_ggml_cuda.a
	$(SPINEL) --cc='cc -Wl,-u,tnn_cuda_force_link' $< -o $@

# Task #70 grad-magnitude probes (per-layer maxabs(grad_A), maxabs(grad_B)).
smollm2_lora_grad_probe:        demos/smollm2_lora_grad_probe
demos/smollm2_lora_grad_probe: demos/smollm2_lora_grad_probe.rb lib/toy_smollm2_ffi_kv.rb lib/toy_smollm2_loader.rb lib/transformer.rb lib/gpt2.rb lib/gguf_load.rb lib/tinynn.rb tinynn/libtinynn_ggml.a
	$(SPINEL) $< -o $@

smollm2_lora_grad_probe_cuda:        demos/smollm2_lora_grad_probe_cuda
demos/smollm2_lora_grad_probe_cuda: demos/smollm2_lora_grad_probe_cuda.rb lib/toy_smollm2_ffi_kv_cuda.rb lib/toy_smollm2_loader.rb lib/transformer.rb lib/gpt2.rb lib/gguf_load.rb lib/tinynn_cuda.rb tinynn/libtinynn_ggml.a tinynn/libtinynn_ggml_cuda.a
	$(SPINEL) --cc='cc -Wl,-u,tnn_cuda_force_link' $< -o $@

# Qwen2.5 Phase-2 mmap inference (CUDA). Requires `make setup-ggml-cuda`.
qwen25_native_mmap_cuda:        demos/qwen25_native_mmap_cuda
demos/qwen25_native_mmap_cuda: demos/qwen25_native_mmap_cuda.rb lib/toy.rb lib/toy_smollm2.rb lib/toy_smollm2_loader.rb lib/toy_smollm2_ffi_kv_cuda.rb lib/transformer.rb lib/gpt2.rb lib/gguf_load.rb lib/training.rb lib/tinynn_cuda.rb tinynn/libtinynn_ggml.a tinynn/libtinynn_ggml_cuda.a
	$(SPINEL) --cc='cc -Wl,-u,tnn_cuda_force_link' $< -o $@

# SmolLM2-135M FFI KV-cache (CUDA).
smollm2_kv_cuda:        demos/smollm2_kv_cuda
demos/smollm2_kv_cuda: demos/smollm2_kv_cuda.rb lib/toy_card.rb lib/toy.rb lib/toy_smollm2.rb lib/toy_smollm2_loader.rb lib/toy_smollm2_ffi_kv_cuda.rb lib/transformer.rb lib/gpt2.rb lib/gguf_load.rb lib/training.rb lib/tinynn_cuda.rb tinynn/libtinynn_ggml.a tinynn/libtinynn_ggml_cuda.a
	$(SPINEL) $< -o $@

# TinyLlama-1.1B demo. Uses the same Toy::SmolLM2 / FFI KV CUDA stack
# (llama-family architecture); just configured for the larger shape.
tinyllama_kv_cuda:        demos/tinyllama_kv_cuda
demos/tinyllama_kv_cuda: demos/tinyllama_kv_cuda.rb lib/toy_card.rb lib/toy.rb lib/toy_smollm2.rb lib/toy_smollm2_loader.rb lib/toy_smollm2_ffi_kv_cuda.rb lib/transformer.rb lib/gpt2.rb lib/gguf_load.rb lib/training.rb lib/tinynn_cuda.rb tinynn/libtinynn_ggml.a tinynn/libtinynn_ggml_cuda.a
	$(SPINEL) $< -o $@

tinyllama:        demos/tinyllama
demos/tinyllama: demos/tinyllama.rb lib/toy_card.rb lib/toy.rb lib/toy_smollm2.rb lib/toy_smollm2_loader.rb lib/transformer.rb lib/gpt2.rb lib/gguf_load.rb lib/training.rb lib/tinynn.rb tinynn/libtinynn_ggml.a
	$(SPINEL) $< -o $@

tinyllama_kv:        demos/tinyllama_kv
demos/tinyllama_kv: demos/tinyllama_kv.rb lib/toy_card.rb lib/toy.rb lib/toy_smollm2.rb lib/toy_smollm2_loader.rb lib/toy_smollm2_ffi_kv.rb lib/transformer.rb lib/gpt2.rb lib/gguf_load.rb lib/training.rb lib/tinynn.rb tinynn/libtinynn_ggml.a
	$(SPINEL) $< -o $@

# Print the Phuong–Hutter algorithm cards for both models. No
# inference — just emit the structured pseudocode. Source-of-truth
# for the round-trip work (task #33).
algorithm_cards:        demos/algorithm_cards
demos/algorithm_cards: demos/algorithm_cards.rb lib/toy_card.rb lib/toy.rb lib/toy_gpt2.rb lib/toy_smollm2.rb lib/toy_gpt2_loader.rb lib/toy_smollm2_loader.rb lib/transformer.rb lib/gpt2.rb lib/gguf_load.rb lib/tinynn.rb tinynn/libtinynn_ggml.a
	$(SPINEL) $< -o $@

# TinyStories from-scratch training via Toy::Trainer.
#
train:        demos/train
demos/train: demos/train.rb lib/toy_trainer.rb lib/transformer.rb lib/training.rb lib/tinynn.rb tinynn/libtinynn_ggml.a
	$(SPINEL) $< -o $@

# Parity probe: one forward at distilgpt2 shape, dump last-row logits
# to data/ours_logits.txt. Pair with prep/parity.py for the HF reference.
gpt2-parity: tinynn/gpt2_parity
	./tinynn/gpt2_parity

tinynn/gpt2_parity: tinynn/gpt2_parity.rb lib/transformer.rb lib/gpt2.rb lib/gguf_load.rb lib/training.rb lib/tinynn.rb tinynn/libtinynn_ggml.a
	$(SPINEL) tinynn/gpt2_parity.rb -o tinynn/gpt2_parity

# FFI parity probe: persistent ggml graph with LayerNorm + biases.
# Dumps last-row logits to data/ours_ffi_logits.txt.
gpt2-ffi-parity: tinynn/gpt2_ffi_parity
	./tinynn/gpt2_ffi_parity

tinynn/gpt2_ffi_parity: tinynn/gpt2_ffi_parity.rb lib/transformer.rb lib/gpt2.rb lib/gpt2_ffi.rb lib/gguf_load.rb lib/training.rb lib/tinynn.rb tinynn/libtinynn_ggml.a
	$(SPINEL) tinynn/gpt2_ffi_parity.rb -o tinynn/gpt2_ffi_parity

# Apples-to-apples bench: native Mat vs FFI on the same forward.
# Re-encode data/prompt_ids.txt first so prompt length matches T_SEQ=5.
gpt2-bench: tinynn/gpt2_bench
	./tinynn/gpt2_bench

tinynn/gpt2_bench: tinynn/gpt2_bench.rb lib/transformer.rb lib/gpt2.rb lib/gpt2_ffi.rb lib/gpt2_ffi_kv.rb lib/gguf_load.rb lib/training.rb lib/tinynn.rb tinynn/libtinynn_ggml.a
	$(SPINEL) tinynn/gpt2_bench.rb -o tinynn/gpt2_bench

# Ruby BPE smoke: load vocab/merges, encode + roundtrip-decode some
# fixed prompts. Compare against prep/tokens.py output.
bpe-smoke: tinynn/bpe_smoke
	./tinynn/bpe_smoke

tinynn/bpe_smoke: tinynn/bpe_smoke.rb lib/transformer.rb lib/bpe.rb lib/tinynn.rb tinynn/libtinynn_ggml.a
	$(SPINEL) tinynn/bpe_smoke.rb -o tinynn/bpe_smoke

# KV-cache parity probe: prefill the prompt one token at a time through
# GPT2KVFFICache, dump last-position logits.
gpt2-kv-parity: tinynn/gpt2_kv_parity
	./tinynn/gpt2_kv_parity

tinynn/gpt2_kv_parity: tinynn/gpt2_kv_parity.rb lib/transformer.rb lib/gpt2.rb lib/gpt2_ffi_kv.rb lib/gguf_load.rb lib/training.rb lib/tinynn.rb tinynn/libtinynn_ggml.a
	$(SPINEL) tinynn/gpt2_kv_parity.rb -o tinynn/gpt2_kv_parity

# --- CUDA mirrors of the GPT-2 demos / parity / bench --------------
# All require `make setup-ggml-cuda` to have produced
# vendor/ggml/build-cuda first. Built on the gx10 (NVIDIA GB10);
# the Mac build doesn't have CUDA.

CUDA_GPT2_DEPS = lib/transformer.rb lib/gpt2.rb lib/gguf_load.rb \
                 lib/training.rb lib/tinynn.rb lib/tinynn_cuda.rb \
                 tinynn/libtinynn_ggml.a tinynn/libtinynn_ggml_cuda.a

gpt2-ffi-parity-cuda: tinynn/gpt2_ffi_parity_cuda
	./tinynn/gpt2_ffi_parity_cuda

tinynn/gpt2_ffi_parity_cuda: tinynn/gpt2_ffi_parity_cuda.rb lib/gpt2_ffi_cuda.rb $(CUDA_GPT2_DEPS)
	$(SPINEL) tinynn/gpt2_ffi_parity_cuda.rb -o tinynn/gpt2_ffi_parity_cuda

gpt2-kv-parity-cuda: tinynn/gpt2_kv_parity_cuda
	./tinynn/gpt2_kv_parity_cuda

tinynn/gpt2_kv_parity_cuda: tinynn/gpt2_kv_parity_cuda.rb lib/gpt2_ffi_kv_cuda.rb $(CUDA_GPT2_DEPS)
	$(SPINEL) tinynn/gpt2_kv_parity_cuda.rb -o tinynn/gpt2_kv_parity_cuda

gpt2-bench-cuda: tinynn/gpt2_bench_cuda
	./tinynn/gpt2_bench_cuda

tinynn/gpt2_bench_cuda: tinynn/gpt2_bench_cuda.rb lib/gpt2_ffi_cuda.rb lib/gpt2_ffi_kv_cuda.rb $(CUDA_GPT2_DEPS)
	$(SPINEL) tinynn/gpt2_bench_cuda.rb -o tinynn/gpt2_bench_cuda

ab-smoke-embed: tinynn/ab_smoke_embed
	./tinynn/ab_smoke_embed

tinynn/ab_smoke_embed: tinynn/ab_smoke_embed.rb lib/transformer.rb lib/tinynn.rb tinynn/libtinynn_ggml.a
	$(SPINEL) tinynn/ab_smoke_embed.rb -o tinynn/ab_smoke_embed

ab-smoke-sgd: tinynn/ab_smoke_sgd
	./tinynn/ab_smoke_sgd

tinynn/ab_smoke_sgd: tinynn/ab_smoke_sgd.rb lib/transformer.rb lib/tinynn.rb tinynn/libtinynn_ggml.a
	$(SPINEL) tinynn/ab_smoke_sgd.rb -o tinynn/ab_smoke_sgd

# F1.2 step 1: multi-step LoRA convergence via the F1.1 in-graph
# optimizer. Toy shape; SGD; 60 steps; asserts final loss < 10% of
# initial (passes at ~10e-13 of initial).
ab-smoke-lora-train: tinynn/ab_smoke_lora_train
	./tinynn/ab_smoke_lora_train

tinynn/ab_smoke_lora_train: tinynn/ab_smoke_lora_train.rb lib/transformer.rb lib/tinynn.rb tinynn/libtinynn_ggml.a
	$(SPINEL) tinynn/ab_smoke_lora_train.rb -o tinynn/ab_smoke_lora_train

# Forward-only smoke: does TransformerLM#forward run at current Spinel
# master? (The #473 SIGBUS is in backward; forward might be OK.)
forward-smoke: tinynn/forward_smoke
	./tinynn/forward_smoke

tinynn/forward_smoke: tinynn/forward_smoke.rb lib/transformer.rb lib/tinynn.rb tinynn/libtinynn_ggml.a
	$(SPINEL) tinynn/forward_smoke.rb -o tinynn/forward_smoke

persistent-bench: tinynn/persistent_bench
	./tinynn/persistent_bench

tinynn/persistent_bench: tinynn/persistent_bench.rb lib/transformer.rb lib/tinynn.rb tinynn/libtinynn_ggml.a
	$(SPINEL) tinynn/persistent_bench.rb -o tinynn/persistent_bench

persistent-bench-cuda: tinynn/persistent_bench_cuda
	./tinynn/persistent_bench_cuda

tinynn/persistent_bench_cuda: tinynn/persistent_bench_cuda.rb lib/transformer.rb lib/tinynn_cuda.rb tinynn/libtinynn_ggml.a
	$(SPINEL) tinynn/persistent_bench_cuda.rb -o tinynn/persistent_bench_cuda

persistent-bench-big: tinynn/persistent_bench_big
	./tinynn/persistent_bench_big

tinynn/persistent_bench_big: tinynn/persistent_bench_big.rb lib/transformer.rb lib/tinynn.rb tinynn/libtinynn_ggml.a
	$(SPINEL) tinynn/persistent_bench_big.rb -o tinynn/persistent_bench_big

# A/B parity test against CUDA backend on the local GPU (sm_121 / GB10).
# Requires `make setup-ggml-cuda` to have produced vendor/ggml/build-cuda.
ab-smoke-cuda: tinynn/ab_smoke_cuda
	./tinynn/ab_smoke_cuda

tinynn/tinynn_backend_cuda.o: tinynn/tinynn_backend_cuda.c
	$(CC) $(CFLAGS) $(GGML_INC) -I$(CUDA_DIR)/include -c $< -o $@

# Only the CUDA backend init goes into the CUDA archive. Common
# wrappers stay in tinynn_ggml.o (CPU archive), referenced from CUDA
# programs via a weak link. Avoids the multi-archive multi-definition
# linker conflict that older two-fat-archive layout had.
tinynn/libtinynn_ggml_cuda.a: tinynn/tinynn_backend_cuda.o
	ar $(ARFLAGS) $@ $<

tinynn/ab_smoke_cuda: tinynn/ab_smoke_cuda.rb lib/transformer.rb lib/tinynn_cuda.rb tinynn/libtinynn_ggml.a
	$(SPINEL) tinynn/ab_smoke_cuda.rb -o tinynn/ab_smoke_cuda

# Consolidated CUDA parity test: matmul + add + gelu + rms_norm + softmax + scale + ffn_pipeline.
ab-smoke-all-cuda: tinynn/ab_smoke_all_cuda
	./tinynn/ab_smoke_all_cuda

tinynn/ab_smoke_all_cuda: tinynn/ab_smoke_all_cuda.rb lib/transformer.rb lib/tinynn_cuda.rb tinynn/libtinynn_ggml.a
	$(SPINEL) tinynn/ab_smoke_all_cuda.rb -o tinynn/ab_smoke_all_cuda

# Transformer-shape parity + wallclock bench on CUDA (GB10).
ab-smoke-big-cuda: tinynn/ab_smoke_big_cuda
	./tinynn/ab_smoke_big_cuda

tinynn/ab_smoke_big_cuda: tinynn/ab_smoke_big_cuda.rb lib/transformer.rb lib/tinynn_cuda.rb tinynn/libtinynn_ggml.a
	$(SPINEL) tinynn/ab_smoke_big_cuda.rb -o tinynn/ab_smoke_big_cuda

# --- maintenance ------------------------------------------------------------
clean:
	rm -f demos/train_minimal demos/train_tinystories \
	      demos/inference_demo demos/inference_demo_cuda \
	      demos/distilgpt2_demo demos/distilgpt2_demo_ffi \
	      demos/distilgpt2_demo_kv demos/distilgpt2_demo_text \
	      demos/distilgpt2_demo_ffi_cuda demos/distilgpt2_demo_kv_cuda \
	      tinynn/tinynn_ggml.o tinynn/libtinynn_ggml.a \
	      tinynn/tinynn_backend_cuda.o tinynn/libtinynn_ggml_cuda.a \
	      tinynn/smoke tinynn/ab_smoke tinynn/ab_smoke_cuda tinynn/ab_smoke_all_cuda \
	      tinynn/ab_smoke_add tinynn/ab_smoke_gelu tinynn/ab_smoke_rms_norm \
	      tinynn/ab_smoke_softmax tinynn/ab_smoke_transpose tinynn/ab_smoke_scale \
	      tinynn/ab_smoke_pipeline tinynn/ab_smoke_big tinynn/ab_smoke_big_cuda \
	      tinynn/ab_smoke_matmul_variants tinynn/ab_smoke_back tinynn/ab_smoke_embed \
	      tinynn/ab_smoke_sgd tinynn/ab_smoke_gelu_back tinynn/ab_smoke_cegrad \
	      tinynn/ab_smoke_adam tinynn/forward_smoke tinynn/persistent_bench \
	      tinynn/persistent_bench_cuda tinynn/persistent_bench_big

distclean: clean
	rm -rf $(GGML_DIR)/build $(GGML_DIR)/build-cuda

.PHONY: all clean distclean setup-ggml setup-ggml-cuda smoke \
        ab-smoke ab-smoke-add ab-smoke-gelu ab-smoke-rms-norm \
        ab-smoke-softmax ab-smoke-transpose ab-smoke-scale ab-smoke-silu \
        ab-smoke-mul ab-smoke-pipeline ab-smoke-big ab-smoke-cuda \
        ab-smoke-all-cuda ab-smoke-big-cuda test \
        gpt2 smollm2 smollm2_kv smollm2_kv_cuda \
        tinyllama tinyllama_kv tinyllama_kv_cuda \
        train algorithm_cards \
        examples gen-mirrors verify-mirrors
