# lib/toy/llm/engine/ar_engine.rb — the toy#166 (capstone P1b)
# AUTOREGRESSIVE BYTE-LM: a causal transformer over bytes, next-byte
# cross-entropy. It plays TWO roles in this lane and the difference
# between them is load-bearing.
#
#   1. THE YARDSTICK ARM (`--arm ar-baseline`). What "good" looks like
#      on a small English corpus at matched size. The diffusion arm is
#      expected to TRAIL it (LD4LG: MAUVE .72 vs .79) — the bar is
#      "closer to this than to the prior floor", not "beats it".
#
#   2. THE JUDGE. Every arm's generated bytes are scored under an AR
#      model's NLL. That model is trained on a DIFFERENT SEED and is
#      never an arm, because a model assigns unusually low NLL to its
#      OWN samples — they are drawn from exactly the distribution being
#      measured. Scoring the ar-baseline arm under itself would hand the
#      ceiling an unquantifiable advantage and the whole "somewhat
#      competitive" bar is stated against that anchor.
#
# Same forward as the ae encoder except for two things, and both matter:
#
#   * ATTENTION IS CAUSAL — an additive [T, T] mask, uploaded once. The
#     ae lane is deliberately bidirectional (reconstruction is not
#     prediction); this lane is deliberately not.
#   * THE TARGET IS THE NEXT BYTE, so position i predicts token i+1 and
#     the last position has no target at all. Its label row is left ALL
#     ZERO, which contributes nothing to the cross-entropy. The NLL used
#     for scoring is NOT this loss — it is computed in Ruby from the
#     downloaded logits over positions 0..T-2, so the reported
#     bits/byte is exact and carries no off-by-one from the padded row.
#
# CPU-only (tao#18). All BP: no DFA on this lane (that is P1c, and it
# attaches to the DENOISER, whose output dim is the latent — a 256-way
# head is exactly the shape F22 concluded killed the LM lane).
#
# Spinel hygiene: plain class, no-arg ctor, no Struct, typed-empty array
# seeds, while loops, no #{}.

require_relative "../../models/transformer"

module Toy; module LLM; module Engine
class ArEngine
  VOCAB = 256
  # Softmax-safe "closed" entry: exp(-30) is ~9e-14, dead in f32 without
  # being -inf, so a fully-masked row degrades to uniform, not to NaN.
  MASK_NEG = -30.0

  attr_accessor :sess,
                :ar_d_model, :ar_heads, :ar_d_head, :ar_d_ff, :ar_blocks,
                :ar_context,
                :ft_weights, :ft_m, :ft_v, :ft_din, :ft_dout, :ft_names,
                :t_tokens, :t_mask, :t_labels, :t_hp, :t_logits, :t_loss,
                :ar_graph_nodes, :ar_graph_bytes

  def initialize
    @sess       = TinyNN.tnn_null_ptr
    @ar_d_model = 0
    @ar_heads   = 0
    @ar_d_head  = 0
    @ar_d_ff    = 0
    @ar_blocks  = 0
    @ar_context = 0
    @ft_weights = [TinyNN.tnn_null_ptr]; @ft_weights.pop
    @ft_m       = [TinyNN.tnn_null_ptr]; @ft_m.pop
    @ft_v       = [TinyNN.tnn_null_ptr]; @ft_v.pop
    @ft_din     = [0]; @ft_din.pop
    @ft_dout    = [0]; @ft_dout.pop
    @ft_names   = [""]; @ft_names.pop
    @t_tokens = TinyNN.tnn_null_ptr
    @t_mask   = TinyNN.tnn_null_ptr
    @t_labels = TinyNN.tnn_null_ptr
    @t_hp     = TinyNN.tnn_null_ptr
    @t_logits = TinyNN.tnn_null_ptr
    @t_loss   = TinyNN.tnn_null_ptr
    @ar_graph_nodes = 0
    @ar_graph_bytes = 0
  end

  def realize_for_random_init(d_model, heads, d_ff, n_blocks, context,
                              seed, init_scale)
    @ar_d_model = d_model
    @ar_heads   = heads
    @ar_d_head  = d_model / heads
    @ar_d_ff    = d_ff
    @ar_blocks  = n_blocks
    @ar_context = context

    @sess = TinyNN.tnn_session_new(0)
    TinyNN.tnn_session_set_graph_capacity(@sess, n_blocks * 400 + 262144)

    add_w(VOCAB,   d_model, "emb")
    add_w(context, d_model, "pos")
    bi = 0
    while bi < n_blocks
      p = "b" + bi.to_s + "."
      h = 0
      while h < heads
        add_w(@ar_d_head, d_model, p + "q" + h.to_s)
        add_w(@ar_d_head, d_model, p + "k" + h.to_s)
        add_w(@ar_d_head, d_model, p + "v" + h.to_s)
        h = h + 1
      end
      add_w(d_model, d_model, p + "o")
      add_w(d_ff,    d_model, p + "up")
      add_w(d_model, d_ff,    p + "down")
      add_w(1, d_model, p + "ln1")
      add_w(1, d_model, p + "ln2")
      bi = bi + 1
    end
    add_w(1, d_model, "ln_f")
    add_w(VOCAB, d_model, "head")
    add_w(1, VOCAB, "head_bias")

    wi = 0
    while wi < @ft_weights.length
      TinyNN.tnn_set_param(@ft_weights[wi])
      wi = wi + 1
    end

    @t_tokens = TinyNN.tnn_input_1d_i32_persistent(@sess, context)
    @t_mask   = TinyNN.tnn_input_2d_f32_persistent(@sess, context, context)
    TinyNN.tnn_tensor_set_name(@t_mask, "causal_mask")

    TinyNN.tnn_finalize_weights(@sess)
    upload_random_init!(seed, init_scale)
    nil
  end

  def build_training_step
    TinyNN.tnn_reset_for_rebuild(@sess)

    t_emb = TinyNN.tnn_get_rows(@sess, @ft_weights[0], @t_tokens)
    t_h   = TinyNN.tnn_add(@sess, t_emb, @ft_weights[1])

    scale = 1.0 / Math.sqrt(@ar_d_head.to_f)
    bj = 0
    while bj < @ar_blocks
      base = 2 + bj * (3 * @ar_heads + 5)
      t_n1 = TinyNN.tnn_rms_norm(@sess, t_h,
               @ft_weights[base + 3 * @ar_heads + 3], 1.0e-5)
      t_heads = [TinyNN.tnn_null_ptr]; t_heads.pop
      hh = 0
      while hh < @ar_heads
        t_q = TinyNN.tnn_matmul(@sess, @ft_weights[base + hh * 3],     t_n1)
        t_k = TinyNN.tnn_matmul(@sess, @ft_weights[base + hh * 3 + 1], t_n1)
        t_v = TinyNN.tnn_matmul(@sess, @ft_weights[base + hh * 3 + 2], t_n1)
        # scores ne=[T_key, T_query]; the CAUSAL mask is additive and
        # applied before the softmax, so no position can read its future.
        t_sc = TinyNN.tnn_softmax(@sess,
                 TinyNN.tnn_add(@sess,
                   TinyNN.tnn_scale(@sess,
                     TinyNN.tnn_matmul(@sess, t_k, t_q), scale),
                   @t_mask))
        t_heads.push(TinyNN.tnn_matmul(@sess, TinyNN.tnn_transpose(@sess, t_v), t_sc))
        hh = hh + 1
      end
      t_cat = t_heads[0]
      hc = 1
      while hc < @ar_heads
        t_cat = TinyNN.tnn_concat(@sess, t_cat, t_heads[hc], 0)
        hc = hc + 1
      end
      t_a = TinyNN.tnn_add(@sess, t_h,
              TinyNN.tnn_matmul(@sess, @ft_weights[base + 3 * @ar_heads], t_cat))
      t_n2 = TinyNN.tnn_rms_norm(@sess, t_a,
               @ft_weights[base + 3 * @ar_heads + 4], 1.0e-5)
      t_up = TinyNN.tnn_silu(@sess,
               TinyNN.tnn_matmul(@sess, @ft_weights[base + 3 * @ar_heads + 1], t_n2))
      t_h  = TinyNN.tnn_add(@sess, t_a,
               TinyNN.tnn_matmul(@sess, @ft_weights[base + 3 * @ar_heads + 2], t_up))
      bj = bj + 1
    end

    nw = @ft_weights.length
    t_f = TinyNN.tnn_rms_norm(@sess, t_h, @ft_weights[nw - 3], 1.0e-5)
    @t_logits = TinyNN.tnn_add(@sess,
                  TinyNN.tnn_matmul(@sess, @ft_weights[nw - 2], t_f),
                  @ft_weights[nw - 1])
    TinyNN.tnn_set_output(@t_logits)

    @t_labels = TinyNN.tnn_input_2d_f32(@sess, @ar_context, VOCAB)
    @t_hp     = TinyNN.tnn_input_1d_f32(@sess, 7)
    @t_loss   = TinyNN.tnn_cross_entropy_loss(@sess, @t_logits, @t_labels)
    TinyNN.tnn_set_output(@t_loss)

    TinyNN.tnn_set_loss(@t_loss)
    TinyNN.tnn_build_forward_only(@sess, @t_loss)
    TinyNN.tnn_build_backward(@sess)

    wk = 0
    while wk < @ft_weights.length
      tg = TinyNN.tnn_tensor_grad(@sess, @ft_weights[wk])
      to = TinyNN.tnn_opt_step_adamw(@sess, @ft_weights[wk], tg,
                                      @ft_m[wk], @ft_v[wk], @t_hp)
      TinyNN.tnn_extend_backward_graph(@sess, to)
      wk = wk + 1
    end

    puts "ar: blocks=" + @ar_blocks.to_s +
         " d_model=" + @ar_d_model.to_s +
         " heads=" + @ar_heads.to_s +
         " d_ff=" + @ar_d_ff.to_s +
         " context=" + @ar_context.to_s +
         " attn=causal params=" + param_count.to_s

    TinyNN.tnn_pin_all_graph_b_nodes(@sess)
    TinyNN.tnn_realize_backward(@sess)
    measure_graph!
    [@t_loss, @t_labels, @t_hp]
  end

  # The additive causal mask, [T_key, T_query] flat as query * T + key.
  def fill_causal_mask!(buf)
    q = 0
    while q < @ar_context
      k = 0
      while k < @ar_context
        if k <= q
          buf[q * @ar_context + k] = 0.0
        else
          buf[q * @ar_context + k] = MASK_NEG
        end
        k = k + 1
      end
      q = q + 1
    end
    nil
  end

  def measure_graph!
    @ar_graph_nodes = TinyNN.tnn_graph_n_nodes(@sess)
    total = 0
    i = 0
    while i < @ar_graph_nodes
      total = total + TinyNN.tnn_tensor_nbytes(TinyNN.tnn_graph_node(@sess, i))
      i = i + 1
    end
    @ar_graph_bytes = total
    nil
  end

  def param_count
    n = 0
    wi = 0
    while wi < @ft_weights.length
      n = n + @ft_din[wi] * @ft_dout[wi]
      wi = wi + 1
    end
    n
  end

  def add_w(dout, din, name)
    w = TinyNN.tnn_input_2d_f32_persistent(@sess, dout, din)
    m = TinyNN.tnn_input_2d_f32_persistent(@sess, dout, din)
    v = TinyNN.tnn_input_2d_f32_persistent(@sess, dout, din)
    TinyNN.tnn_tensor_set_name(w, name)
    TinyNN.tnn_tensor_set_name(m, name + ".m")
    TinyNN.tnn_tensor_set_name(v, name + ".v")
    @ft_weights.push(w)
    @ft_m.push(m)
    @ft_v.push(v)
    @ft_din.push(din)
    @ft_dout.push(dout)
    @ft_names.push(name)
    nil
  end

  def upload_random_init!(seed, init_scale)
    state = xorshift_seed_state(seed)
    wi = 0
    while wi < @ft_weights.length
      n  = @ft_din[wi] * @ft_dout[wi]
      nm = @ft_names[wi]
      if nm == "head_bias"
        upload_const(@ft_weights[wi], n, 0.0)
      elsif nm == "ln_f" || (nm.length > 3 &&
         (nm[nm.length - 3, 3] == "ln1" || nm[nm.length - 3, 3] == "ln2"))
        upload_const(@ft_weights[wi], n, 1.0)
      else
        std = init_scale / Math.sqrt(@ft_din[wi].to_f)
        upload_gaussian(@ft_weights[wi], n, std, state)
      end
      zero_tensor(@ft_m[wi])
      zero_tensor(@ft_v[wi])
      wi = wi + 1
    end
    nil
  end

  def xorshift_seed_state(seed)
    s = ((seed + 104729) * 2654435761) % 2147483647
    if s <= 0
      s = seed + 104729
    end
    w = 0
    while w < 8
      s = (s * 1103515245 + 12345) & 0x7FFFFFFF
      w = w + 1
    end
    [s]
  end

  def upload_gaussian(tensor, n, std, state)
    buf = Array.new(n, 0.0)
    i = 0
    while i < n
      s = state[0]
      s = (s * 1103515245 + 12345) & 0x7FFFFFFF
      state[0] = s
      u1 = (s.to_f + 1.0) / 2147483648.0
      s = state[0]
      s = (s * 1103515245 + 12345) & 0x7FFFFFFF
      state[0] = s
      u2 = (s.to_f + 1.0) / 2147483648.0
      if u1 < 1.0e-12; u1 = 1.0e-12; end
      z = Math.sqrt(-2.0 * Math.log(u1)) * Math.cos(2.0 * Math::PI * u2)
      buf[i] = z * std
      i = i + 1
    end
    TinyNN.tnn_upload_from_float_array(@sess, tensor, buf, n)
  end

  def upload_const(tensor, n, v)
    buf = Array.new(n, v)
    TinyNN.tnn_upload_from_float_array(@sess, tensor, buf, n)
  end

  def zero_tensor(tensor)
    n = TinyNN.tnn_tensor_nelements(tensor)
    buf = Array.new(n, 0.0)
    TinyNN.tnn_upload_from_float_array(@sess, tensor, buf, n)
  end
end
end; end; end
