#!/usr/bin/env ruby
# Generate the GPU-backend mirror of a CPU FFI source file by
# mechanical substitution. The CPU file is the source of truth; the
# GPU files (CUDA, Metal) are build artifacts (committed so reviewers
# see both).
#
# Phase 0.6 — graph-inlining refactor. The Spinel ivar-collision that
# made an `include Module` approach impractical doesn't matter here:
# we still get distinct compiled classes per backend (Spinel-friendly),
# but one human-readable Ruby source file.
#
# Usage:
#   prep/gen_cuda_mirror.rb [file1 file2 ...]
#       -> regenerate both CUDA and Metal mirrors for each input
#          (default: every file in MIRRORABLE below).
#
#   prep/gen_cuda_mirror.rb --backend cuda|metal [file ...]
#       -> regenerate only the named backend's mirrors.
#
#   prep/gen_cuda_mirror.rb --verify [file ...]
#       -> compare each on-disk mirror against what we'd generate;
#          exit non-zero on drift. Use in CI / `make verify-mirrors`.
#
# === Sentinel syntax ===
#
# To carry a CPU-only block over the mirror line, wrap it:
#
#     # CUDA-MIRROR-SKIP-BEGIN: <reason>
#     <CPU-only code, any length>
#     # CUDA-MIRROR-SKIP-END
#
# The block is dropped from the GPU mirrors. Optionally precede the
# skipped lines with one or more STUB lines whose contents replace
# the block in the GPU mirror:
#
#     # CUDA-MIRROR-SKIP-BEGIN: trace-tap is CPU-only diagnostic
#     # CUDA-MIRROR-STUB: def trace_tap(_name, t)
#     # CUDA-MIRROR-STUB:   t
#     # CUDA-MIRROR-STUB: end
#     def trace_tap(name_, t)
#       if @trace_on
#         ...full CPU implementation...
#       end
#       t
#     end
#     # CUDA-MIRROR-SKIP-END
#
# In the GPU mirror, the three STUB lines become uncommented Ruby
# code in place of the original method body. STUB lines must appear
# *before* the first non-sentinel non-comment line of the block.
#
# Sentinels are spelled `CUDA-MIRROR-*` for backwards compatibility;
# they apply uniformly to every backend.

require "fileutils"

MIRRORABLE = [
  "lib/llama_seq_forward_ffi.rb",       # M3 (sequence-mode forward + LoRA)
  "lib/toy_smollm2_ffi_kv.rb",          # KV-cache decode (Phase 0.6 step 2)
  "lib/gpt2_ffi.rb",                    # GPT-2 full-forward FFI (Phase 0.6 step 3)
  "lib/gpt2_ffi_kv.rb",                 # GPT-2 KV-cache decode (Phase 0.6 step 3)
  "examples/06_train_from_scratch.rb",  # #152: from-scratch training entry (CPU/CUDA)
]

# Per-backend codegen parameters.
BACKENDS = {
  cuda:  { suffix: "Cuda",  session: 1, tinynn: "tinynn_cuda",  label: "CUDA"  },
  metal: { suffix: "Metal", session: 2, tinynn: "tinynn_metal", label: "Metal" },
}

# Build the substitution table for a given (file, backend). Each
# input file gets a per-file table because class names differ; the
# backend supplies the suffix + session + module rename. Order
# matters: longer-suffix variants must come first so we don't double-
# rename (e.g. don't run `TinyNN → TinyNNCuda` after we've already
# produced `TinyNNCuda`).
def subs_for(cpu_path, backend)
  cfg     = BACKENDS.fetch(backend)
  suffix  = cfg[:suffix]
  module_ = "TinyNN" + suffix
  session = cfg[:session]
  tinynn  = cfg[:tinynn]
  label   = cfg[:label]

  common_module_tail = [
    [/\bTinyNN\.\b/,                   module_ + "."],
    [/\bTinyNN\b/,                     module_],
    [/tnn_session_new\(0\)/,           "tnn_session_new(" + session.to_s + ")"],
    [/^require_relative "tinynn"$/,    'require_relative "' + tinynn + '"'],
  ]

  case cpu_path
  when "lib/llama_seq_forward_ffi.rb"
    [
      [/^# lib\/llama_seq_forward_ffi\.rb.*$/,
       "# lib/llama_seq_forward_ffi_#{backend}.rb — #{label} mirror of lib/llama_seq_forward_ffi.rb.\n" +
       "#\n" +
       "# AUTO-GENERATED by prep/gen_cuda_mirror.rb. Do not edit by hand;\n" +
       "# edit the CPU source and re-run the generator. The CPU file's\n" +
       "# header explains the architecture; this mirror keeps the same\n" +
       "# contract on the GPU backend via #{module_}."],
      [/\bLlamaSeqForwardFFICache\b/, "LlamaSeqForwardFFICache" + suffix],
      [/\bLlamaSeqBlockFFI\b/,        "LlamaSeqBlockFFI"        + suffix],
    ] + common_module_tail

  when "lib/toy_smollm2_ffi_kv.rb"
    [
      [/^# lib\/toy_smollm2_ffi_kv\.rb.*$/,
       "# lib/toy_smollm2_ffi_kv_#{backend}.rb — #{label} mirror of lib/toy_smollm2_ffi_kv.rb.\n" +
       "#\n" +
       "# AUTO-GENERATED by prep/gen_cuda_mirror.rb. Do not edit by hand;\n" +
       "# edit the CPU source and re-run the generator. The CPU file's\n" +
       "# header explains the architecture; this mirror keeps the same\n" +
       "# contract on the GPU backend via #{module_}."],
      # Class names — longer ones first (KV is a substring of KVBlock).
      [/\bSmolLM2KVStepResult\b/,    "SmolLM2KVStepResult" + suffix],
      [/\bSmolLM2KVFFICache\b/,      "SmolLM2KVFFICache"   + suffix],
      [/\bSmolLM2KVBlockFFI\b/,      "SmolLM2KVBlockFFI"   + suffix],
      # Module — the ".decode_step" wrapper.
      [/\bSmolLM2KV\.decode_step\b/, "SmolLM2KV" + suffix + ".decode_step"],
      [/\bSmolLM2KV\.upload_from\b/, "SmolLM2KV" + suffix + ".upload_from"],
      [/^module SmolLM2KV$/,         "module SmolLM2KV" + suffix],
    ] + common_module_tail

  when "lib/gpt2_ffi.rb"
    [
      [/^# lib\/gpt2_ffi\.rb.*$/,
       "# lib/gpt2_ffi_#{backend}.rb — #{label} mirror of lib/gpt2_ffi.rb.\n" +
       "#\n" +
       "# AUTO-GENERATED by prep/gen_cuda_mirror.rb. Do not edit by hand."],
      [/\bGPT2FullForwardFFICache\b/, "GPT2FullForwardFFICache" + suffix],
      [/\bGPT2BlockFFI\b/,            "GPT2BlockFFI"            + suffix],
      [/\bGPT2FFI\b/,                 "GPT2FFI"                 + suffix],
    ] + common_module_tail

  when "lib/gpt2_ffi_kv.rb"
    [
      [/^# lib\/gpt2_ffi_kv\.rb.*$/,
       "# lib/gpt2_ffi_kv_#{backend}.rb — #{label} mirror of lib/gpt2_ffi_kv.rb.\n" +
       "#\n" +
       "# AUTO-GENERATED by prep/gen_cuda_mirror.rb. Do not edit by hand."],
      [/\bGPT2KVStepResult\b/,        "GPT2KVStepResult" + suffix],
      [/\bGPT2KVFFICache\b/,          "GPT2KVFFICache"   + suffix],
      [/\bGPT2KVBlockFFI\b/,          "GPT2KVBlockFFI"   + suffix],
      [/\bGPT2KV\.decode_step\b/,     "GPT2KV" + suffix + ".decode_step"],
      [/\bGPT2KV\.upload_from\b/,     "GPT2KV" + suffix + ".upload_from"],
      [/^module GPT2KV$/,             "module GPT2KV" + suffix],
    ] + common_module_tail

  when "examples/06_train_from_scratch.rb"
    # #152 — CUDA mirror of the from-scratch training entry. Rewrites
    # the require to the GPU-side llama_seq_forward_ffi mirror, renames
    # LlamaSeqForwardFFICache to its backend variant, and swaps every
    # TinyNN. call to TinyNN<Suffix>. (handled by common_module_tail).
    [
      [/^require_relative "..\/lib\/llama_seq_forward_ffi"$/,
       'require_relative "../lib/llama_seq_forward_ffi_' + backend.to_s + '"'],
      [/\bLlamaSeqForwardFFICache\b/, "LlamaSeqForwardFFICache" + suffix],
    ] + common_module_tail

  else
    nil
  end
end

SKIP_OPEN   = /^\s*# CUDA-MIRROR-SKIP-BEGIN(?::.*)?$/
SKIP_CLOSE  = /^\s*# CUDA-MIRROR-SKIP-END\s*$/
STUB_LINE   = /^\s*# CUDA-MIRROR-STUB:\s?(.*)$/

def generate(cpu_path, subs)
  src = File.read(cpu_path)
  out_lines = []
  i = 0
  lines = src.lines
  while i < lines.length
    line = lines[i]
    if line =~ SKIP_OPEN
      # Scan the entire SKIP block, collect every STUB line (they may
      # appear anywhere inside, intermixed with comments and code),
      # then advance past SKIP-END.
      stub_lines = []
      j = i + 1
      while j < lines.length && lines[j] !~ SKIP_CLOSE
        if lines[j] =~ STUB_LINE
          stub_lines << $1 + "\n"
        end
        j += 1
      end
      stub_lines.each { |s| out_lines << s }
      i = j + 1  # past SKIP-END
      next
    end
    transformed = line.dup
    subs.each { |re, replacement| transformed.gsub!(re, replacement) }
    out_lines << transformed
    i += 1
  end
  out_lines.join
end

def derive_mirror_path(cpu_path, backend)
  # lib/X_ffi.rb → lib/X_ffi_<backend>.rb (original use case)
  # examples/NN_name.rb → examples/NN_name_<backend>.rb (#152)
  unless cpu_path =~ /_ffi(_[a-z]+)?\.rb$/ || cpu_path =~ %r{^examples/\d+_[a-z0-9_]+\.rb$}
    raise "unrecognised mirror path: #{cpu_path}"
  end
  cpu_path.sub(/\.rb$/, "_#{backend}.rb")
end

verify_only = ARGV.delete("--verify")
backend_arg = nil
if (idx = ARGV.index("--backend"))
  backend_arg = ARGV[idx + 1]&.to_sym
  ARGV.delete_at(idx + 1)
  ARGV.delete_at(idx)
  unless BACKENDS.key?(backend_arg)
    $stderr.puts "[gen_cuda_mirror] unknown backend: #{backend_arg.inspect} (want one of #{BACKENDS.keys.inspect})"
    exit 1
  end
end
inputs   = ARGV.empty? ? MIRRORABLE : ARGV
backends = backend_arg ? [backend_arg] : BACKENDS.keys

drift = false
inputs.each do |cpu_path|
  unless File.exist?(cpu_path)
    $stderr.puts "[gen_cuda_mirror] missing: #{cpu_path}"
    drift = true
    next
  end
  backends.each do |backend|
    subs = subs_for(cpu_path, backend)
    unless subs
      $stderr.puts "[gen_cuda_mirror] no substitution table for #{cpu_path} (backend #{backend})"
      drift = true
      next
    end
    mirror_path = derive_mirror_path(cpu_path, backend)
    generated   = generate(cpu_path, subs)
    if verify_only
      actual = File.exist?(mirror_path) ? File.read(mirror_path) : ""
      if actual == generated
        puts "[gen_cuda_mirror] ok: #{mirror_path} matches generator"
      else
        puts "[gen_cuda_mirror] DRIFT: #{mirror_path} does not match generator output"
        puts "                  edit #{cpu_path} (the source of truth) and re-run"
        puts "                  prep/gen_cuda_mirror.rb #{cpu_path}"
        drift = true
      end
    else
      File.write(mirror_path, generated)
      puts "[gen_cuda_mirror] wrote #{mirror_path} (#{generated.lines.size} lines)"
    end
  end
end

exit(drift ? 1 : 0) if verify_only
