#!/usr/bin/env ruby
# Generate the CUDA-backend mirror of a CPU FFI source file by
# mechanical substitution. The CPU file is the source of truth; the
# CUDA file is the build artifact (committed so reviewers see both).
#
# Phase 0.6 — graph-inlining refactor. The Spinel ivar-collision that
# made an `include Module` approach impractical doesn't matter here:
# we still get two distinct compiled classes (Spinel-friendly), but
# one human-readable Ruby file.
#
# Usage:
#   prep/gen_cuda_mirror.rb lib/llama_seq_forward_ffi.rb
#       -> writes lib/llama_seq_forward_ffi_cuda.rb
#
#   prep/gen_cuda_mirror.rb --verify lib/llama_seq_forward_ffi.rb
#       -> compares the on-disk CUDA file against what we'd generate,
#          exits non-zero on drift. Use in CI / Makefile target.
#
# Files that this works on must be "mechanically mirrorable" — same
# Ruby logic, only the FFI module name + class names + a couple of
# header comments differ. Files with CPU-only or CUDA-only blocks
# (trace tap, alt allocators, ...) need template directives we
# haven't built yet; see the "MIRRORABLE" allowlist below.

require "fileutils"

MIRRORABLE = [
  "lib/llama_seq_forward_ffi.rb",   # M3 (sequence-mode forward + LoRA)
]

# Ordered substitution list. The first hit wins per-line; order
# matters because the CUDA names contain the CPU names as substrings
# (e.g. don't match "TinyNN" after we've already produced "TinyNNCuda").
SUBSTITUTIONS = [
  # File header — replace the "this is the source" preamble with a
  # one-line "this is generated" pointer.
  [/^# lib\/llama_seq_forward_ffi\.rb.*$/,
   "# lib/llama_seq_forward_ffi_cuda.rb — CUDA mirror of lib/llama_seq_forward_ffi.rb.\n" +
   "#\n" +
   "# AUTO-GENERATED by prep/gen_cuda_mirror.rb. Do not edit by hand;\n" +
   "# edit the CPU source and re-run the generator. The CPU file's\n" +
   "# header explains the architecture; this mirror keeps the same\n" +
   "# contract on the GPU backend via TinyNNCuda."],

  # Class names — the seq classes use the FFICache / FFICacheCuda
  # suffix already; we just add "Cuda" before "FFICache" / "FFI" tails.
  [/\bLlamaSeqForwardFFICache\b/, "LlamaSeqForwardFFICacheCuda"],
  [/\bLlamaSeqBlockFFI\b/,        "LlamaSeqBlockFFICuda"],

  # FFI module — must be done AFTER the class renames so we don't
  # touch the (already-renamed) Cuda class names.
  [/\bTinyNN\.\b/,                "TinyNNCuda."],
  [/\bTinyNN\b/,                  "TinyNNCuda"],

  # Backend selector. tnn_session_new(0) selects CPU; (1) selects CUDA.
  [/tnn_session_new\(0\)/,        "tnn_session_new(1)"],

  # require — the CPU file requires "tinynn"; the CUDA mirror needs
  # "tinynn_cuda" (which itself defines TinyNNCuda).
  [/^require_relative "tinynn"$/, 'require_relative "tinynn_cuda"'],
]

# Substitutions that hide CPU-only blocks. These match a *line range*:
# from the OPEN sentinel to the CLOSE sentinel, the block is dropped
# entirely in the CUDA mirror. None today; reserve the slot so when
# the toy_smollm2_ffi_kv pair migrates it has a precedent.
#
# Pattern (when needed):
#   # CUDA-MIRROR-SKIP-BEGIN: <reason>
#   ...CPU-only lines...
#   # CUDA-MIRROR-SKIP-END
CPU_ONLY_OPEN  = /^\s*# CUDA-MIRROR-SKIP-BEGIN:/
CPU_ONLY_CLOSE = /^\s*# CUDA-MIRROR-SKIP-END/

def generate(cpu_path)
  src = File.read(cpu_path)
  out_lines = []
  skipping = false
  src.each_line do |line|
    if skipping
      skipping = false if line =~ CPU_ONLY_CLOSE
      next
    end
    if line =~ CPU_ONLY_OPEN
      skipping = true
      next
    end
    transformed = line.dup
    SUBSTITUTIONS.each { |re, replacement| transformed.gsub!(re, replacement) }
    out_lines << transformed
  end
  out_lines.join
end

def derive_cuda_path(cpu_path)
  raise "expected lib/X_ffi.rb, got #{cpu_path}" unless cpu_path =~ /_ffi\.rb$/
  cpu_path.sub(/_ffi\.rb$/, "_ffi_cuda.rb")
end

verify_only = ARGV.delete("--verify")
inputs      = ARGV.empty? ? MIRRORABLE : ARGV

drift = false
inputs.each do |cpu_path|
  unless File.exist?(cpu_path)
    $stderr.puts "[gen_cuda_mirror] missing: #{cpu_path}"
    drift = true
    next
  end
  cuda_path = derive_cuda_path(cpu_path)
  generated = generate(cpu_path)
  if verify_only
    actual = File.exist?(cuda_path) ? File.read(cuda_path) : ""
    if actual == generated
      puts "[gen_cuda_mirror] ok: #{cuda_path} matches generator"
    else
      puts "[gen_cuda_mirror] DRIFT: #{cuda_path} does not match generator output"
      puts "                  edit #{cpu_path} (the source of truth) and re-run"
      puts "                  prep/gen_cuda_mirror.rb #{cpu_path}"
      drift = true
    end
  else
    File.write(cuda_path, generated)
    puts "[gen_cuda_mirror] wrote #{cuda_path} (#{generated.lines.size} lines)"
  end
end

exit(drift ? 1 : 0) if verify_only
