# lib/toy/llm/blocks/transformer_block_metal.rb — Metal mirror of lib/toy/llm/blocks/transformer_block.rb.
#
# AUTO-GENERATED by prep/gen_cuda_mirror.rb. Do not edit by hand;
# edit the CPU source and re-run the generator. Same L2 contract
# on the GPU backend via TinyNNMetal.
# (RMSNorm + GQA attention with RoPE + SwiGLU FFN), seq-mode forward.
#
# Extracted from lib/llama_seq_forward_ffi.rb (P2.4). This is the
# minimal faithful lift of the former LlamaSeqBlockFFI class +
# build_seq_block / build_seq_qhead / mp_matmul: the forward body is
# moved VERBATIM (op order unchanged → bit-identical output) with only
# mechanical rewrites — the per-forward context the body previously
# read off the cache as @ivars is now passed IN via a positional ctx
# object (TransformerBlockCtx), and the block owns its own weight
# handles (former blk.* are now self.*).
#
# DIVERGENCE from the L2 README sketch: the README shows a forward-
# looking build_forward(sess, x, state, cfg) -> [out, state_out] with a
# KV-cache "state" threaded per block. That incremental KV-decode does
# NOT exist in seq mode — full-sequence forward threads NO per-block KV
# state (KV-cache decode is the separate lib/toy_smollm2_ffi_kv.rb
# path, out of scope here). We adapt to build_forward(sess, t_x, ctx)
# -> t_resid (single handle). We also keep the owned-weight field names
# (t_seq_*) verbatim rather than renaming to the sketch's short names,
# so the cache-side realize / train / tap walkers keep working by
# accessor name with no parity risk.
#
# Spinel hygiene: TransformerBlockCtx is a plain class with an explicit
# positional initialize (NO kwargs, NO default args — default-arg
# poisoning, landmine #4); TransformerBlock#initialize takes NO args and
# has NO default-arg ctor; no Card /
# step_bind / FFI :str args at class load (step_bind :str landmine
# 2026-05-28 — ft_name_last's tnn_tensor_set_name :str stays on the
# cache realize runtime path, not here). The IntArray ptr-array params
# (t_k_per_kv, t_vt_per_kv) keep their trailing positional slots so
# Spinel's locked IntArray param typing (#688) does not shift.
#
# This file does NOT `require_relative "tinynn"`: the loading module
# (lib/llama_seq_forward_ffi.rb) already loads the correct backend's
# TinyNNMetal before requiring this block, exactly like the L1 primitives.
# The mirror generator picks the backend via the monolith's require
# rewrite.

module Toy; module LLM; module Blocks
  # Per-forward read-only context: the 14 config/handle values the body
  # previously read off the cache as @ivars, packed fresh each forward.
  #
  # Plain class with an explicit POSITIONAL initialize (NO default args,
  # NO kwargs) — the same Spinel-safe pattern as RoPE::Cfg. We do NOT use
  # Struct.new here, and the member names keep the original cache's
  # `@seq_*` / `@t_seq_*` prefixes VERBATIM. Both choices are forced by
  # Spinel's whole-program type inference, which unifies an accessor's
  # return type across every class exposing the same accessor name:
  #   - a Struct's auto-generated `#n_heads` collided with
  #     SmolLM2Config#n_heads / CausalSelfAttention#n_heads, breaking an
  #     unrelated call (Toy::SmolLM2#algorithm's `@cfg.n_heads.to_s`);
  #   - short names `#t` / `#b` collided with Toy::Linear#b (a weight
  #     tensor / FloatArray), so `ctx.b`/`ctx.t` were inferred as
  #     FloatArray* and poisoned RoPE.apply_2d / GQA.attention's integer
  #     batch args.
  # The `@seq_*`-prefixed names were chosen on the cache precisely for
  # this type-isolation (see lib/llama_seq_forward_ffi.rb header), so
  # reusing them here keeps every accessor's return type local and
  # concrete. Carries values, no behavior.
  class TransformerBlockCtx
    attr_accessor :seq_scale, :seq_eps, :seq_n_kv, :seq_n_heads, :seq_group_size,
                  :seq_has_qkv_bias, :seq_weight_dtype, :seq_lora_q_enabled,
                  :t_seq_positions, :t_seq_rope_freq_factors, :seq_rope_cfg,
                  :seq_t, :seq_b, :t_seq_attn_mask

    def initialize(seq_scale, seq_eps, seq_n_kv, seq_n_heads, seq_group_size,
                   seq_has_qkv_bias, seq_weight_dtype, seq_lora_q_enabled,
                   t_seq_positions, t_seq_rope_freq_factors, seq_rope_cfg,
                   seq_t, seq_b, t_seq_attn_mask)
      @seq_scale               = seq_scale
      @seq_eps                 = seq_eps
      @seq_n_kv                = seq_n_kv
      @seq_n_heads             = seq_n_heads
      @seq_group_size          = seq_group_size
      @seq_has_qkv_bias        = seq_has_qkv_bias
      @seq_weight_dtype        = seq_weight_dtype
      @seq_lora_q_enabled      = seq_lora_q_enabled
      @t_seq_positions         = t_seq_positions
      @t_seq_rope_freq_factors = t_seq_rope_freq_factors
      @seq_rope_cfg            = seq_rope_cfg
      @seq_t                   = seq_t
      @seq_b                   = seq_b
      @t_seq_attn_mask         = t_seq_attn_mask
    end
  end

  # Per-block tensor handles. Field names are UNCHANGED from the former
  # LlamaSeqBlockFFI so the cache-side realize / train / tap walkers
  # keep working by accessor name.
  class TransformerBlock
    attr_accessor :t_seq_rn1_gamma, :t_seq_rn2_gamma,
                  :t_seq_w_q,  :t_seq_w_k,  :t_seq_w_v,  :t_seq_w_o,
                  :t_seq_b_q,  :t_seq_b_k,  :t_seq_b_v,
                  :t_seq_w_gate, :t_seq_w_up, :t_seq_w_down,
                  # M3 step 3: LoRA-Q adapter pair + persistent Adam moments.
                  :t_seq_w_lora_a_q, :t_seq_w_lora_b_q,
                  :t_seq_w_lora_a_q_m, :t_seq_w_lora_a_q_v,
                  :t_seq_w_lora_b_q_m, :t_seq_w_lora_b_q_v,
                  # F3 full fine-tune (CPU + CUDA via gen_cuda_mirror).
                  # Parallel arrays of (weight, m, v) triples — one entry
                  # per trainable weight tensor in this block.
                  :ft_weights, :ft_m, :ft_v,
                  # GH#15 — per-block activation tap targets for CKA.
                  :tap_attn_norm, :tap_ffn_out, :tap_resid_post

    def initialize
      @t_seq_rn1_gamma = TinyNNMetal.tnn_null_ptr
      @t_seq_rn2_gamma = TinyNNMetal.tnn_null_ptr
      @t_seq_w_q = [TinyNNMetal.tnn_null_ptr]
      @t_seq_w_k = [TinyNNMetal.tnn_null_ptr]
      @t_seq_w_v = [TinyNNMetal.tnn_null_ptr]
      @t_seq_b_q = [TinyNNMetal.tnn_null_ptr]
      @t_seq_b_k = [TinyNNMetal.tnn_null_ptr]
      @t_seq_b_v = [TinyNNMetal.tnn_null_ptr]
      @t_seq_w_o    = TinyNNMetal.tnn_null_ptr
      @t_seq_w_gate = TinyNNMetal.tnn_null_ptr
      @t_seq_w_up   = TinyNNMetal.tnn_null_ptr
      @t_seq_w_down = TinyNNMetal.tnn_null_ptr
      @t_seq_w_lora_a_q   = [TinyNNMetal.tnn_null_ptr]
      @t_seq_w_lora_b_q   = [TinyNNMetal.tnn_null_ptr]
      @t_seq_w_lora_a_q_m = [TinyNNMetal.tnn_null_ptr]
      @t_seq_w_lora_a_q_v = [TinyNNMetal.tnn_null_ptr]
      @t_seq_w_lora_b_q_m = [TinyNNMetal.tnn_null_ptr]
      @t_seq_w_lora_b_q_v = [TinyNNMetal.tnn_null_ptr]
      @ft_weights = [TinyNNMetal.tnn_null_ptr]; @ft_weights.pop
      @ft_m       = [TinyNNMetal.tnn_null_ptr]; @ft_m.pop
      @ft_v       = [TinyNNMetal.tnn_null_ptr]; @ft_v.pop
      @tap_attn_norm  = TinyNNMetal.tnn_null_ptr
      @tap_ffn_out    = TinyNNMetal.tnn_null_ptr
      @tap_resid_post = TinyNNMetal.tnn_null_ptr
    end

    # One transformer block. SEQ-MODE forward: no `state` input, no
    # `state_out` return (KV decode is the separate toy_smollm2_ffi_kv.rb
    # path). The per-forward context (scale, eps, dims, positions, rope
    # cfg, mask, ...) arrives in `ctx`; the block owns its weight handles
    # as self.t_seq_*. Single tensor return (t_resid).
    #
    #   h1   = RMSNorm(x)
    #   per KV head kv_h:
    #     k_pre = w_k[kv_h] @ h1  (+ b_k[kv_h])         ne=[d_head, T]
    #     k     = RoPE(k_pre, positions)
    #     v     = w_v[kv_h] @ h1  (+ b_v[kv_h])         ne=[d_head, T]
    #     v_t   = transpose(v)                          ne=[T, d_head]
    #   per Q head q_h (kv_h = q_h / group_size):
    #     q_pre = w_q[q_h] @ h1  (+ b_q[q_h])           ne=[d_head, T]
    #     q     = RoPE(q_pre, positions)
    #     scores = k[kv_h] @ q                          ne=[T_keys, T_queries]
    #     scaled = scores / sqrt(d_head)
    #     masked = diag_mask_inf(scaled, 0)              causal triangle
    #     attn   = softmax(masked)                       ne=[T, T]
    #     head_h = v_t[kv_h] @ attn                     ne=[d_head, T]
    #   concat heads along ne0 → ne=[d_model, T]
    #   x_attn = x + (w_o @ concat)
    #   h2     = RMSNorm(x_attn)
    #   ff     = w_down @ (silu(w_gate @ h2) * (w_up @ h2))
    #   x_out  = x_attn + ff
    def build_forward(sess, t_x, ctx)
      t_h = Toy::LLM::Primitives::RMSNorm.build(sess, t_x, self.t_seq_rn1_gamma, ctx.seq_eps)
      # GH#15 — tap the post-attn-norm activation. set_output keeps it
      # alive across graph computation so the host can download it.
      self.tap_attn_norm = t_h
      TinyNNMetal.tnn_set_output(t_h)

      # K, V over all KV heads. Pre-compute v_t per head so the per-Q-head
      # attention loop can index it (avoids n_heads × transpose).
      # See the mirror for the Spinel landmine (issue #688 partial fix;
      # the function-parameter type for build_qhead was already locked in
      # as IntArray before the local-var ptr-push promotion runs).
      # Re-verified 2026-05-26: bare `[]` still fires the warning.
      t_k_per_kv  = [TinyNNMetal.tnn_null_ptr]; t_k_per_kv.pop
      t_vt_per_kv = [TinyNNMetal.tnn_null_ptr]; t_vt_per_kv.pop
      hkv = 0
      while hkv < ctx.seq_n_kv
        t_k_raw = mp_matmul(sess, ctx.seq_weight_dtype, self.t_seq_w_k[hkv], t_h)
        if ctx.seq_has_qkv_bias
          t_k_pre = TinyNNMetal.tnn_add(sess, t_k_raw, self.t_seq_b_k[hkv])
        else
          t_k_pre = t_k_raw
        end
        # ggml_rope_ext requires a->ne[2] == positions->ne[0]. Our K is
        # ne=[d_head, T*B] (ne[2]=1); reshape to ne=[d_head, 1, T*B] so
        # ne[2]==T*B, then reshape back after rope. Reshape is metadata-
        # only (no copy) on contiguous tensors. At T=1, B=1 this is a
        # no-op (1 == 1).
        t_k = Toy::LLM::Primitives::RoPE.apply_2d(
                sess, t_k_pre, ctx.t_seq_positions,
                ctx.t_seq_rope_freq_factors, ctx.seq_rope_cfg, ctx.seq_t, ctx.seq_b)
        t_k_per_kv.push(t_k)

        t_v_raw = mp_matmul(sess, ctx.seq_weight_dtype, self.t_seq_w_v[hkv], t_h)
        if ctx.seq_has_qkv_bias
          t_v = TinyNNMetal.tnn_add(sess, t_v_raw, self.t_seq_b_v[hkv])
        else
          t_v = t_v_raw
        end
        # head_out = v_t @ attn. v has ne=[d_head, T]; transpose to
        # ne=[T, d_head] so the second matmul's contraction lines up.
        t_v_t = TinyNNMetal.tnn_transpose(sess, t_v)
        t_vt_per_kv.push(t_v_t)
        hkv = hkv + 1
      end

      # Per-Q-head attention. GQA: each Q head reads from kv_h = q_h / group_size.
      t_head_out0 = build_qhead(sess, ctx, t_h, 0, t_k_per_kv, t_vt_per_kv)
      t_head_outs = [t_head_out0]
      hq = 1
      while hq < ctx.seq_n_heads
        t_head_outs.push(build_qhead(sess, ctx, t_h, hq, t_k_per_kv, t_vt_per_kv))
        hq = hq + 1
      end

      t_concat = t_head_outs[0]
      hq2 = 1
      while hq2 < ctx.seq_n_heads
        t_concat = TinyNNMetal.tnn_concat(sess, t_concat, t_head_outs[hq2], 0)
        hq2 = hq2 + 1
      end

      t_out_proj = mp_matmul(sess, ctx.seq_weight_dtype, self.t_seq_w_o, t_concat)
      t_x_attn   = TinyNNMetal.tnn_add(sess, t_x, t_out_proj)

      # SwiGLU FFN.
      t_h2    = Toy::LLM::Primitives::RMSNorm.build(sess, t_x_attn, self.t_seq_rn2_gamma, ctx.seq_eps)
      t_gate  = mp_matmul(sess, ctx.seq_weight_dtype, self.t_seq_w_gate, t_h2)
      t_up    = mp_matmul(sess, ctx.seq_weight_dtype, self.t_seq_w_up,   t_h2)
      t_gated = Toy::LLM::Primitives::SwiGLU.gate(sess, t_gate, t_up)
      t_dn    = mp_matmul(sess, ctx.seq_weight_dtype, self.t_seq_w_down, t_gated)
      # GH#15 — tap the FFN output (pre-residual). set_output to pin.
      self.tap_ffn_out = t_dn
      TinyNNMetal.tnn_set_output(t_dn)

      t_resid = TinyNNMetal.tnn_add(sess, t_x_attn, t_dn)
      # GH#15 — tap the residual-stream value AFTER this block. Stable,
      # matched-across-runs region name: resid_post_block.
      self.tap_resid_post = t_resid
      TinyNNMetal.tnn_set_output(t_resid)
      t_resid
    end

    private

    def build_qhead(sess, ctx, t_h, hq, t_k_per_kv, t_vt_per_kv)
      hkv = hq / ctx.seq_group_size
      t_q_raw = mp_matmul(sess, ctx.seq_weight_dtype, self.t_seq_w_q[hq], t_h)
      # M3 step 3 — LoRA splice on Q (same as decode_step). With B
      # zero-initialized this is a no-op at step 0. LoRA matmuls use
      # TinyNNMetal.tnn_matmul DIRECTLY (F32, no cast) — NOT mp_matmul.
      if ctx.seq_lora_q_enabled
        t_lora_a   = TinyNNMetal.tnn_matmul(sess, self.t_seq_w_lora_a_q[hq], t_h)
        t_lora_b_a = TinyNNMetal.tnn_matmul(sess, self.t_seq_w_lora_b_q[hq], t_lora_a)
        t_q_raw    = TinyNNMetal.tnn_add(sess, t_q_raw, t_lora_b_a)
      end
      if ctx.seq_has_qkv_bias
        t_q_pre = TinyNNMetal.tnn_add(sess, t_q_raw, self.t_seq_b_q[hq])
      else
        t_q_pre = t_q_raw
      end
      # Same rope-shape lift as the K path; see comment in build_forward.
      t_q = Toy::LLM::Primitives::RoPE.apply_2d(
              sess, t_q_pre, ctx.t_seq_positions,
              ctx.t_seq_rope_freq_factors, ctx.seq_rope_cfg, ctx.seq_t, ctx.seq_b)

      # Attention math (scores -> scaled+masked softmax -> weighted V).
      # GQA KV-head selection (hkv) stays on the block; the primitive
      # gets the already-selected K/Vt handles. At B=1 the mask handle
      # (ctx.t_seq_attn_mask) is NULL and is never read by the B=1 branch.
      # head ne=[d_head, T*B].
      Toy::LLM::Primitives::GQA.attention(
        sess, t_k_per_kv[hkv], t_q, t_vt_per_kv[hkv],
        ctx.t_seq_attn_mask, ctx.seq_scale, ctx.seq_b)
    end

    # GH#9 — mixed-precision matmul helper. When weight_dtype != 0,
    # casts the F32 master weight to the chosen dtype before the matmul
    # so the math hits the lower-precision tensor-core path. At
    # weight_dtype == 0 this is `tnn_matmul` verbatim — bit-identical to
    # pre-GH#9 graphs. Takes sess + weight_dtype as args (no ivar reads).
    def mp_matmul(sess, weight_dtype, w, x)
      if weight_dtype != 0
        wc = TinyNNMetal.tnn_cast(sess, w, weight_dtype)
        return TinyNNMetal.tnn_matmul(sess, wc, x)
      end
      TinyNNMetal.tnn_matmul(sess, w, x)
    end
  end
end; end; end
