# lib/llama_seq_forward_ffi_metal.rb — Metal mirror of lib/llama_seq_forward_ffi.rb.
#
# AUTO-GENERATED by prep/gen_cuda_mirror.rb. Do not edit by hand;
# edit the CPU source and re-run the generator. The CPU file's
# header explains the architecture; this mirror keeps the same
# contract on the GPU backend via TinyNNMetal.
# llama-family architecture (RMSNorm + SwiGLU + RoPE + GQA).
#
# Sibling of lib/toy_smollm2_ffi_kv.rb (KV-cache decode for single
# positions). This class builds ONE forward graph that processes T
# token positions in a single compute — the prerequisite for real SFT
# (F1.2 step 6c/6d) where masked CE across all T positions is the loss.
#
# Step 1 (this file): forward only, no LoRA, no training. Parity gate
# is T=1 vs SmolLM2KVFFICache#decode_step at pos=0; full-T parity smoke
# (T>1) follows in step 2.
#
# Spinel hygiene — see docs/design/m3-seq-forward-2026-05-21.md, risk #6:
# the M1 full-forward integration was blocked by ivar-type unification
# across cache classes (t_seq / d_model / d_ff fields colliding). To
# sidestep it cleanly, every dimension/parameter ivar here uses a
# `@seq_*` prefix. Verbose but type-isolated.

require_relative "transformer"
require_relative "toy"
require_relative "toy_smollm2"
require_relative "tinynn_metal"

# Per-block tensor handles. Distinct from SmolLM2KVBlockFFI so Spinel
# treats them as independent classes (no shared layout pressure).
class LlamaSeqBlockFFIMetal
  attr_accessor :t_seq_rn1_gamma, :t_seq_rn2_gamma,
                :t_seq_w_q,  :t_seq_w_k,  :t_seq_w_v,  :t_seq_w_o,
                :t_seq_b_q,  :t_seq_b_k,  :t_seq_b_v,
                :t_seq_w_gate, :t_seq_w_up, :t_seq_w_down,
                # M3 step 3: LoRA-Q adapter pair + persistent Adam moments.
                # Same shapes as SmolLM2KVBlockFFI's lora ivars; we keep
                # them on the seq-block so a future training driver can
                # share weights with the KV-decode path (both classes
                # allocate against the same gguf mmap).
                :t_seq_w_lora_a_q, :t_seq_w_lora_b_q,
                :t_seq_w_lora_a_q_m, :t_seq_w_lora_a_q_v,
                :t_seq_w_lora_b_q_m, :t_seq_w_lora_b_q_v,
                # F3 full fine-tune (CPU + CUDA via gen_cuda_mirror).
                # Parallel arrays of (weight, m, v) triples — one entry
                # per trainable weight tensor in this block. Populated
                # only on the realize_for_full_finetune path; left empty
                # in the mmap / LoRA-only paths.
                :ft_weights, :ft_m, :ft_v,
                # GH#15 — per-block activation tap targets for CKA.
                # set_output-pinned intermediates so the host can download
                # them after compute. Region names match the issue text.
                :tap_attn_norm, :tap_ffn_out, :tap_resid_post

  def initialize
    @t_seq_rn1_gamma = TinyNNMetal.tnn_null_ptr
    @t_seq_rn2_gamma = TinyNNMetal.tnn_null_ptr
    @t_seq_w_q = [TinyNNMetal.tnn_null_ptr]
    @t_seq_w_k = [TinyNNMetal.tnn_null_ptr]
    @t_seq_w_v = [TinyNNMetal.tnn_null_ptr]
    @t_seq_b_q = [TinyNNMetal.tnn_null_ptr]
    @t_seq_b_k = [TinyNNMetal.tnn_null_ptr]
    @t_seq_b_v = [TinyNNMetal.tnn_null_ptr]
    @t_seq_w_o    = TinyNNMetal.tnn_null_ptr
    @t_seq_w_gate = TinyNNMetal.tnn_null_ptr
    @t_seq_w_up   = TinyNNMetal.tnn_null_ptr
    @t_seq_w_down = TinyNNMetal.tnn_null_ptr
    @t_seq_w_lora_a_q   = [TinyNNMetal.tnn_null_ptr]
    @t_seq_w_lora_b_q   = [TinyNNMetal.tnn_null_ptr]
    @t_seq_w_lora_a_q_m = [TinyNNMetal.tnn_null_ptr]
    @t_seq_w_lora_a_q_v = [TinyNNMetal.tnn_null_ptr]
    @t_seq_w_lora_b_q_m = [TinyNNMetal.tnn_null_ptr]
    @t_seq_w_lora_b_q_v = [TinyNNMetal.tnn_null_ptr]
    @ft_weights = [TinyNNMetal.tnn_null_ptr]; @ft_weights.pop
    @ft_m       = [TinyNNMetal.tnn_null_ptr]; @ft_m.pop
    @ft_v       = [TinyNNMetal.tnn_null_ptr]; @ft_v.pop
    @tap_attn_norm  = TinyNNMetal.tnn_null_ptr
    @tap_ffn_out    = TinyNNMetal.tnn_null_ptr
    @tap_resid_post = TinyNNMetal.tnn_null_ptr
  end
end

class LlamaSeqForwardFFICacheMetal
  attr_accessor :sess,
                :t_seq_token_embed, :t_seq_final_norm_gamma, :t_seq_output,
                :seq_has_untied_output, :seq_has_qkv_bias,
                :seq_blocks_ffi,
                :seq_t, :seq_b, :seq_d_model, :seq_d_ff, :seq_n_heads, :seq_n_kv,
                :seq_d_head, :seq_group_size, :seq_n_layers, :seq_vocab_size,
                :seq_rope_base, :seq_rope_scaling, :t_seq_rope_freq_factors,
                :seq_rms_eps, :seq_realized, :seq_weight_dtype,
                :t_seq_token_ids, :t_seq_positions, :t_seq_attn_mask,
                :t_seq_x_embed, :t_seq_x_final, :t_seq_logits,
                :seq_gguf_handle_keepalive,
                # M3 step 3 LoRA flags. Both must be set BEFORE
                # realize_for_mmap. enable_lora_q!(r) allocates the
                # adapter A/B pair per Q head; enable_lora_q_adamw!
                # additionally allocates persistent Adam m/v alongside
                # them (mirrors F1.2 step 6b).
                :seq_lora_q_enabled, :seq_lora_q_rank,
                :seq_lora_q_adamw_enabled,
                # F3 full fine-tune. When set BEFORE
                # realize_for_full_finetune, every per-block weight
                # tensor is allocated writable F32 in ctx_w with paired
                # Adam m/v and marked set_param; build_training_step
                # then emits opt_step on each.
                :seq_full_finetune_enabled,
                # Per-cache (not per-block) parallel arrays for the
                # global trainable weights — token_embed, final-norm
                # gamma, optional untied output projection. Populated
                # in realize_for_full_finetune; empty otherwise.
                :ft_globals_weights, :ft_globals_m, :ft_globals_v,
                # Opt-in: include the embedding / final-norm /
                # untied-output tensors in full FT. Default off — the
                # embed tensor on Qwen-class models is huge (V=152K ×
                # d=1536 = 233M params F32) and brings the full
                # forward+backward+opt-step memory closer to the GPU
                # limit. Works correctly on CUDA after vendor-patches
                # 0006 chunked the get_rows_back kernel launch
                # (previously hit CUDA's gridDim.y = 65535 cap).
                :ft_train_embeddings_enabled

  def initialize
    @seq_realized   = false
    @seq_t          = 0
    @seq_b          = 1
    # GH#9 — mixed-precision compute. 0 = F32 (current behaviour;
    # bit-identical to pre-GH#9). 1 = F16, 30 = BF16. When != 0,
    # weight matmuls inside build_seq_block / build_seq_qhead route
    # through mp_matmul which casts the F32 master to the chosen
    # dtype inline in the forward graph. F32 master is kept (required
    # by opt_step_adamw); the cast result lives in transient scratch.
    @seq_weight_dtype = 0
    @seq_d_model    = 0
    @seq_d_ff       = 0
    @seq_n_heads    = 0
    @seq_n_kv       = 0
    @seq_d_head     = 0
    @seq_group_size = 0
    @seq_n_layers   = 0
    @seq_vocab_size = 0
    @seq_rope_base            = 10000.0
    @seq_rope_scaling         = Toy::RopeScaling.none
    @t_seq_rope_freq_factors  = TinyNNMetal.tnn_null_ptr
    @seq_rms_eps    = 1.0e-5
    @sess                  = TinyNNMetal.tnn_null_ptr
    @t_seq_token_embed     = TinyNNMetal.tnn_null_ptr
    @t_seq_final_norm_gamma = TinyNNMetal.tnn_null_ptr
    @t_seq_output          = TinyNNMetal.tnn_null_ptr
    @seq_has_untied_output = false
    @seq_has_qkv_bias      = false
    @seq_blocks_ffi        = [LlamaSeqBlockFFIMetal.new]
    @seq_gguf_handle_keepalive = TinyNNMetal.tnn_null_ptr
    @t_seq_token_ids = TinyNNMetal.tnn_null_ptr
    @t_seq_positions = TinyNNMetal.tnn_null_ptr
    # GH#7 — batched-training block-causal attention mask. Allocated
    # only when @seq_b > 1 (realize_for_random_init with t_batch > 1);
    # otherwise stays NULL and build_seq_qhead falls back to the
    # diag_mask_inf + softmax path (bit-identical to today at B=1).
    @t_seq_attn_mask = TinyNNMetal.tnn_null_ptr
    @t_seq_x_embed   = TinyNNMetal.tnn_null_ptr
    @t_seq_x_final   = TinyNNMetal.tnn_null_ptr
    @t_seq_logits    = TinyNNMetal.tnn_null_ptr
    @seq_lora_q_enabled       = false
    @seq_lora_q_rank          = 0
    @seq_lora_q_adamw_enabled = false
    @seq_full_finetune_enabled = false
    @ft_globals_weights = [TinyNNMetal.tnn_null_ptr]; @ft_globals_weights.pop
    @ft_globals_m       = [TinyNNMetal.tnn_null_ptr]; @ft_globals_m.pop
    @ft_globals_v       = [TinyNNMetal.tnn_null_ptr]; @ft_globals_v.pop
    @ft_train_embeddings_enabled = false
    # E2.3 (towards GH#14) — projection-lens path. donor_d_in is read
    # from cfg in realize_for_random_init; @t_seq_w_proj is the
    # trainable [donor_d_in, d_model] linear inserted after the embed
    # get_rows when donor_d_in > 0.
    @seq_donor_d_in   = 0
    @t_seq_w_proj     = TinyNNMetal.tnn_null_ptr
  end

  # F3 — additionally train the embedding / final-norm gamma / untied
  # output. Opt-in: the embed tensor on Qwen-class vocab is large and
  # makes the memory budget noticeably tighter, but the math itself
  # works correctly post vendor-patches/0006 (chunked get_rows_back).
  def enable_full_finetune_embeddings!
    @ft_train_embeddings_enabled = true
  end

  # F3 — turn on full fine-tune. Every per-block weight tensor will
  # be allocated as writable F32 in ctx_w (instead of mmap'd from the
  # GGUF), paired with persistent Adam m/v, and marked trainable.
  # Mutually exclusive with enable_lora_q!. Call BEFORE
  # realize_for_full_finetune.
  def enable_full_finetune!
    @seq_full_finetune_enabled = true
  end

  # M3 step 3 — turn on LoRA on the Q projection. Adapter A is (r, d_model),
  # B is (d_head, r). Standard init: A small Gaussian, B zero → adapter is
  # a no-op at step 0. Call BEFORE realize_for_mmap. Mirrors
  # SmolLM2KVFFICache#enable_lora_q!.
  def enable_lora_q!(r)
    @seq_lora_q_enabled = true
    @seq_lora_q_rank    = r
  end

  # M3 step 3 — allocate persistent AdamW moments next to each LoRA pair
  # (parallel to F1.2 step 6b on SmolLM2KVFFICache). Required to keep
  # optimizer state alive across reset_for_rebuild / multi-step training.
  def enable_lora_q_adamw!
    @seq_lora_q_adamw_enabled = true
  end

  # F4 alternative realize for CUDA + Q8 base. Allocates every weight
  # tensor in the standard ggml ctx_w (NOT the BYO mmap region), then
  # verbatim-copies the GGUF bytes in. Buys correctness on CUDA at the
  # cost of holding the weights twice transiently (mmap + ctx_w during
  # load; ctx_w only after). Required because the BYO-pointer cuda
  # buffer's quantized padding zeroing (cudaMemset past tensor data)
  # would otherwise crash on Q8 tensors with `ne0 % 512 != 0`.
  #
  # Use this realize when (a) the GGUF is Q8 AND (b) the backend is
  # CUDA. CPU + Q8 stays on realize_for_mmap (no padding issue).
  def realize_for_q8_copy(gguf_handle, cfg, t_seq, untied, qkv_bias)
    @seq_t          = t_seq
    @seq_d_model    = cfg.d_model
    @seq_d_ff       = cfg.d_ff
    @seq_n_heads    = cfg.n_heads
    @seq_n_kv       = cfg.n_kv
    @seq_d_head     = cfg.head_dim
    @seq_group_size = cfg.n_heads / cfg.n_kv
    @seq_n_layers   = cfg.n_layers
    @seq_vocab_size = cfg.vocab
    @seq_rope_base    = cfg.rope_base
    @seq_rope_scaling = cfg.rope_scaling
    @seq_rms_eps    = cfg.rms_eps

    @seq_gguf_handle_keepalive = gguf_handle
    @sess                  = TinyNNMetal.tnn_session_new(2)

    # llama3 / LongRoPE: allocate the freq_factors tensor in ctx_w
    # before finalize_weights. Values uploaded post-finalize.
    if @seq_rope_scaling.kind == :llama3
      @t_seq_rope_freq_factors = TinyNNMetal.tnn_rope_freq_factors_alloc(@sess, cfg.head_dim)
    else
      @t_seq_rope_freq_factors = TinyNNMetal.tnn_null_ptr
    end
    @seq_has_untied_output = untied
    @seq_has_qkv_bias      = qkv_bias

    # Read source tensor types so we can allocate ctx_w tensors of the
    # MATCHING type (verbatim copy requires source/target types match).
    eidx = TinyNNMetal.tnn_gguf_find_index(gguf_handle, "token_embd.weight")
    etyp = TinyNNMetal.tnn_gguf_tensor_type(gguf_handle, eidx)
    @t_seq_token_embed = TinyNNMetal.tnn_input_2d_persistent_typed(@sess,
                           @seq_vocab_size, @seq_d_model, etyp)
    @t_seq_final_norm_gamma = TinyNNMetal.tnn_input_1d_f32_persistent(@sess, @seq_d_model)
    if untied
      oidx = TinyNNMetal.tnn_gguf_find_index(gguf_handle, "output.weight")
      otyp = TinyNNMetal.tnn_gguf_tensor_type(gguf_handle, oidx)
      @t_seq_output = TinyNNMetal.tnn_input_2d_persistent_typed(@sess,
                        @seq_vocab_size, @seq_d_model, otyp)
    end

    @seq_blocks_ffi = [LlamaSeqBlockFFIMetal.new]
    li_init = 1
    while li_init < @seq_n_layers
      @seq_blocks_ffi.push(LlamaSeqBlockFFIMetal.new)
      li_init = li_init + 1
    end

    li = 0
    while li < @seq_n_layers
      blk    = @seq_blocks_ffi[li]
      prefix = "blk." + li.to_s

      blk.t_seq_rn1_gamma = TinyNNMetal.tnn_input_1d_f32_persistent(@sess, @seq_d_model)
      blk.t_seq_rn2_gamma = TinyNNMetal.tnn_input_1d_f32_persistent(@sess, @seq_d_model)

      q_idx  = TinyNNMetal.tnn_gguf_find_index(gguf_handle, prefix + ".attn_q.weight")
      q_type = TinyNNMetal.tnn_gguf_tensor_type(gguf_handle, q_idx)
      blk.t_seq_w_q = [TinyNNMetal.tnn_input_2d_persistent_typed(@sess, @seq_d_head, @seq_d_model, q_type)]
      hq = 1
      while hq < @seq_n_heads
        blk.t_seq_w_q.push(TinyNNMetal.tnn_input_2d_persistent_typed(@sess, @seq_d_head, @seq_d_model, q_type))
        hq = hq + 1
      end

      k_idx = TinyNNMetal.tnn_gguf_find_index(gguf_handle, prefix + ".attn_k.weight")
      v_idx = TinyNNMetal.tnn_gguf_find_index(gguf_handle, prefix + ".attn_v.weight")
      k_type = TinyNNMetal.tnn_gguf_tensor_type(gguf_handle, k_idx)
      v_type = TinyNNMetal.tnn_gguf_tensor_type(gguf_handle, v_idx)
      blk.t_seq_w_k = [TinyNNMetal.tnn_input_2d_persistent_typed(@sess, @seq_d_head, @seq_d_model, k_type)]
      blk.t_seq_w_v = [TinyNNMetal.tnn_input_2d_persistent_typed(@sess, @seq_d_head, @seq_d_model, v_type)]
      hkv = 1
      while hkv < @seq_n_kv
        blk.t_seq_w_k.push(TinyNNMetal.tnn_input_2d_persistent_typed(@sess, @seq_d_head, @seq_d_model, k_type))
        blk.t_seq_w_v.push(TinyNNMetal.tnn_input_2d_persistent_typed(@sess, @seq_d_head, @seq_d_model, v_type))
        hkv = hkv + 1
      end

      if qkv_bias
        blk.t_seq_b_q = [TinyNNMetal.tnn_input_1d_f32_persistent(@sess, @seq_d_head)]
        hbq = 1
        while hbq < @seq_n_heads
          blk.t_seq_b_q.push(TinyNNMetal.tnn_input_1d_f32_persistent(@sess, @seq_d_head))
          hbq = hbq + 1
        end
        blk.t_seq_b_k = [TinyNNMetal.tnn_input_1d_f32_persistent(@sess, @seq_d_head)]
        blk.t_seq_b_v = [TinyNNMetal.tnn_input_1d_f32_persistent(@sess, @seq_d_head)]
        hbkv = 1
        while hbkv < @seq_n_kv
          blk.t_seq_b_k.push(TinyNNMetal.tnn_input_1d_f32_persistent(@sess, @seq_d_head))
          blk.t_seq_b_v.push(TinyNNMetal.tnn_input_1d_f32_persistent(@sess, @seq_d_head))
          hbkv = hbkv + 1
        end
      end

      o_idx    = TinyNNMetal.tnn_gguf_find_index(gguf_handle, prefix + ".attn_output.weight")
      gate_idx = TinyNNMetal.tnn_gguf_find_index(gguf_handle, prefix + ".ffn_gate.weight")
      up_idx   = TinyNNMetal.tnn_gguf_find_index(gguf_handle, prefix + ".ffn_up.weight")
      down_idx = TinyNNMetal.tnn_gguf_find_index(gguf_handle, prefix + ".ffn_down.weight")
      blk.t_seq_w_o    = TinyNNMetal.tnn_input_2d_persistent_typed(@sess, @seq_d_model, @seq_d_model,
                           TinyNNMetal.tnn_gguf_tensor_type(gguf_handle, o_idx))
      blk.t_seq_w_gate = TinyNNMetal.tnn_input_2d_persistent_typed(@sess, @seq_d_ff, @seq_d_model,
                           TinyNNMetal.tnn_gguf_tensor_type(gguf_handle, gate_idx))
      blk.t_seq_w_up   = TinyNNMetal.tnn_input_2d_persistent_typed(@sess, @seq_d_ff, @seq_d_model,
                           TinyNNMetal.tnn_gguf_tensor_type(gguf_handle, up_idx))
      blk.t_seq_w_down = TinyNNMetal.tnn_input_2d_persistent_typed(@sess, @seq_d_model, @seq_d_ff,
                           TinyNNMetal.tnn_gguf_tensor_type(gguf_handle, down_idx))

      # LoRA + Adam allocations (same as realize_for_mmap path).
      if @seq_lora_q_enabled
        blk.t_seq_w_lora_a_q = [TinyNNMetal.tnn_input_2d_f32_persistent(@sess,
                                  @seq_lora_q_rank, @seq_d_model)]
        blk.t_seq_w_lora_b_q = [TinyNNMetal.tnn_input_2d_f32_persistent(@sess,
                                  @seq_d_head, @seq_lora_q_rank)]
        hql = 1
        while hql < @seq_n_heads
          blk.t_seq_w_lora_a_q.push(TinyNNMetal.tnn_input_2d_f32_persistent(@sess,
                                      @seq_lora_q_rank, @seq_d_model))
          blk.t_seq_w_lora_b_q.push(TinyNNMetal.tnn_input_2d_f32_persistent(@sess,
                                      @seq_d_head, @seq_lora_q_rank))
          hql = hql + 1
        end
        if @seq_lora_q_adamw_enabled
          blk.t_seq_w_lora_a_q_m = [TinyNNMetal.tnn_input_2d_f32_persistent(@sess,
                                      @seq_lora_q_rank, @seq_d_model)]
          blk.t_seq_w_lora_a_q_v = [TinyNNMetal.tnn_input_2d_f32_persistent(@sess,
                                      @seq_lora_q_rank, @seq_d_model)]
          blk.t_seq_w_lora_b_q_m = [TinyNNMetal.tnn_input_2d_f32_persistent(@sess,
                                      @seq_d_head, @seq_lora_q_rank)]
          blk.t_seq_w_lora_b_q_v = [TinyNNMetal.tnn_input_2d_f32_persistent(@sess,
                                      @seq_d_head, @seq_lora_q_rank)]
          hqm = 1
          while hqm < @seq_n_heads
            blk.t_seq_w_lora_a_q_m.push(TinyNNMetal.tnn_input_2d_f32_persistent(@sess,
                                          @seq_lora_q_rank, @seq_d_model))
            blk.t_seq_w_lora_a_q_v.push(TinyNNMetal.tnn_input_2d_f32_persistent(@sess,
                                          @seq_lora_q_rank, @seq_d_model))
            blk.t_seq_w_lora_b_q_m.push(TinyNNMetal.tnn_input_2d_f32_persistent(@sess,
                                          @seq_d_head, @seq_lora_q_rank))
            blk.t_seq_w_lora_b_q_v.push(TinyNNMetal.tnn_input_2d_f32_persistent(@sess,
                                          @seq_d_head, @seq_lora_q_rank))
            hqm = hqm + 1
          end
        end
      end

      li = li + 1
    end

    if @seq_lora_q_enabled
      li2 = 0
      while li2 < @seq_n_layers
        blk2 = @seq_blocks_ffi[li2]
        hq_p = 0
        while hq_p < @seq_n_heads
          TinyNNMetal.tnn_set_param(blk2.t_seq_w_lora_a_q[hq_p])
          TinyNNMetal.tnn_set_param(blk2.t_seq_w_lora_b_q[hq_p])
          hq_p = hq_p + 1
        end
        li2 = li2 + 1
      end
    end

    # GH#7 — block-causal attention mask for B>1 (see realize_for_mmap
    # for the same pattern). Caller sets cache.seq_b = N before realize.
    if @seq_b > 1
      tb_alloc = @seq_t * @seq_b
      @t_seq_attn_mask = TinyNNMetal.tnn_input_2d_f32_persistent(@sess, tb_alloc, tb_alloc)
    end

    TinyNNMetal.tnn_finalize_weights(@sess)

    # Upload llama3-style RoPE freq_factors once the backend buffer
    # exists. Per-model constant; never re-uploaded.
    if @seq_rope_scaling.kind == :llama3
      ff = Toy::RopeScaling.compute_llama3_freq_factors(
        @seq_d_head, @seq_rope_base,
        @seq_rope_scaling.orig_max_pos, @seq_rope_scaling.factor,
        @seq_rope_scaling.low_freq_factor, @seq_rope_scaling.high_freq_factor)
      TinyNNMetal.tnn_upload_from_float_array(@sess, @t_seq_rope_freq_factors, ff, ff.length)
    end

    if @seq_b > 1
      upload_block_causal_mask!
    end

    # Load all weight bytes from the GGUF into the now-allocated
    # backend buffers. Verbatim copy keeps Q8 as Q8.
    TinyNNMetal.tnn_gguf_copy_verbatim_to_persistent(gguf_handle, eidx, @sess, @t_seq_token_embed)
    fnidx = TinyNNMetal.tnn_gguf_find_index(gguf_handle, "output_norm.weight")
    TinyNNMetal.tnn_gguf_copy_1d_to_persistent(gguf_handle, fnidx, @sess, @t_seq_final_norm_gamma)
    if untied
      oidx2 = TinyNNMetal.tnn_gguf_find_index(gguf_handle, "output.weight")
      TinyNNMetal.tnn_gguf_copy_verbatim_to_persistent(gguf_handle, oidx2, @sess, @t_seq_output)
    end

    li_l = 0
    while li_l < @seq_n_layers
      blk    = @seq_blocks_ffi[li_l]
      prefix = "blk." + li_l.to_s
      rn1_idx = TinyNNMetal.tnn_gguf_find_index(gguf_handle, prefix + ".attn_norm.weight")
      rn2_idx = TinyNNMetal.tnn_gguf_find_index(gguf_handle, prefix + ".ffn_norm.weight")
      TinyNNMetal.tnn_gguf_copy_1d_to_persistent(gguf_handle, rn1_idx, @sess, blk.t_seq_rn1_gamma)
      TinyNNMetal.tnn_gguf_copy_1d_to_persistent(gguf_handle, rn2_idx, @sess, blk.t_seq_rn2_gamma)

      q_idx = TinyNNMetal.tnn_gguf_find_index(gguf_handle, prefix + ".attn_q.weight")
      hq = 0
      while hq < @seq_n_heads
        TinyNNMetal.tnn_gguf_copy_verbatim_head_slice_to_persistent(gguf_handle, q_idx, @sess,
          blk.t_seq_w_q[hq], hq, @seq_n_heads)
        hq = hq + 1
      end
      k_idx = TinyNNMetal.tnn_gguf_find_index(gguf_handle, prefix + ".attn_k.weight")
      v_idx = TinyNNMetal.tnn_gguf_find_index(gguf_handle, prefix + ".attn_v.weight")
      hkv = 0
      while hkv < @seq_n_kv
        TinyNNMetal.tnn_gguf_copy_verbatim_head_slice_to_persistent(gguf_handle, k_idx, @sess,
          blk.t_seq_w_k[hkv], hkv, @seq_n_kv)
        TinyNNMetal.tnn_gguf_copy_verbatim_head_slice_to_persistent(gguf_handle, v_idx, @sess,
          blk.t_seq_w_v[hkv], hkv, @seq_n_kv)
        hkv = hkv + 1
      end

      if qkv_bias
        qb_idx = TinyNNMetal.tnn_gguf_find_index(gguf_handle, prefix + ".attn_q.bias")
        kb_idx = TinyNNMetal.tnn_gguf_find_index(gguf_handle, prefix + ".attn_k.bias")
        vb_idx = TinyNNMetal.tnn_gguf_find_index(gguf_handle, prefix + ".attn_v.bias")
        hbq = 0
        while hbq < @seq_n_heads
          TinyNNMetal.tnn_gguf_copy_head_bias_slice_to_persistent(gguf_handle, qb_idx, @sess,
            blk.t_seq_b_q[hbq], hbq, @seq_d_head)
          hbq = hbq + 1
        end
        hbkv = 0
        while hbkv < @seq_n_kv
          TinyNNMetal.tnn_gguf_copy_head_bias_slice_to_persistent(gguf_handle, kb_idx, @sess,
            blk.t_seq_b_k[hbkv], hbkv, @seq_d_head)
          TinyNNMetal.tnn_gguf_copy_head_bias_slice_to_persistent(gguf_handle, vb_idx, @sess,
            blk.t_seq_b_v[hbkv], hbkv, @seq_d_head)
          hbkv = hbkv + 1
        end
      end

      o_idx    = TinyNNMetal.tnn_gguf_find_index(gguf_handle, prefix + ".attn_output.weight")
      gate_idx = TinyNNMetal.tnn_gguf_find_index(gguf_handle, prefix + ".ffn_gate.weight")
      up_idx   = TinyNNMetal.tnn_gguf_find_index(gguf_handle, prefix + ".ffn_up.weight")
      down_idx = TinyNNMetal.tnn_gguf_find_index(gguf_handle, prefix + ".ffn_down.weight")
      TinyNNMetal.tnn_gguf_copy_verbatim_to_persistent(gguf_handle, o_idx,    @sess, blk.t_seq_w_o)
      TinyNNMetal.tnn_gguf_copy_verbatim_to_persistent(gguf_handle, gate_idx, @sess, blk.t_seq_w_gate)
      TinyNNMetal.tnn_gguf_copy_verbatim_to_persistent(gguf_handle, up_idx,   @sess, blk.t_seq_w_up)
      TinyNNMetal.tnn_gguf_copy_verbatim_to_persistent(gguf_handle, down_idx, @sess, blk.t_seq_w_down)

      li_l = li_l + 1
    end

    if @seq_lora_q_adamw_enabled
      za = Mat.new(@seq_lora_q_rank, @seq_d_model)
      zb = Mat.new(@seq_d_head,      @seq_lora_q_rank)
      i = 0
      while i < @seq_lora_q_rank * @seq_d_model; za.flat[i] = 0.0; i = i + 1; end
      j = 0
      while j < @seq_d_head * @seq_lora_q_rank; zb.flat[j] = 0.0; j = j + 1; end
      li_z = 0
      while li_z < @seq_n_layers
        blk_z = @seq_blocks_ffi[li_z]
        hqz = 0
        while hqz < @seq_n_heads
          TinyNNMetal.upload_row_major(@sess, blk_z.t_seq_w_lora_a_q_m[hqz], za)
          TinyNNMetal.upload_row_major(@sess, blk_z.t_seq_w_lora_a_q_v[hqz], za)
          TinyNNMetal.upload_row_major(@sess, blk_z.t_seq_w_lora_b_q_m[hqz], zb)
          TinyNNMetal.upload_row_major(@sess, blk_z.t_seq_w_lora_b_q_v[hqz], zb)
          hqz = hqz + 1
        end
        li_z = li_z + 1
      end
    end

    build_forward_in_current_ctx
    TinyNNMetal.tnn_realize(@sess, @t_seq_logits)
    @seq_realized = true
  end

  # Allocate persistent weights mmap'd from `gguf_handle` (caller is
  # responsible for keeping the handle alive — we keepalive it via
  # @seq_gguf_handle_keepalive), compute inputs, and the full forward
  # graph for T = `t_seq` positions. Fixed T; rebuild for a different T.
  #
  # Weight layout matches SmolLM2KVFFICache#realize_for_mmap exactly
  # (same byte offsets + per-head split), so a sharded GGUF can be
  # loaded by either class.
  def realize_for_mmap(gguf_handle, cfg, t_seq, untied, qkv_bias)
    @seq_t          = t_seq
    @seq_d_model    = cfg.d_model
    @seq_d_ff       = cfg.d_ff
    @seq_n_heads    = cfg.n_heads
    @seq_n_kv       = cfg.n_kv
    @seq_d_head     = cfg.head_dim
    @seq_group_size = cfg.n_heads / cfg.n_kv
    @seq_n_layers   = cfg.n_layers
    @seq_vocab_size = cfg.vocab
    @seq_rope_base    = cfg.rope_base
    @seq_rope_scaling = cfg.rope_scaling
    @seq_rms_eps    = cfg.rms_eps

    @seq_gguf_handle_keepalive = gguf_handle
    @sess                  = TinyNNMetal.tnn_session_new(2)

    # llama3 / LongRoPE: allocate the freq_factors tensor in ctx_w
    # before finalize_weights. Values uploaded post-finalize.
    if @seq_rope_scaling.kind == :llama3
      @t_seq_rope_freq_factors = TinyNNMetal.tnn_rope_freq_factors_alloc(@sess, cfg.head_dim)
    else
      @t_seq_rope_freq_factors = TinyNNMetal.tnn_null_ptr
    end
    @seq_has_untied_output = untied
    @seq_has_qkv_bias      = qkv_bias

    map_base = TinyNNMetal.tnn_gguf_mmap_base(gguf_handle)
    map_size = TinyNNMetal.tnn_gguf_mmap_size(gguf_handle)
    TinyNNMetal.tnn_session_attach_weight_mmap(@sess, map_base, map_size)

    # Embeddings + final norm + optional untied LM head.
    eidx = TinyNNMetal.tnn_gguf_find_index(gguf_handle, "token_embd.weight")
    eoff = TinyNNMetal.tnn_gguf_tensor_file_offset(gguf_handle, eidx)
    etyp = TinyNNMetal.tnn_gguf_tensor_type(gguf_handle, eidx)
    @t_seq_token_embed = TinyNNMetal.tnn_input_2d_persistent_mmap(@sess,
                           @seq_vocab_size, @seq_d_model, etyp, eoff)

    fnidx = TinyNNMetal.tnn_gguf_find_index(gguf_handle, "output_norm.weight")
    fnoff = TinyNNMetal.tnn_gguf_tensor_file_offset(gguf_handle, fnidx)
    @t_seq_final_norm_gamma = TinyNNMetal.tnn_input_1d_persistent_mmap(@sess,
                                @seq_d_model, 0, fnoff)

    if untied
      oidx = TinyNNMetal.tnn_gguf_find_index(gguf_handle, "output.weight")
      ooff = TinyNNMetal.tnn_gguf_tensor_file_offset(gguf_handle, oidx)
      otyp = TinyNNMetal.tnn_gguf_tensor_type(gguf_handle, oidx)
      @t_seq_output = TinyNNMetal.tnn_input_2d_persistent_mmap(@sess,
                        @seq_vocab_size, @seq_d_model, otyp, ooff)
    end

    @seq_blocks_ffi = [LlamaSeqBlockFFIMetal.new]
    li_init = 1
    while li_init < @seq_n_layers
      @seq_blocks_ffi.push(LlamaSeqBlockFFIMetal.new)
      li_init = li_init + 1
    end

    li = 0
    while li < @seq_n_layers
      blk = @seq_blocks_ffi[li]
      prefix = "blk." + li.to_s

      rn1_idx = TinyNNMetal.tnn_gguf_find_index(gguf_handle, prefix + ".attn_norm.weight")
      rn2_idx = TinyNNMetal.tnn_gguf_find_index(gguf_handle, prefix + ".ffn_norm.weight")
      blk.t_seq_rn1_gamma = TinyNNMetal.tnn_input_1d_persistent_mmap(@sess,
                              @seq_d_model, 0,
                              TinyNNMetal.tnn_gguf_tensor_file_offset(gguf_handle, rn1_idx))
      blk.t_seq_rn2_gamma = TinyNNMetal.tnn_input_1d_persistent_mmap(@sess,
                              @seq_d_model, 0,
                              TinyNNMetal.tnn_gguf_tensor_file_offset(gguf_handle, rn2_idx))

      # Q heads — per-head [d_head, d_model] tensor, n_heads of them.
      q_idx      = TinyNNMetal.tnn_gguf_find_index(gguf_handle, prefix + ".attn_q.weight")
      q_off_base = TinyNNMetal.tnn_gguf_tensor_file_offset(gguf_handle, q_idx)
      q_type     = TinyNNMetal.tnn_gguf_tensor_type(gguf_handle, q_idx)
      q_stride   = head_nbytes(q_type, @seq_d_head, @seq_d_model)
      blk.t_seq_w_q = [TinyNNMetal.tnn_input_2d_persistent_mmap(@sess,
                         @seq_d_head, @seq_d_model, q_type, q_off_base)]
      hq = 1
      while hq < @seq_n_heads
        blk.t_seq_w_q.push(TinyNNMetal.tnn_input_2d_persistent_mmap(@sess,
                             @seq_d_head, @seq_d_model, q_type,
                             q_off_base + hq * q_stride))
        hq = hq + 1
      end

      # M3 step 3 — LoRA-Q adapter pair per Q head. Trainable F32 in
      # ctx_w (mirrors SmolLM2KVFFICache). Optional persistent Adam m/v.
      # Names ride the llama.cpp convention extended for the per-head /
      # adapter axes: blk.N.attn_q.head_H.lora_{a,b}.weight (+ .m / .v).
      lora_prefix = "blk." + li.to_s + ".attn_q.head_"
      if @seq_lora_q_enabled
        blk.t_seq_w_lora_a_q = [TinyNNMetal.tnn_input_2d_f32_persistent(@sess,
                                  @seq_lora_q_rank, @seq_d_model)]
        blk.t_seq_w_lora_b_q = [TinyNNMetal.tnn_input_2d_f32_persistent(@sess,
                                  @seq_d_head, @seq_lora_q_rank)]
        hql = 1
        while hql < @seq_n_heads
          blk.t_seq_w_lora_a_q.push(TinyNNMetal.tnn_input_2d_f32_persistent(@sess,
                                      @seq_lora_q_rank, @seq_d_model))
          blk.t_seq_w_lora_b_q.push(TinyNNMetal.tnn_input_2d_f32_persistent(@sess,
                                      @seq_d_head, @seq_lora_q_rank))
          hql = hql + 1
        end
        hqn = 0
        while hqn < @seq_n_heads
          TinyNNMetal.tnn_tensor_set_name(blk.t_seq_w_lora_a_q[hqn],
                                     lora_prefix + hqn.to_s + ".lora_a.weight")
          TinyNNMetal.tnn_tensor_set_name(blk.t_seq_w_lora_b_q[hqn],
                                     lora_prefix + hqn.to_s + ".lora_b.weight")
          hqn = hqn + 1
        end

        if @seq_lora_q_adamw_enabled
          blk.t_seq_w_lora_a_q_m = [TinyNNMetal.tnn_input_2d_f32_persistent(@sess,
                                      @seq_lora_q_rank, @seq_d_model)]
          blk.t_seq_w_lora_a_q_v = [TinyNNMetal.tnn_input_2d_f32_persistent(@sess,
                                      @seq_lora_q_rank, @seq_d_model)]
          blk.t_seq_w_lora_b_q_m = [TinyNNMetal.tnn_input_2d_f32_persistent(@sess,
                                      @seq_d_head, @seq_lora_q_rank)]
          blk.t_seq_w_lora_b_q_v = [TinyNNMetal.tnn_input_2d_f32_persistent(@sess,
                                      @seq_d_head, @seq_lora_q_rank)]
          hqm = 1
          while hqm < @seq_n_heads
            blk.t_seq_w_lora_a_q_m.push(TinyNNMetal.tnn_input_2d_f32_persistent(@sess,
                                          @seq_lora_q_rank, @seq_d_model))
            blk.t_seq_w_lora_a_q_v.push(TinyNNMetal.tnn_input_2d_f32_persistent(@sess,
                                          @seq_lora_q_rank, @seq_d_model))
            blk.t_seq_w_lora_b_q_m.push(TinyNNMetal.tnn_input_2d_f32_persistent(@sess,
                                          @seq_d_head, @seq_lora_q_rank))
            blk.t_seq_w_lora_b_q_v.push(TinyNNMetal.tnn_input_2d_f32_persistent(@sess,
                                          @seq_d_head, @seq_lora_q_rank))
            hqm = hqm + 1
          end
          hmn = 0
          while hmn < @seq_n_heads
            TinyNNMetal.tnn_tensor_set_name(blk.t_seq_w_lora_a_q_m[hmn],
                                       lora_prefix + hmn.to_s + ".lora_a.m")
            TinyNNMetal.tnn_tensor_set_name(blk.t_seq_w_lora_a_q_v[hmn],
                                       lora_prefix + hmn.to_s + ".lora_a.v")
            TinyNNMetal.tnn_tensor_set_name(blk.t_seq_w_lora_b_q_m[hmn],
                                       lora_prefix + hmn.to_s + ".lora_b.m")
            TinyNNMetal.tnn_tensor_set_name(blk.t_seq_w_lora_b_q_v[hmn],
                                       lora_prefix + hmn.to_s + ".lora_b.v")
            hmn = hmn + 1
          end
        end
      end

      # K, V heads — per-KV-head [d_head, d_model].
      k_idx      = TinyNNMetal.tnn_gguf_find_index(gguf_handle, prefix + ".attn_k.weight")
      v_idx      = TinyNNMetal.tnn_gguf_find_index(gguf_handle, prefix + ".attn_v.weight")
      k_off_base = TinyNNMetal.tnn_gguf_tensor_file_offset(gguf_handle, k_idx)
      v_off_base = TinyNNMetal.tnn_gguf_tensor_file_offset(gguf_handle, v_idx)
      k_type     = TinyNNMetal.tnn_gguf_tensor_type(gguf_handle, k_idx)
      v_type     = TinyNNMetal.tnn_gguf_tensor_type(gguf_handle, v_idx)
      k_stride   = head_nbytes(k_type, @seq_d_head, @seq_d_model)
      v_stride   = head_nbytes(v_type, @seq_d_head, @seq_d_model)
      blk.t_seq_w_k = [TinyNNMetal.tnn_input_2d_persistent_mmap(@sess,
                         @seq_d_head, @seq_d_model, k_type, k_off_base)]
      blk.t_seq_w_v = [TinyNNMetal.tnn_input_2d_persistent_mmap(@sess,
                         @seq_d_head, @seq_d_model, v_type, v_off_base)]
      hkv = 1
      while hkv < @seq_n_kv
        blk.t_seq_w_k.push(TinyNNMetal.tnn_input_2d_persistent_mmap(@sess,
                             @seq_d_head, @seq_d_model, k_type,
                             k_off_base + hkv * k_stride))
        blk.t_seq_w_v.push(TinyNNMetal.tnn_input_2d_persistent_mmap(@sess,
                             @seq_d_head, @seq_d_model, v_type,
                             v_off_base + hkv * v_stride))
        hkv = hkv + 1
      end

      # Optional Q/K/V biases (Qwen2.x). 1D [d_head] per head, contiguous.
      if qkv_bias
        qb_idx = TinyNNMetal.tnn_gguf_find_index(gguf_handle, prefix + ".attn_q.bias")
        kb_idx = TinyNNMetal.tnn_gguf_find_index(gguf_handle, prefix + ".attn_k.bias")
        vb_idx = TinyNNMetal.tnn_gguf_find_index(gguf_handle, prefix + ".attn_v.bias")
        qb_off = TinyNNMetal.tnn_gguf_tensor_file_offset(gguf_handle, qb_idx)
        kb_off = TinyNNMetal.tnn_gguf_tensor_file_offset(gguf_handle, kb_idx)
        vb_off = TinyNNMetal.tnn_gguf_tensor_file_offset(gguf_handle, vb_idx)
        bias_stride = @seq_d_head * 4

        blk.t_seq_b_q = [TinyNNMetal.tnn_input_1d_persistent_mmap(@sess, @seq_d_head, 0, qb_off)]
        hq = 1
        while hq < @seq_n_heads
          blk.t_seq_b_q.push(TinyNNMetal.tnn_input_1d_persistent_mmap(@sess, @seq_d_head, 0,
                               qb_off + hq * bias_stride))
          hq = hq + 1
        end
        blk.t_seq_b_k = [TinyNNMetal.tnn_input_1d_persistent_mmap(@sess, @seq_d_head, 0, kb_off)]
        blk.t_seq_b_v = [TinyNNMetal.tnn_input_1d_persistent_mmap(@sess, @seq_d_head, 0, vb_off)]
        hkv = 1
        while hkv < @seq_n_kv
          blk.t_seq_b_k.push(TinyNNMetal.tnn_input_1d_persistent_mmap(@sess, @seq_d_head, 0,
                               kb_off + hkv * bias_stride))
          blk.t_seq_b_v.push(TinyNNMetal.tnn_input_1d_persistent_mmap(@sess, @seq_d_head, 0,
                               vb_off + hkv * bias_stride))
          hkv = hkv + 1
        end
      end

      # O, FFN — full 2D weights, no per-head split.
      o_idx    = TinyNNMetal.tnn_gguf_find_index(gguf_handle, prefix + ".attn_output.weight")
      gate_idx = TinyNNMetal.tnn_gguf_find_index(gguf_handle, prefix + ".ffn_gate.weight")
      up_idx   = TinyNNMetal.tnn_gguf_find_index(gguf_handle, prefix + ".ffn_up.weight")
      down_idx = TinyNNMetal.tnn_gguf_find_index(gguf_handle, prefix + ".ffn_down.weight")
      blk.t_seq_w_o    = TinyNNMetal.tnn_input_2d_persistent_mmap(@sess, @seq_d_model, @seq_d_model,
                           TinyNNMetal.tnn_gguf_tensor_type(gguf_handle, o_idx),
                           TinyNNMetal.tnn_gguf_tensor_file_offset(gguf_handle, o_idx))
      blk.t_seq_w_gate = TinyNNMetal.tnn_input_2d_persistent_mmap(@sess, @seq_d_ff, @seq_d_model,
                           TinyNNMetal.tnn_gguf_tensor_type(gguf_handle, gate_idx),
                           TinyNNMetal.tnn_gguf_tensor_file_offset(gguf_handle, gate_idx))
      blk.t_seq_w_up   = TinyNNMetal.tnn_input_2d_persistent_mmap(@sess, @seq_d_ff, @seq_d_model,
                           TinyNNMetal.tnn_gguf_tensor_type(gguf_handle, up_idx),
                           TinyNNMetal.tnn_gguf_tensor_file_offset(gguf_handle, up_idx))
      blk.t_seq_w_down = TinyNNMetal.tnn_input_2d_persistent_mmap(@sess, @seq_d_model, @seq_d_ff,
                           TinyNNMetal.tnn_gguf_tensor_type(gguf_handle, down_idx),
                           TinyNNMetal.tnn_gguf_tensor_file_offset(gguf_handle, down_idx))

      li = li + 1
    end

    # Mark LoRA tensors as trainable BEFORE finalize. set_param flips
    # the PARAM flag so build_backward walks them when emitting grad nodes.
    if @seq_lora_q_enabled
      li2 = 0
      while li2 < @seq_n_layers
        blk2 = @seq_blocks_ffi[li2]
        hq_p = 0
        while hq_p < @seq_n_heads
          TinyNNMetal.tnn_set_param(blk2.t_seq_w_lora_a_q[hq_p])
          TinyNNMetal.tnn_set_param(blk2.t_seq_w_lora_b_q[hq_p])
          hq_p = hq_p + 1
        end
        li2 = li2 + 1
      end
    end

    # GH#7 — block-causal attention mask for B>1. Caller opts in by
    # setting `cache.seq_b = N` BEFORE realize_for_mmap. At B=1 the
    # mask stays NULL and build_seq_qhead uses diag_mask_inf + softmax
    # (bit-identical to pre-GH#7).
    if @seq_b > 1
      tb_alloc = @seq_t * @seq_b
      @t_seq_attn_mask = TinyNNMetal.tnn_input_2d_f32_persistent(@sess, tb_alloc, tb_alloc)
    end

    TinyNNMetal.tnn_finalize_weights(@sess)

    if @seq_rope_scaling.kind == :llama3
      ff = Toy::RopeScaling.compute_llama3_freq_factors(
        @seq_d_head, @seq_rope_base,
        @seq_rope_scaling.orig_max_pos, @seq_rope_scaling.factor,
        @seq_rope_scaling.low_freq_factor, @seq_rope_scaling.high_freq_factor)
      TinyNNMetal.tnn_upload_from_float_array(@sess, @t_seq_rope_freq_factors, ff, ff.length)
    end

    if @seq_b > 1
      upload_block_causal_mask!
    end

    # Zero-init persistent AdamW moments. Same contract as F1.2 step 6b
    # on SmolLM2KVFFICache — m and v start at 0 per the AdamW update rule.
    if @seq_lora_q_adamw_enabled
      za = Mat.new(@seq_lora_q_rank, @seq_d_model)
      zb = Mat.new(@seq_d_head,      @seq_lora_q_rank)
      i = 0
      while i < @seq_lora_q_rank * @seq_d_model; za.flat[i] = 0.0; i = i + 1; end
      j = 0
      while j < @seq_d_head * @seq_lora_q_rank; zb.flat[j] = 0.0; j = j + 1; end
      li_z = 0
      while li_z < @seq_n_layers
        blk_z = @seq_blocks_ffi[li_z]
        hqz = 0
        while hqz < @seq_n_heads
          TinyNNMetal.upload_row_major(@sess, blk_z.t_seq_w_lora_a_q_m[hqz], za)
          TinyNNMetal.upload_row_major(@sess, blk_z.t_seq_w_lora_a_q_v[hqz], za)
          TinyNNMetal.upload_row_major(@sess, blk_z.t_seq_w_lora_b_q_m[hqz], zb)
          TinyNNMetal.upload_row_major(@sess, blk_z.t_seq_w_lora_b_q_v[hqz], zb)
          hqz = hqz + 1
        end
        li_z = li_z + 1
      end
    end

    build_forward_in_current_ctx
    TinyNNMetal.tnn_realize(@sess, @t_seq_logits)
    @seq_realized = true
  end

  # F3 — full fine-tune realize path. Parallel to realize_for_mmap
  # but every per-block weight is allocated writable F32 in ctx_w
  # (no mmap), set_param-marked, paired with Adam m/v, and loaded
  # from the GGUF post-finalize via the dequantize-friendly
  # tnn_gguf_copy_* primitives. The embedding tensor + final_norm
  # gamma stay mmap'd (read-only) — the MVP doesn't train them.
  def realize_for_full_finetune(gguf_handle, cfg, t_seq, untied, qkv_bias)
    @seq_t          = t_seq
    @seq_d_model    = cfg.d_model
    @seq_d_ff       = cfg.d_ff
    @seq_n_heads    = cfg.n_heads
    @seq_n_kv       = cfg.n_kv
    @seq_d_head     = cfg.head_dim
    @seq_group_size = cfg.n_heads / cfg.n_kv
    @seq_n_layers   = cfg.n_layers
    @seq_vocab_size = cfg.vocab
    @seq_rope_base    = cfg.rope_base
    @seq_rope_scaling = cfg.rope_scaling
    @seq_rms_eps    = cfg.rms_eps

    @seq_gguf_handle_keepalive = gguf_handle
    @sess                  = TinyNNMetal.tnn_session_new(2)

    # llama3 / LongRoPE: allocate the freq_factors tensor in ctx_w
    # before finalize_weights. Values uploaded post-finalize.
    if @seq_rope_scaling.kind == :llama3
      @t_seq_rope_freq_factors = TinyNNMetal.tnn_rope_freq_factors_alloc(@sess, cfg.head_dim)
    else
      @t_seq_rope_freq_factors = TinyNNMetal.tnn_null_ptr
    end
    @seq_has_untied_output = untied
    @seq_has_qkv_bias      = qkv_bias

    # Token embed + final-norm gamma + (untied) output: trainable
    # only when opt-in (ft_train_embeddings_enabled). Otherwise
    # they stay mmap'd / read-only (still need a mmap attach for
    # this branch).
    if @ft_train_embeddings_enabled
      @t_seq_token_embed = TinyNNMetal.tnn_input_2d_f32_persistent(@sess,
                             @seq_vocab_size, @seq_d_model)
      ft_add_global_2d(@t_seq_token_embed, @seq_vocab_size, @seq_d_model)
      ft_name_last_global("token_embd.weight")

      @t_seq_final_norm_gamma = TinyNNMetal.tnn_input_1d_f32_persistent(@sess, @seq_d_model)
      ft_add_global_1d(@t_seq_final_norm_gamma)
      ft_name_last_global("output_norm.weight")

      if untied
        @t_seq_output = TinyNNMetal.tnn_input_2d_f32_persistent(@sess,
                          @seq_vocab_size, @seq_d_model)
        ft_add_global_2d(@t_seq_output, @seq_vocab_size, @seq_d_model)
        ft_name_last_global("output.weight")
      end
    else
      map_base = TinyNNMetal.tnn_gguf_mmap_base(gguf_handle)
      map_size = TinyNNMetal.tnn_gguf_mmap_size(gguf_handle)
      TinyNNMetal.tnn_session_attach_weight_mmap(@sess, map_base, map_size)

      eidx = TinyNNMetal.tnn_gguf_find_index(gguf_handle, "token_embd.weight")
      eoff = TinyNNMetal.tnn_gguf_tensor_file_offset(gguf_handle, eidx)
      etyp = TinyNNMetal.tnn_gguf_tensor_type(gguf_handle, eidx)
      @t_seq_token_embed = TinyNNMetal.tnn_input_2d_persistent_mmap(@sess,
                             @seq_vocab_size, @seq_d_model, etyp, eoff)

      fnidx = TinyNNMetal.tnn_gguf_find_index(gguf_handle, "output_norm.weight")
      fnoff = TinyNNMetal.tnn_gguf_tensor_file_offset(gguf_handle, fnidx)
      @t_seq_final_norm_gamma = TinyNNMetal.tnn_input_1d_persistent_mmap(@sess,
                                  @seq_d_model, 0, fnoff)

      if untied
        oidx = TinyNNMetal.tnn_gguf_find_index(gguf_handle, "output.weight")
        ooff = TinyNNMetal.tnn_gguf_tensor_file_offset(gguf_handle, oidx)
        otyp = TinyNNMetal.tnn_gguf_tensor_type(gguf_handle, oidx)
        @t_seq_output = TinyNNMetal.tnn_input_2d_persistent_mmap(@sess,
                          @seq_vocab_size, @seq_d_model, otyp, ooff)
      end
    end

    @seq_blocks_ffi = [LlamaSeqBlockFFIMetal.new]
    li_init = 1
    while li_init < @seq_n_layers
      @seq_blocks_ffi.push(LlamaSeqBlockFFIMetal.new)
      li_init = li_init + 1
    end

    # Per-block: allocate writable F32 weights + Adam m/v. Record
    # each (weight, m, v) triple on the block's parallel arrays so
    # build_training_step can emit opt_step per weight.
    li = 0
    while li < @seq_n_layers
      blk = @seq_blocks_ffi[li]
      prefix = "blk." + li.to_s + "."

      blk.t_seq_rn1_gamma = TinyNNMetal.tnn_input_1d_f32_persistent(@sess, @seq_d_model)
      blk.t_seq_rn2_gamma = TinyNNMetal.tnn_input_1d_f32_persistent(@sess, @seq_d_model)
      ft_add_1d(blk, blk.t_seq_rn1_gamma)
      ft_name_last(blk, prefix + "attn_norm.weight")
      ft_add_1d(blk, blk.t_seq_rn2_gamma)
      ft_name_last(blk, prefix + "ffn_norm.weight")

      blk.t_seq_w_q = [TinyNNMetal.tnn_input_2d_f32_persistent(@sess, @seq_d_head, @seq_d_model)]
      hq = 1
      while hq < @seq_n_heads
        blk.t_seq_w_q.push(TinyNNMetal.tnn_input_2d_f32_persistent(@sess, @seq_d_head, @seq_d_model))
        hq = hq + 1
      end
      hq2 = 0
      while hq2 < @seq_n_heads
        ft_add_2d(blk, blk.t_seq_w_q[hq2], @seq_d_head, @seq_d_model)
        ft_name_last(blk, prefix + "attn_q.head_" + hq2.to_s + ".weight")
        hq2 = hq2 + 1
      end

      blk.t_seq_w_k = [TinyNNMetal.tnn_input_2d_f32_persistent(@sess, @seq_d_head, @seq_d_model)]
      blk.t_seq_w_v = [TinyNNMetal.tnn_input_2d_f32_persistent(@sess, @seq_d_head, @seq_d_model)]
      hkv = 1
      while hkv < @seq_n_kv
        blk.t_seq_w_k.push(TinyNNMetal.tnn_input_2d_f32_persistent(@sess, @seq_d_head, @seq_d_model))
        blk.t_seq_w_v.push(TinyNNMetal.tnn_input_2d_f32_persistent(@sess, @seq_d_head, @seq_d_model))
        hkv = hkv + 1
      end
      hkv2 = 0
      while hkv2 < @seq_n_kv
        ft_add_2d(blk, blk.t_seq_w_k[hkv2], @seq_d_head, @seq_d_model)
        ft_name_last(blk, prefix + "attn_k.head_" + hkv2.to_s + ".weight")
        ft_add_2d(blk, blk.t_seq_w_v[hkv2], @seq_d_head, @seq_d_model)
        ft_name_last(blk, prefix + "attn_v.head_" + hkv2.to_s + ".weight")
        hkv2 = hkv2 + 1
      end

      if qkv_bias
        blk.t_seq_b_q = [TinyNNMetal.tnn_input_1d_f32_persistent(@sess, @seq_d_head)]
        hbq = 1
        while hbq < @seq_n_heads
          blk.t_seq_b_q.push(TinyNNMetal.tnn_input_1d_f32_persistent(@sess, @seq_d_head))
          hbq = hbq + 1
        end
        blk.t_seq_b_k = [TinyNNMetal.tnn_input_1d_f32_persistent(@sess, @seq_d_head)]
        blk.t_seq_b_v = [TinyNNMetal.tnn_input_1d_f32_persistent(@sess, @seq_d_head)]
        hbkv = 1
        while hbkv < @seq_n_kv
          blk.t_seq_b_k.push(TinyNNMetal.tnn_input_1d_f32_persistent(@sess, @seq_d_head))
          blk.t_seq_b_v.push(TinyNNMetal.tnn_input_1d_f32_persistent(@sess, @seq_d_head))
          hbkv = hbkv + 1
        end
        hbq2 = 0
        while hbq2 < @seq_n_heads
          ft_add_1d(blk, blk.t_seq_b_q[hbq2])
          ft_name_last(blk, prefix + "attn_q.head_" + hbq2.to_s + ".bias")
          hbq2 = hbq2 + 1
        end
        hbkv2 = 0
        while hbkv2 < @seq_n_kv
          ft_add_1d(blk, blk.t_seq_b_k[hbkv2])
          ft_name_last(blk, prefix + "attn_k.head_" + hbkv2.to_s + ".bias")
          ft_add_1d(blk, blk.t_seq_b_v[hbkv2])
          ft_name_last(blk, prefix + "attn_v.head_" + hbkv2.to_s + ".bias")
          hbkv2 = hbkv2 + 1
        end
      end

      blk.t_seq_w_o    = TinyNNMetal.tnn_input_2d_f32_persistent(@sess, @seq_d_model, @seq_d_model)
      blk.t_seq_w_gate = TinyNNMetal.tnn_input_2d_f32_persistent(@sess, @seq_d_ff,    @seq_d_model)
      blk.t_seq_w_up   = TinyNNMetal.tnn_input_2d_f32_persistent(@sess, @seq_d_ff,    @seq_d_model)
      blk.t_seq_w_down = TinyNNMetal.tnn_input_2d_f32_persistent(@sess, @seq_d_model, @seq_d_ff)
      ft_add_2d(blk, blk.t_seq_w_o,    @seq_d_model, @seq_d_model)
      ft_name_last(blk, prefix + "attn_output.weight")
      ft_add_2d(blk, blk.t_seq_w_gate, @seq_d_ff,    @seq_d_model)
      ft_name_last(blk, prefix + "ffn_gate.weight")
      ft_add_2d(blk, blk.t_seq_w_up,   @seq_d_ff,    @seq_d_model)
      ft_name_last(blk, prefix + "ffn_up.weight")
      ft_add_2d(blk, blk.t_seq_w_down, @seq_d_model, @seq_d_ff)
      ft_name_last(blk, prefix + "ffn_down.weight")

      # Mark every recorded weight as a trainable parameter.
      wi = 0
      while wi < blk.ft_weights.length
        TinyNNMetal.tnn_set_param(blk.ft_weights[wi])
        wi = wi + 1
      end

      li = li + 1
    end

    # Globals are trainable too only when embeddings are opt-in.
    if @ft_train_embeddings_enabled
      gi = 0
      while gi < @ft_globals_weights.length
        TinyNNMetal.tnn_set_param(@ft_globals_weights[gi])
        gi = gi + 1
      end
    end

    # GH#7 — block-causal attention mask for B>1 (see realize_for_mmap
    # for the same pattern). Caller sets cache.seq_b = N before realize.
    if @seq_b > 1
      tb_alloc = @seq_t * @seq_b
      @t_seq_attn_mask = TinyNNMetal.tnn_input_2d_f32_persistent(@sess, tb_alloc, tb_alloc)
    end

    TinyNNMetal.tnn_finalize_weights(@sess)

    if @seq_rope_scaling.kind == :llama3
      ff = Toy::RopeScaling.compute_llama3_freq_factors(
        @seq_d_head, @seq_rope_base,
        @seq_rope_scaling.orig_max_pos, @seq_rope_scaling.factor,
        @seq_rope_scaling.low_freq_factor, @seq_rope_scaling.high_freq_factor)
      TinyNNMetal.tnn_upload_from_float_array(@sess, @t_seq_rope_freq_factors, ff, ff.length)
    end

    if @seq_b > 1
      upload_block_causal_mask!
    end

    # Post-finalize: load every writable weight from the GGUF.
    if @ft_train_embeddings_enabled
      ft_load_globals(gguf_handle, untied)
    end
    ft_load_from_gguf(gguf_handle, qkv_bias)
    ft_zero_init_adam(qkv_bias)
    if @ft_train_embeddings_enabled
      ft_zero_init_adam_globals
    end

    build_forward_in_current_ctx
    TinyNNMetal.tnn_realize(@sess, @t_seq_logits)
    @seq_realized = true
  end

  # P2-α: from-scratch training entry. Allocates the same persistent
  # tensor layout as realize_for_full_finetune (embeddings + per-block
  # weights, all trainable F32 in ctx_w), then random-initialises
  # every weight via Ruby-side Gaussian upload — no GGUF needed.
  #
  # Force-enables `@ft_train_embeddings_enabled` so the existing
  # full-FT machinery allocates persistent F32 embeddings instead
  # of the mmap branch. Caller doesn't need to call
  # enable_full_finetune_embeddings! first.
  #
  # Currently Llama-arch only (RMSNorm + GQA + RoPE + SwiGLU). Other
  # architectures (GPT-2 LN, MHA + biases) need a separate trainer
  # cache class; deferred until we actually need GPT-2 from-scratch.
  def realize_for_random_init(cfg, t_seq, t_batch, weight_dtype, untied, qkv_bias, seed, init_scale)
    @ft_train_embeddings_enabled = true   # forces persistent-F32 alloc of embeddings
    @seq_full_finetune_enabled   = true   # build_training_step gates on this

    @seq_t          = t_seq
    # GH#7 — micro-batching. B=1 keeps the codepath bit-identical to
    # the pre-GH#7 single-sequence training. B>1 lays out tokens as a
    # flat [T*B] vector with a block-causal attention mask uploaded
    # post-finalize and applied via soft_max_ext.
    @seq_b          = t_batch
    # GH#9 — mixed-precision compute. 0 = F32 (bit-identical to
    # pre-GH#9). 1 = F16, 30 = BF16. See mp_matmul + ivar comment in
    # initialize for the master-copy details.
    @seq_weight_dtype = weight_dtype
    @seq_d_model    = cfg.d_model
    @seq_d_ff       = cfg.d_ff
    @seq_n_heads    = cfg.n_heads
    @seq_n_kv       = cfg.n_kv
    @seq_d_head     = cfg.head_dim
    @seq_group_size = cfg.n_heads / cfg.n_kv
    @seq_n_layers   = cfg.n_layers
    @seq_vocab_size = cfg.vocab
    @seq_rope_base    = cfg.rope_base
    @seq_rope_scaling = cfg.rope_scaling
    @seq_rms_eps    = cfg.rms_eps

    @sess                  = TinyNNMetal.tnn_session_new(2)
    # GH#17 — per-head decomposition makes node count scale as
    # O(n_layers × n_heads). The default 65536 cap overflows on
    # 24L × 16-head Qwen-shape at backward-expand. Empirically a
    # 24L × 16-head model needs ~450k nodes for forward + backward +
    # AdamW, so we budget ~1000 nodes per (layer × head) cell + floor.
    cap = cfg.n_layers * cfg.n_heads * 1000 + 65536
    TinyNNMetal.tnn_session_set_graph_capacity(@sess, cap)
    @seq_has_untied_output = untied
    @seq_has_qkv_bias      = qkv_bias
    @seq_donor_d_in        = cfg.donor_d_in   # E2.3 — 0 disables projection lens

    if @seq_rope_scaling.kind == :llama3
      @t_seq_rope_freq_factors = TinyNNMetal.tnn_rope_freq_factors_alloc(@sess, cfg.head_dim)
    else
      @t_seq_rope_freq_factors = TinyNNMetal.tnn_null_ptr
    end

    # Globals — all trainable persistent F32. Each gets a llama.cpp-
    # convention name so drift/grad/checkpoint consumers can align
    # across runs (toy#semantic-tensor-names, GH#11).
    # E2.3 — projection lens. When cfg.donor_d_in > 0 the embed
    # table has donor_d_in columns (typically loaded from a donor
    # GGUF post-realize, frozen); a trainable Linear(donor_d_in,
    # d_model) named "lens.proj.weight" sits between get_rows and
    # the first block. When 0, behaviour is identical to before.
    if @seq_donor_d_in > 0
      # token_embd ne=[donor_d_in, vocab] — donor-width rows.
      @t_seq_token_embed = TinyNNMetal.tnn_input_2d_f32_persistent(@sess,
                             @seq_vocab_size, @seq_donor_d_in)
      # Frozen — NOT in ft_globals so backward won't compute its grad
      # and build_training_step won't emit an opt_step for it. Caller
      # uploads donor values post-finalize.
      TinyNNMetal.tnn_tensor_set_name(@t_seq_token_embed, "token_embd.weight")
      # W_proj ne=[donor_d_in, d_model] so matmul(W_proj, embed)
      # contracts donor_d_in → d_model. Trainable.
      @t_seq_w_proj = TinyNNMetal.tnn_input_2d_f32_persistent(@sess,
                        @seq_d_model, @seq_donor_d_in)
      ft_add_global_2d(@t_seq_w_proj, @seq_d_model, @seq_donor_d_in)
      ft_name_last_global("lens.proj.weight")
    else
      @t_seq_token_embed = TinyNNMetal.tnn_input_2d_f32_persistent(@sess,
                             @seq_vocab_size, @seq_d_model)
      ft_add_global_2d(@t_seq_token_embed, @seq_vocab_size, @seq_d_model)
      ft_name_last_global("token_embd.weight")
    end

    @t_seq_final_norm_gamma = TinyNNMetal.tnn_input_1d_f32_persistent(@sess, @seq_d_model)
    ft_add_global_1d(@t_seq_final_norm_gamma)
    ft_name_last_global("output_norm.weight")

    if untied
      @t_seq_output = TinyNNMetal.tnn_input_2d_f32_persistent(@sess,
                        @seq_vocab_size, @seq_d_model)
      ft_add_global_2d(@t_seq_output, @seq_vocab_size, @seq_d_model)
      ft_name_last_global("output.weight")
    end

    # Per-block weights — identical structure to realize_for_full_finetune.
    @seq_blocks_ffi = [LlamaSeqBlockFFIMetal.new]
    li_init = 1
    while li_init < @seq_n_layers
      @seq_blocks_ffi.push(LlamaSeqBlockFFIMetal.new)
      li_init = li_init + 1
    end

    li = 0
    while li < @seq_n_layers
      blk = @seq_blocks_ffi[li]
      prefix = "blk." + li.to_s + "."

      blk.t_seq_rn1_gamma = TinyNNMetal.tnn_input_1d_f32_persistent(@sess, @seq_d_model)
      blk.t_seq_rn2_gamma = TinyNNMetal.tnn_input_1d_f32_persistent(@sess, @seq_d_model)
      ft_add_1d(blk, blk.t_seq_rn1_gamma)
      ft_name_last(blk, prefix + "attn_norm.weight")
      ft_add_1d(blk, blk.t_seq_rn2_gamma)
      ft_name_last(blk, prefix + "ffn_norm.weight")

      blk.t_seq_w_q = [TinyNNMetal.tnn_input_2d_f32_persistent(@sess, @seq_d_head, @seq_d_model)]
      hq = 1
      while hq < @seq_n_heads
        blk.t_seq_w_q.push(TinyNNMetal.tnn_input_2d_f32_persistent(@sess, @seq_d_head, @seq_d_model))
        hq = hq + 1
      end
      hq2 = 0
      while hq2 < @seq_n_heads
        ft_add_2d(blk, blk.t_seq_w_q[hq2], @seq_d_head, @seq_d_model)
        ft_name_last(blk, prefix + "attn_q.head_" + hq2.to_s + ".weight")
        hq2 = hq2 + 1
      end

      blk.t_seq_w_k = [TinyNNMetal.tnn_input_2d_f32_persistent(@sess, @seq_d_head, @seq_d_model)]
      blk.t_seq_w_v = [TinyNNMetal.tnn_input_2d_f32_persistent(@sess, @seq_d_head, @seq_d_model)]
      hkv = 1
      while hkv < @seq_n_kv
        blk.t_seq_w_k.push(TinyNNMetal.tnn_input_2d_f32_persistent(@sess, @seq_d_head, @seq_d_model))
        blk.t_seq_w_v.push(TinyNNMetal.tnn_input_2d_f32_persistent(@sess, @seq_d_head, @seq_d_model))
        hkv = hkv + 1
      end
      hkv2 = 0
      while hkv2 < @seq_n_kv
        ft_add_2d(blk, blk.t_seq_w_k[hkv2], @seq_d_head, @seq_d_model)
        ft_name_last(blk, prefix + "attn_k.head_" + hkv2.to_s + ".weight")
        ft_add_2d(blk, blk.t_seq_w_v[hkv2], @seq_d_head, @seq_d_model)
        ft_name_last(blk, prefix + "attn_v.head_" + hkv2.to_s + ".weight")
        hkv2 = hkv2 + 1
      end

      blk.t_seq_w_o    = TinyNNMetal.tnn_input_2d_f32_persistent(@sess, @seq_d_model, @seq_n_heads * @seq_d_head)
      blk.t_seq_w_gate = TinyNNMetal.tnn_input_2d_f32_persistent(@sess, @seq_d_ff,    @seq_d_model)
      blk.t_seq_w_up   = TinyNNMetal.tnn_input_2d_f32_persistent(@sess, @seq_d_ff,    @seq_d_model)
      blk.t_seq_w_down = TinyNNMetal.tnn_input_2d_f32_persistent(@sess, @seq_d_model, @seq_d_ff)
      ft_add_2d(blk, blk.t_seq_w_o,    @seq_d_model, @seq_n_heads * @seq_d_head)
      ft_name_last(blk, prefix + "attn_output.weight")
      ft_add_2d(blk, blk.t_seq_w_gate, @seq_d_ff,    @seq_d_model)
      ft_name_last(blk, prefix + "ffn_gate.weight")
      ft_add_2d(blk, blk.t_seq_w_up,   @seq_d_ff,    @seq_d_model)
      ft_name_last(blk, prefix + "ffn_up.weight")
      ft_add_2d(blk, blk.t_seq_w_down, @seq_d_model, @seq_d_ff)
      ft_name_last(blk, prefix + "ffn_down.weight")

      wi = 0
      while wi < blk.ft_weights.length
        TinyNNMetal.tnn_set_param(blk.ft_weights[wi])
        wi = wi + 1
      end

      li = li + 1
    end

    # Mark globals as params too (gated on @ft_train_embeddings_enabled).
    gi = 0
    while gi < @ft_globals_weights.length
      TinyNNMetal.tnn_set_param(@ft_globals_weights[gi])
      gi = gi + 1
    end

    # GH#7 — batched-training attention mask. Allocated in ctx_w as
    # f32 persistent (so it survives reset_for_rebuild without being
    # re-uploaded each step), shape ne=[T*B, T*B]. NOT marked as a
    # param — backward must not compute its gradient. Values uploaded
    # post-finalize. Only allocated when B>1; B=1 keeps the legacy
    # diag_mask_inf + softmax path with @t_seq_attn_mask=NULL.
    if @seq_b > 1
      tb_alloc = @seq_t * @seq_b
      @t_seq_attn_mask = TinyNNMetal.tnn_input_2d_f32_persistent(@sess, tb_alloc, tb_alloc)
    end

    TinyNNMetal.tnn_finalize_weights(@sess)

    if @seq_rope_scaling.kind == :llama3
      ff = Toy::RopeScaling.compute_llama3_freq_factors(
        @seq_d_head, @seq_rope_base,
        @seq_rope_scaling.orig_max_pos, @seq_rope_scaling.factor,
        @seq_rope_scaling.low_freq_factor, @seq_rope_scaling.high_freq_factor)
      TinyNNMetal.tnn_upload_from_float_array(@sess, @t_seq_rope_freq_factors, ff, ff.length)
    end

    if @seq_b > 1
      upload_block_causal_mask!
    end

    # Random-init every weight + zero biases + ones gammas.
    upload_random_init!(seed, init_scale, qkv_bias, untied)
    ft_zero_init_adam(qkv_bias)
    ft_zero_init_adam_globals

    build_forward_in_current_ctx
    TinyNNMetal.tnn_realize(@sess, @t_seq_logits)
    @seq_realized = true
  end

  # GH#7 — build + upload the block-causal attention mask for B>1.
  # Layout: scores from matmul(K[d_head, T*B], Q[d_head, T*B]) have
  # ne=[T*B, T*B] where ne0 indexes keys and ne1 indexes queries
  # (ggml column-major: flat[ne0_idx + ne1_idx * T*B]). For query
  # position i1 = b_q*T + p_q and key position i0 = b_k*T + p_k:
  #   mask = 0.0  iff b_k == b_q AND p_k <= p_q   (intra-batch causal)
  #   mask = NEG  otherwise                      (cross-batch + future)
  # NEG = -1.0e30 so exp(NEG) == 0.0 in f32 (avoids Float::INFINITY,
  # which would also work but is one less Spinel codegen variable).
  def upload_block_causal_mask!
    tb = @seq_t * @seq_b
    neg = -1.0e30
    mask_arr = [0.0]; mask_arr.pop
    i1 = 0
    while i1 < tb
      b_q = i1 / @seq_t
      p_q = i1 % @seq_t
      i0 = 0
      while i0 < tb
        b_k = i0 / @seq_t
        p_k = i0 % @seq_t
        if b_k == b_q && p_k <= p_q
          mask_arr.push(0.0)
        else
          mask_arr.push(neg)
        end
        i0 = i0 + 1
      end
      i1 = i1 + 1
    end
    TinyNNMetal.tnn_upload_from_float_array(@sess, @t_seq_attn_mask, mask_arr, mask_arr.length)
  end

  # Fill every persistent weight tensor with N(0, std) values.
  # Norm gammas → 1.0, biases (if present) → 0.0, matmul weights →
  # N(0, init_scale/sqrt(fan_in)). Token embedding uses GPT-2-style
  # N(0, 0.02). All values computed in Ruby, uploaded in bulk via
  # tnn_upload_from_float_array.
  def upload_random_init!(seed, init_scale, qkv_bias, untied)
    state = [seed]

    # Token embed: width depends on projection lens.
    # When donor_d_in > 0, embed is [vocab, donor_d_in] (caller may
    # overwrite with real donor values after realize); the trainable
    # projection W_proj [donor_d_in, d_model] also gets a Gaussian init.
    embed_cols = @seq_donor_d_in > 0 ? @seq_donor_d_in : @seq_d_model
    upload_gaussian(@t_seq_token_embed, @seq_vocab_size * embed_cols, 0.02, state)
    if @seq_donor_d_in > 0
      upload_gaussian(@t_seq_w_proj, @seq_donor_d_in * @seq_d_model,
                       1.0 / Math.sqrt(@seq_donor_d_in.to_f), state)
    end
    upload_constant(@t_seq_final_norm_gamma, @seq_d_model, 1.0)
    if untied
      upload_gaussian(@t_seq_output, @seq_vocab_size * @seq_d_model, 0.02, state)
    end

    inv_sqrt_d   = init_scale / Math.sqrt(@seq_d_model.to_f)
    inv_sqrt_dff = init_scale / Math.sqrt(@seq_d_ff.to_f)

    li = 0
    while li < @seq_n_layers
      blk = @seq_blocks_ffi[li]
      upload_constant(blk.t_seq_rn1_gamma, @seq_d_model, 1.0)
      upload_constant(blk.t_seq_rn2_gamma, @seq_d_model, 1.0)

      hq = 0
      while hq < @seq_n_heads
        upload_gaussian(blk.t_seq_w_q[hq], @seq_d_head * @seq_d_model, inv_sqrt_d, state)
        hq = hq + 1
      end
      hkv = 0
      while hkv < @seq_n_kv
        upload_gaussian(blk.t_seq_w_k[hkv], @seq_d_head * @seq_d_model, inv_sqrt_d, state)
        upload_gaussian(blk.t_seq_w_v[hkv], @seq_d_head * @seq_d_model, inv_sqrt_d, state)
        hkv = hkv + 1
      end

      upload_gaussian(blk.t_seq_w_o,    @seq_d_model * @seq_n_heads * @seq_d_head, inv_sqrt_d, state)
      upload_gaussian(blk.t_seq_w_gate, @seq_d_ff    * @seq_d_model, inv_sqrt_d, state)
      upload_gaussian(blk.t_seq_w_up,   @seq_d_ff    * @seq_d_model, inv_sqrt_d, state)
      upload_gaussian(blk.t_seq_w_down, @seq_d_model * @seq_d_ff,    inv_sqrt_dff, state)
      li = li + 1
    end
  end

  # Box-Muller from a xorshift64-driven uniform stream. state is a
  # one-element Array<Integer> so the mutable PRNG state survives
  # across calls without using class variables. Always emits exactly
  # `n` Gaussian-distributed F32 values via tnn_upload_from_float_array.
  def upload_gaussian(tensor, n, std, state)
    buf = [0.0]; buf.pop
    pair = 0
    saved = 0.0
    i = 0
    while i < n
      if pair == 0
        u1 = xorshift_uniform!(state)
        u2 = xorshift_uniform!(state)
        if u1 < 1.0e-300; u1 = 1.0e-300; end
        r = Math.sqrt(-2.0 * Math.log(u1))
        theta = 2.0 * Math::PI * u2
        z0 = r * Math.cos(theta) * std
        z1 = r * Math.sin(theta) * std
        buf.push(z0)
        saved = z1
        pair = 1
      else
        buf.push(saved)
        pair = 0
      end
      i = i + 1
    end
    TinyNNMetal.tnn_upload_from_float_array(@sess, tensor, buf, n)
  end

  def upload_constant(tensor, n, v)
    buf = [0.0]; buf.pop
    i = 0
    while i < n
      buf.push(v)
      i = i + 1
    end
    TinyNNMetal.tnn_upload_from_float_array(@sess, tensor, buf, n)
  end

  # xorshift64 → uniform in (0, 1). Mutates state[0].
  def xorshift_uniform!(state)
    x = state[0]
    x = x ^ (x << 13)
    x = x & 0xFFFFFFFFFFFFFFFF
    x = x ^ (x >> 7)
    x = x ^ (x << 17)
    x = x & 0xFFFFFFFFFFFFFFFF
    state[0] = x
    (x.to_f / 18446744073709551616.0) + 1.0e-300
  end

  # Append (weight, m, v) to the block's parallel arrays. Allocates
  # Adam m and v of the same shape as `weight` as a side effect.
  def ft_add_2d(blk, weight, rows, cols)
    blk.ft_weights.push(weight)
    blk.ft_m.push(TinyNNMetal.tnn_input_2d_f32_persistent(@sess, rows, cols))
    blk.ft_v.push(TinyNNMetal.tnn_input_2d_f32_persistent(@sess, rows, cols))
  end

  def ft_add_1d(blk, weight)
    n = TinyNNMetal.tnn_tensor_nelements(weight)
    blk.ft_weights.push(weight)
    blk.ft_m.push(TinyNNMetal.tnn_input_1d_f32_persistent(@sess, n))
    blk.ft_v.push(TinyNNMetal.tnn_input_1d_f32_persistent(@sess, n))
  end

  # Name the most-recently-pushed (weight, m, v) triple in a block.
  # Used right after ft_add_2d / ft_add_1d so drift/grad event consumers
  # see llama.cpp-convention names like "blk.0.attn_norm.weight" instead
  # of ggml's auto-generated "node_N". toy#semantic-tensor-names.
  def ft_name_last(blk, name)
    last = blk.ft_weights.length - 1
    TinyNNMetal.tnn_tensor_set_name(blk.ft_weights[last], name)
    TinyNNMetal.tnn_tensor_set_name(blk.ft_m[last],       name + ".m")
    TinyNNMetal.tnn_tensor_set_name(blk.ft_v[last],       name + ".v")
  end

  def ft_name_last_global(name)
    last = @ft_globals_weights.length - 1
    TinyNNMetal.tnn_tensor_set_name(@ft_globals_weights[last], name)
    TinyNNMetal.tnn_tensor_set_name(@ft_globals_m[last],       name + ".m")
    TinyNNMetal.tnn_tensor_set_name(@ft_globals_v[last],       name + ".v")
  end

  # Same shape as ft_add_2d / ft_add_1d but writes to the cache-level
  # globals arrays (token_embed, final-norm, untied output).
  def ft_add_global_2d(weight, rows, cols)
    @ft_globals_weights.push(weight)
    @ft_globals_m.push(TinyNNMetal.tnn_input_2d_f32_persistent(@sess, rows, cols))
    @ft_globals_v.push(TinyNNMetal.tnn_input_2d_f32_persistent(@sess, rows, cols))
  end

  def ft_add_global_1d(weight)
    n = TinyNNMetal.tnn_tensor_nelements(weight)
    @ft_globals_weights.push(weight)
    @ft_globals_m.push(TinyNNMetal.tnn_input_1d_f32_persistent(@sess, n))
    @ft_globals_v.push(TinyNNMetal.tnn_input_1d_f32_persistent(@sess, n))
  end

  # Load token_embed + final-norm + (untied) output from the GGUF
  # into their now-allocated backend buffers.
  def ft_load_globals(gguf, untied)
    eidx = TinyNNMetal.tnn_gguf_find_index(gguf, "token_embd.weight")
    TinyNNMetal.tnn_gguf_copy_to_persistent(gguf, eidx, @sess, @t_seq_token_embed)
    fnidx = TinyNNMetal.tnn_gguf_find_index(gguf, "output_norm.weight")
    TinyNNMetal.tnn_gguf_copy_1d_to_persistent(gguf, fnidx, @sess, @t_seq_final_norm_gamma)
    if untied
      oidx = TinyNNMetal.tnn_gguf_find_index(gguf, "output.weight")
      TinyNNMetal.tnn_gguf_copy_to_persistent(gguf, oidx, @sess, @t_seq_output)
    end
  end

  def ft_zero_init_adam_globals
    gi = 0
    while gi < @ft_globals_weights.length
      TinyNNMetal.tnn_zero_tensor(@sess, @ft_globals_m[gi])
      TinyNNMetal.tnn_zero_tensor(@sess, @ft_globals_v[gi])
      gi = gi + 1
    end
  end

  # Pull bytes from the GGUF into each writable weight. Uses the
  # existing C-side dequantize-and-copy primitives so a Q8 source
  # transparently becomes F32 in the target tensor.
  def ft_load_from_gguf(gguf, qkv_bias)
    li = 0
    while li < @seq_n_layers
      blk = @seq_blocks_ffi[li]
      prefix = "blk." + li.to_s

      rn1_idx = TinyNNMetal.tnn_gguf_find_index(gguf, prefix + ".attn_norm.weight")
      rn2_idx = TinyNNMetal.tnn_gguf_find_index(gguf, prefix + ".ffn_norm.weight")
      TinyNNMetal.tnn_gguf_copy_1d_to_persistent(gguf, rn1_idx, @sess, blk.t_seq_rn1_gamma)
      TinyNNMetal.tnn_gguf_copy_1d_to_persistent(gguf, rn2_idx, @sess, blk.t_seq_rn2_gamma)

      q_idx = TinyNNMetal.tnn_gguf_find_index(gguf, prefix + ".attn_q.weight")
      hq = 0
      while hq < @seq_n_heads
        TinyNNMetal.tnn_gguf_copy_head_slice_to_persistent_native(gguf, q_idx, @sess,
          blk.t_seq_w_q[hq], hq, @seq_n_heads, @seq_d_model, @seq_d_head)
        hq = hq + 1
      end

      k_idx = TinyNNMetal.tnn_gguf_find_index(gguf, prefix + ".attn_k.weight")
      v_idx = TinyNNMetal.tnn_gguf_find_index(gguf, prefix + ".attn_v.weight")
      hkv = 0
      while hkv < @seq_n_kv
        TinyNNMetal.tnn_gguf_copy_head_slice_to_persistent_native(gguf, k_idx, @sess,
          blk.t_seq_w_k[hkv], hkv, @seq_n_kv, @seq_d_model, @seq_d_head)
        TinyNNMetal.tnn_gguf_copy_head_slice_to_persistent_native(gguf, v_idx, @sess,
          blk.t_seq_w_v[hkv], hkv, @seq_n_kv, @seq_d_model, @seq_d_head)
        hkv = hkv + 1
      end

      if qkv_bias
        # qbias / kbias / vbias are 1-D head-sliced. We don't have a
        # dedicated head-slice loader for them; fall through and use
        # tnn_gguf_copy_head_bias_slice_to_persistent.
        qb_idx = TinyNNMetal.tnn_gguf_find_index(gguf, prefix + ".attn_q.bias")
        kb_idx = TinyNNMetal.tnn_gguf_find_index(gguf, prefix + ".attn_k.bias")
        vb_idx = TinyNNMetal.tnn_gguf_find_index(gguf, prefix + ".attn_v.bias")
        hbq = 0
        while hbq < @seq_n_heads
          TinyNNMetal.tnn_gguf_copy_head_bias_slice_to_persistent(gguf, qb_idx, @sess,
            blk.t_seq_b_q[hbq], hbq, @seq_d_head)
          hbq = hbq + 1
        end
        hbkv = 0
        while hbkv < @seq_n_kv
          TinyNNMetal.tnn_gguf_copy_head_bias_slice_to_persistent(gguf, kb_idx, @sess,
            blk.t_seq_b_k[hbkv], hbkv, @seq_d_head)
          TinyNNMetal.tnn_gguf_copy_head_bias_slice_to_persistent(gguf, vb_idx, @sess,
            blk.t_seq_b_v[hbkv], hbkv, @seq_d_head)
          hbkv = hbkv + 1
        end
      end

      o_idx    = TinyNNMetal.tnn_gguf_find_index(gguf, prefix + ".attn_output.weight")
      gate_idx = TinyNNMetal.tnn_gguf_find_index(gguf, prefix + ".ffn_gate.weight")
      up_idx   = TinyNNMetal.tnn_gguf_find_index(gguf, prefix + ".ffn_up.weight")
      down_idx = TinyNNMetal.tnn_gguf_find_index(gguf, prefix + ".ffn_down.weight")
      TinyNNMetal.tnn_gguf_copy_to_persistent(gguf, o_idx,    @sess, blk.t_seq_w_o)
      TinyNNMetal.tnn_gguf_copy_to_persistent(gguf, gate_idx, @sess, blk.t_seq_w_gate)
      TinyNNMetal.tnn_gguf_copy_to_persistent(gguf, up_idx,   @sess, blk.t_seq_w_up)
      TinyNNMetal.tnn_gguf_copy_to_persistent(gguf, down_idx, @sess, blk.t_seq_w_down)

      li = li + 1
    end
  end

  # Zero-init the Adam moments. m and v both start at 0 per the
  # AdamW step-0 contract. Uses the backend-side memset primitive
  # (tnn_zero_tensor) so a 1 GB Adam state doesn't materialize a
  # Mat-of-zeros in Ruby first.
  def ft_zero_init_adam(qkv_bias)
    li = 0
    while li < @seq_n_layers
      blk = @seq_blocks_ffi[li]
      i = 0
      while i < blk.ft_weights.length
        TinyNNMetal.tnn_zero_tensor(@sess, blk.ft_m[i])
        TinyNNMetal.tnn_zero_tensor(@sess, blk.ft_v[i])
        i = i + 1
      end
      li = li + 1
    end
  end

  # Build the forward graph in the CURRENT compute context. Used both
  # from realize_for_mmap (first realize) and after tnn_reset_for_rebuild
  # (e.g. when switching from inference to training, which needs the
  # forward + loss + backward + opt_step all in one rebuilt ctx).
  # Stores the per-graph tensor handles back on `self`.
  def build_forward_in_current_ctx
    # GH#7 — at B=1, @seq_t * @seq_b == @seq_t (legacy behaviour).
    # At B>1, the layout is flat [T*B]: per-batch positions cycle
    # 0..T-1 (the caller-built positions array is responsible for
    # that ordering); RoPE applies per-batch positional encoding
    # because rope_ext reads positions[k] for each ne[2] slot.
    tb = @seq_t * @seq_b
    @t_seq_token_ids = TinyNNMetal.tnn_input_1d_i32(@sess, tb)
    @t_seq_positions = TinyNNMetal.tnn_input_1d_i32_ctx(@sess, tb)

    eps   = @seq_rms_eps
    scale = 1.0 / Math.sqrt(@seq_d_head.to_f)

    @t_seq_x_embed = TinyNNMetal.tnn_get_rows(@sess, @t_seq_token_embed, @t_seq_token_ids)
    TinyNNMetal.tnn_set_output(@t_seq_x_embed)

    # E2.3 — projection lens. ggml matmul(W, x) with W=[donor_d_in, d_model]
    # and x=[donor_d_in, T] gives [d_model, T] (contraction on ne[0]).
    if @seq_donor_d_in > 0
      t_proj = TinyNNMetal.tnn_matmul(@sess, @t_seq_w_proj, @t_seq_x_embed)
      TinyNNMetal.tnn_set_output(t_proj)
      t_cur = t_proj
    else
      t_cur = @t_seq_x_embed
    end
    li_g = 0
    while li_g < @seq_n_layers
      t_cur = build_seq_block(t_cur, @seq_blocks_ffi[li_g], scale, eps)
      li_g = li_g + 1
    end

    @t_seq_x_final = TinyNNMetal.tnn_rms_norm(@sess, t_cur, @t_seq_final_norm_gamma, eps)
    TinyNNMetal.tnn_set_output(@t_seq_x_final)

    if @seq_has_untied_output
      @t_seq_logits = TinyNNMetal.tnn_matmul(@sess, @t_seq_output, @t_seq_x_final)
    else
      @t_seq_logits = TinyNNMetal.tnn_matmul(@sess, @t_seq_token_embed, @t_seq_x_final)
    end
    TinyNNMetal.tnn_set_output(@t_seq_logits)
  end

  # M3 step 3 — rebuild the session graph as forward + CE loss + backward
  # + AdamW opt_step over every LoRA pair. After this, callers upload
  # token IDs + positions + labels (one-hot vocab×T) + hp vector and
  # call tnn_compute_backward to get one training step over the whole
  # T-position sequence.
  #
  # Returns the (loss_tensor, labels_tensor, hp_tensor) triple.
  def build_training_step
    if !@seq_full_finetune_enabled && (!@seq_lora_q_enabled || !@seq_lora_q_adamw_enabled)
      puts "build_training_step: requires enable_lora_q! AND enable_lora_q_adamw!  (or enable_full_finetune!)"
      return nil
    end
    TinyNNMetal.tnn_reset_for_rebuild(@sess)
    build_forward_in_current_ctx

    # Label tensor: same shape as logits, ggml ne=[vocab, T*B]. Our
    # wrapper takes (rows, cols) and emits ggml(cols, rows), so pass
    # (T*B, vocab) here to get ne=[vocab, T*B]. One-hot per ne1-column
    # (i.e. per (batch, position) slot). At B=1, identical to legacy.
    t_labels = TinyNNMetal.tnn_input_2d_f32(@sess, @seq_t * @seq_b, @seq_vocab_size)
    # Hyper-params vector for AdamW: alpha, beta1, beta2, eps, wd, beta1h, beta2h.
    t_hp = TinyNNMetal.tnn_input_1d_f32(@sess, 7)

    # CE loss over all T columns. ggml_cross_entropy_loss returns the
    # mean over columns — masking is a follow-up (would zero specific
    # columns in labels before this op).
    t_loss = TinyNNMetal.tnn_cross_entropy_loss(@sess, @t_seq_logits, t_labels)
    TinyNNMetal.tnn_set_output(t_loss)
    TinyNNMetal.tnn_set_loss(t_loss)

    TinyNNMetal.tnn_build_forward_only(@sess, t_loss)
    TinyNNMetal.tnn_build_backward(@sess)

    if @seq_full_finetune_enabled
      # F3 — emit opt_step_adamw for every recorded (weight, m, v)
      # triple. The arrays are populated in realize_for_full_finetune.
      li = 0
      while li < @seq_n_layers
        blk = @seq_blocks_ffi[li]
        wi = 0
        while wi < blk.ft_weights.length
          tw = blk.ft_weights[wi]
          tg = TinyNNMetal.tnn_tensor_grad(@sess, tw)
          to = TinyNNMetal.tnn_opt_step_adamw(@sess, tw, tg,
                                          blk.ft_m[wi], blk.ft_v[wi], t_hp)
          TinyNNMetal.tnn_extend_backward_graph(@sess, to)
          wi = wi + 1
        end
        li = li + 1
      end
      # Globals (token_embed, final-norm, optional untied output).
      gi = 0
      while gi < @ft_globals_weights.length
        tw = @ft_globals_weights[gi]
        tg = TinyNNMetal.tnn_tensor_grad(@sess, tw)
        to = TinyNNMetal.tnn_opt_step_adamw(@sess, tw, tg,
                                        @ft_globals_m[gi], @ft_globals_v[gi], t_hp)
        TinyNNMetal.tnn_extend_backward_graph(@sess, to)
        gi = gi + 1
      end
    else
      # LoRA-only training (M3 step 3). One opt_step_adamw per LoRA-A
      # and per LoRA-B tensor; thread each through extend_backward_graph
      # so sched sees the writes.
      li = 0
      while li < @seq_n_layers
        blk = @seq_blocks_ffi[li]
        hq = 0
        while hq < @seq_n_heads
          t_a       = blk.t_seq_w_lora_a_q[hq]
          t_b       = blk.t_seq_w_lora_b_q[hq]
          t_grad_a  = TinyNNMetal.tnn_tensor_grad(@sess, t_a)
          t_grad_b  = TinyNNMetal.tnn_tensor_grad(@sess, t_b)
          t_opt_a   = TinyNNMetal.tnn_opt_step_adamw(@sess, t_a, t_grad_a,
                                                  blk.t_seq_w_lora_a_q_m[hq],
                                                  blk.t_seq_w_lora_a_q_v[hq], t_hp)
          t_opt_b   = TinyNNMetal.tnn_opt_step_adamw(@sess, t_b, t_grad_b,
                                                  blk.t_seq_w_lora_b_q_m[hq],
                                                  blk.t_seq_w_lora_b_q_v[hq], t_hp)
          TinyNNMetal.tnn_extend_backward_graph(@sess, t_opt_a)
          TinyNNMetal.tnn_extend_backward_graph(@sess, t_opt_b)
          hq = hq + 1
        end
        li = li + 1
      end
    end

    # Pin every node in graph_b before sched-alloc — workaround for the
    # ggml-cpu sched-aliasing bug on long backward chains (documented in
    # project_cpu_cuda_lora_train_divergence_2026_05_21). Memory cost
    # grows roughly with node count; fine for SmolLM2-135M at T<=64.
    TinyNNMetal.tnn_pin_all_graph_b_nodes(@sess)
    TinyNNMetal.tnn_realize_backward(@sess)
    [t_loss, t_labels, t_hp]
  end

  # GH#9 — mixed-precision matmul helper. When @seq_weight_dtype != 0,
  # casts the F32 master weight to the chosen dtype before the matmul
  # so the math hits the lower-precision tensor-core path. At
  # @seq_weight_dtype == 0 this is `tnn_matmul` verbatim — bit-
  # identical to pre-GH#9 graphs.
  #
  # The cast is in-graph: ggml_cast emits a CPY-with-typed-dst node
  # that sched buffers in transient scratch. Once the matmul consumes
  # the cast result, sched can reuse the buffer. Backward through
  # the cast flows correctly via GGML_OP_CPY's backward case (grad
  # of cast(src) preserves src's dtype, so the F32 master receives
  # its grad as expected).
  def mp_matmul(w, x)
    if @seq_weight_dtype != 0
      wc = TinyNNMetal.tnn_cast(@sess, w, @seq_weight_dtype)
      return TinyNNMetal.tnn_matmul(@sess, wc, x)
    end
    TinyNNMetal.tnn_matmul(@sess, w, x)
  end

  # GGUF type → bytes-per-row stride for per-head slicing. Mirrors the
  # SmolLM2KVFFICache helper of the same name. F32=0, Q8_0=8.
  def head_nbytes(ggml_type, d_head, d_model)
    if ggml_type == 0
      d_head * d_model * 4
    elsif ggml_type == 8
      d_head * (d_model / 32) * 34
    else
      0
    end
  end

  # One transformer block.
  #
  #   h1   = RMSNorm(x)
  #   per KV head kv_h:
  #     k_pre = w_k[kv_h] @ h1  (+ b_k[kv_h])         ne=[d_head, T]
  #     k     = RoPE(k_pre, positions)
  #     v     = w_v[kv_h] @ h1  (+ b_v[kv_h])         ne=[d_head, T]
  #     v_t   = transpose(v)                          ne=[T, d_head]
  #   per Q head q_h (kv_h = q_h / group_size):
  #     q_pre = w_q[q_h] @ h1  (+ b_q[q_h])           ne=[d_head, T]
  #     q     = RoPE(q_pre, positions)
  #     scores = k[kv_h] @ q                          ne=[T_keys, T_queries]
  #     scaled = scores / sqrt(d_head)
  #     masked = diag_mask_inf(scaled, 0)              causal triangle
  #     attn   = softmax(masked)                       ne=[T, T]
  #     head_h = v_t[kv_h] @ attn                     ne=[d_head, T]
  #   concat heads along ne0 → ne=[d_model, T]
  #   x_attn = x + (w_o @ concat)
  #   h2     = RMSNorm(x_attn)
  #   ff     = w_down @ (silu(w_gate @ h2) * (w_up @ h2))
  #   x_out  = x_attn + ff
  def build_seq_block(t_x, blk, scale, eps)
    t_h = TinyNNMetal.tnn_rms_norm(@sess, t_x, blk.t_seq_rn1_gamma, eps)
    # GH#15 — tap the post-attn-norm activation. set_output keeps it
    # alive across graph computation so the host can download it.
    blk.tap_attn_norm = t_h
    TinyNNMetal.tnn_set_output(t_h)

    # K, V over all KV heads. Pre-compute v_t per head so the per-Q-head
    # attention loop can index it (avoids n_heads × transpose).
    # See lib/llama_seq_forward_ffi_cuda.rb for the Spinel landmine
    # (issue #688 partial fix; the function-parameter type for
    # build_seq_qhead was already locked in as IntArray before the
    # local-var ptr-push promotion runs). Re-verified 2026-05-26 on
    # Spinel 2183a92: bare `[]` still fires the warning.
    t_k_per_kv  = [TinyNNMetal.tnn_null_ptr]; t_k_per_kv.pop
    t_vt_per_kv = [TinyNNMetal.tnn_null_ptr]; t_vt_per_kv.pop
    hkv = 0
    while hkv < @seq_n_kv
      t_k_raw = mp_matmul(blk.t_seq_w_k[hkv], t_h)
      if @seq_has_qkv_bias
        t_k_pre = TinyNNMetal.tnn_add(@sess, t_k_raw, blk.t_seq_b_k[hkv])
      else
        t_k_pre = t_k_raw
      end
      # ggml_rope_ext requires a->ne[2] == positions->ne[0]. Our K is
      # ne=[d_head, T*B] (ne[2]=1); reshape to ne=[d_head, 1, T*B] so
      # ne[2]==T*B, then reshape back after rope. Reshape is metadata-
      # only (no copy) on contiguous tensors. At T=1, B=1 this is a
      # no-op (1 == 1).
      tb = @seq_t * @seq_b
      t_k_pre3 = TinyNNMetal.tnn_reshape_3d(@sess, t_k_pre, @seq_d_head, 1, tb)
      t_k3     = TinyNNMetal.tnn_rope_ext(@sess, t_k_pre3, @t_seq_positions,
                                       @seq_d_head, @seq_rope_base,
                                       @seq_rope_scaling.freq_scale,
                                       @seq_rope_scaling.ext_factor,
                                       @seq_rope_scaling.attn_factor,
                                       @seq_rope_scaling.beta_fast,
                                       @seq_rope_scaling.beta_slow,
                                       @t_seq_rope_freq_factors)
      t_k      = TinyNNMetal.tnn_reshape_2d(@sess, t_k3, @seq_d_head, tb)
      t_k_per_kv.push(t_k)

      t_v_raw = mp_matmul(blk.t_seq_w_v[hkv], t_h)
      if @seq_has_qkv_bias
        t_v = TinyNNMetal.tnn_add(@sess, t_v_raw, blk.t_seq_b_v[hkv])
      else
        t_v = t_v_raw
      end
      # head_out = v_t @ attn. v has ne=[d_head, T]; transpose to
      # ne=[T, d_head] so the second matmul's contraction lines up.
      t_v_t = TinyNNMetal.tnn_transpose(@sess, t_v)
      t_vt_per_kv.push(t_v_t)
      hkv = hkv + 1
    end

    # Per-Q-head attention. GQA: each Q head reads from kv_h = q_h / group_size.
    t_head_out0 = build_seq_qhead(t_h, blk, 0, t_k_per_kv, t_vt_per_kv, scale)
    t_head_outs = [t_head_out0]
    hq = 1
    while hq < @seq_n_heads
      t_head_outs.push(build_seq_qhead(t_h, blk, hq, t_k_per_kv, t_vt_per_kv, scale))
      hq = hq + 1
    end

    t_concat = t_head_outs[0]
    hq2 = 1
    while hq2 < @seq_n_heads
      t_concat = TinyNNMetal.tnn_concat(@sess, t_concat, t_head_outs[hq2], 0)
      hq2 = hq2 + 1
    end

    t_out_proj = mp_matmul(blk.t_seq_w_o, t_concat)
    t_x_attn   = TinyNNMetal.tnn_add(@sess, t_x, t_out_proj)

    # SwiGLU FFN.
    t_h2    = TinyNNMetal.tnn_rms_norm(@sess, t_x_attn, blk.t_seq_rn2_gamma, eps)
    t_gate  = mp_matmul(blk.t_seq_w_gate, t_h2)
    t_up    = mp_matmul(blk.t_seq_w_up,   t_h2)
    t_silug = TinyNNMetal.tnn_silu(@sess, t_gate)
    t_gated = TinyNNMetal.tnn_mul(@sess, t_silug, t_up)
    t_dn    = mp_matmul(blk.t_seq_w_down, t_gated)
    # GH#15 — tap the FFN output (pre-residual). set_output to pin.
    blk.tap_ffn_out = t_dn
    TinyNNMetal.tnn_set_output(t_dn)

    t_resid = TinyNNMetal.tnn_add(@sess, t_x_attn, t_dn)
    # GH#15 — tap the residual-stream value AFTER this block. Stable,
    # matched-across-runs region name: resid_post_block.
    blk.tap_resid_post = t_resid
    TinyNNMetal.tnn_set_output(t_resid)
    t_resid
  end

  def build_seq_qhead(t_h, blk, hq, t_k_per_kv, t_vt_per_kv, scale)
    hkv = hq / @seq_group_size
    t_q_raw = mp_matmul(blk.t_seq_w_q[hq], t_h)
    # M3 step 3 — LoRA splice on Q (same as decode_step). With B
    # zero-initialized this is a no-op at step 0.
    if @seq_lora_q_enabled
      t_lora_a   = TinyNNMetal.tnn_matmul(@sess, blk.t_seq_w_lora_a_q[hq], t_h)
      t_lora_b_a = TinyNNMetal.tnn_matmul(@sess, blk.t_seq_w_lora_b_q[hq], t_lora_a)
      t_q_raw    = TinyNNMetal.tnn_add(@sess, t_q_raw, t_lora_b_a)
    end
    if @seq_has_qkv_bias
      t_q_pre = TinyNNMetal.tnn_add(@sess, t_q_raw, blk.t_seq_b_q[hq])
    else
      t_q_pre = t_q_raw
    end
    # Same rope-shape lift as the K path; see comment in build_seq_block.
    tb = @seq_t * @seq_b
    t_q_pre3 = TinyNNMetal.tnn_reshape_3d(@sess, t_q_pre, @seq_d_head, 1, tb)
    t_q3     = TinyNNMetal.tnn_rope_ext(@sess, t_q_pre3, @t_seq_positions,
                                     @seq_d_head, @seq_rope_base,
                                     @seq_rope_scaling.freq_scale,
                                     @seq_rope_scaling.ext_factor,
                                     @seq_rope_scaling.attn_factor,
                                     @seq_rope_scaling.beta_fast,
                                     @seq_rope_scaling.beta_slow,
                                     @t_seq_rope_freq_factors)
    t_q      = TinyNNMetal.tnn_reshape_2d(@sess, t_q3, @seq_d_head, tb)

    # scores ne=[T_keys, T_queries]. At B=1, scores=[T, T]; at B>1,
    # scores=[T*B, T*B] (every query attends every key in the matmul;
    # the block-causal mask zeroes cross-batch + future positions).
    t_scores = TinyNNMetal.tnn_matmul(@sess, t_k_per_kv[hkv], t_q)
    if @seq_b > 1
      # GH#7 — soft_max_ext folds scale + mask + softmax. The mask
      # tensor was uploaded at realize time (upload_block_causal_mask!).
      t_attn = TinyNNMetal.tnn_soft_max_ext(@sess, t_scores, @t_seq_attn_mask, scale, 0.0)
    else
      # B=1 legacy path — bit-identical to pre-GH#7. Causal triangle
      # mask + softmax. scale folded as a separate op.
      t_scaled = TinyNNMetal.tnn_scale(@sess, t_scores, scale)
      t_masked = TinyNNMetal.tnn_diag_mask_inf(@sess, t_scaled, 0)
      t_attn   = TinyNNMetal.tnn_softmax(@sess, t_masked)
    end
    # head ne=[d_head, T*B]
    TinyNNMetal.tnn_matmul(@sess, t_vt_per_kv[hkv], t_attn)
  end

  # Run one forward pass. `ids` and `positions` are length-T Int arrays.
  # Returns the t_seq_logits handle; caller downloads via download_row_major
  # against (vocab, T) shape.
  def forward(ids, positions)
    TinyNNMetal.upload_int_array(@sess, @t_seq_token_ids, ids)
    TinyNNMetal.upload_int_array(@sess, @t_seq_positions, positions)
    TinyNNMetal.tnn_compute(@sess)
    @t_seq_logits
  end

  # Seed LoRA-A with a small Gaussian and LoRA-B with zero — the
  # standard init makes the adapter a no-op at step 0 (forward output
  # equals the base model). Mirror of SmolLM2KVFFICache#upload_lora_q_init!.
  def upload_lora_q_init!(seed, init_scale)
    if !@seq_lora_q_enabled; return; end
    s = seed
    m_a = Mat.new(@seq_lora_q_rank, @seq_d_model)
    m_b = Mat.new(@seq_d_head, @seq_lora_q_rank)
    i_b = 0
    while i_b < @seq_d_head * @seq_lora_q_rank
      m_b.flat[i_b] = 0.0
      i_b = i_b + 1
    end
    li = 0
    while li < @seq_n_layers
      blk = @seq_blocks_ffi[li]
      hq = 0
      while hq < @seq_n_heads
        ii = 0
        while ii < @seq_lora_q_rank * @seq_d_model
          s = (s * 1103515245 + 12345) & 0x7FFFFFFF
          u1 = (s.to_f + 1.0) / 2147483648.0
          s = (s * 1103515245 + 12345) & 0x7FFFFFFF
          u2 = (s.to_f + 1.0) / 2147483648.0
          m_a.flat[ii] = init_scale * Math.sqrt(-2.0 * Math.log(u1)) * Math.cos(2.0 * Math::PI * u2)
          ii = ii + 1
        end
        TinyNNMetal.upload_row_major(@sess, blk.t_seq_w_lora_a_q[hq], m_a)
        TinyNNMetal.upload_row_major(@sess, blk.t_seq_w_lora_b_q[hq], m_b)
        hq = hq + 1
      end
      li = li + 1
    end
  end
end
