# Run an open-weight model. Loads a SmolLM2-135M GGUF, decodes 16
# tokens greedily, prints the token IDs. Decoding text from IDs is a
# separate concern (see examples/README — server-side tokenizer is
# opt-in via lib/tokenizer.rb).
#
# The default points at the model converted by prep/convert_smollm2.py
# (run once; see README). examples/example_list_models will show any
# other GGUFs you've cached locally — swap with GGUF= below.
#
#   make example_inference
#   ./examples/example_inference
#   GGUF=data/qwen25-0.5b-native.gguf ./examples/example_inference
#   N_NEW=32 ./examples/example_inference
#
# On CUDA, change `:cpu` → `:cuda` and build with
# `make example_inference_cuda` (the only difference is the FFI
# backend module).

require_relative "../lib/arch"
require_relative "../lib/transformer_lm"

GGUF  = ENV["GGUF"]  || "data/smollm2-135m-f32.gguf"
N_NEW = (ENV["N_NEW"] || "16").to_i

arch = Arch.from_gguf(GGUF)
if arch == nil
  puts "example_inference: could not load " + GGUF +
       " — set GGUF= to a valid file (see examples/example_list_models)."
  exit 1
end
puts arch.summary

lm = ToyLM.new(arch, :cpu)
lm.load(GGUF)

# Token IDs are vocab-specific. The default below is the first five
# IDs from data/smollm2_prompt_ids.txt (generated by
# prep/smollm2_tokens.py); the full canonical prompt is decoded by
# demos/smollm2.rb. If you swap GGUF to a different family, replace
# this list with IDs from that model's tokenizer.
ids = lm.generate([6403, 1980, 253, 655, 28], N_NEW)

print "ids:"
k = 0
while k < ids.length
  print " " + ids[k].to_s
  k = k + 1
end
puts ""
