# lib/toy/llm/primitives/rms_norm_metal.rb — Metal mirror of lib/toy/llm/primitives/rms_norm.rb.
#
# AUTO-GENERATED by prep/gen_cuda_mirror.rb. Do not edit by hand;
# edit the CPU source and re-run the generator. Same L1 contract
# on the GPU backend via TinyNNMetal.
# (root-mean-square normalisation, gamma scale only, no beta).
#
# Pure module: `self.` methods only, no module ivars, no state, no
# config object. The block (L2) owns the gamma weight tensor and the
# eps scalar; this primitive composes only the single tnn_rms_norm
# call. See lib/toy/llm/primitives/README.md for the L1 contract.
#
# Spinel hygiene: no Cfg ctor and no default args (default-arg
# poisoning, landmine #4) — all three call sites supply eps explicitly,
# so a fixed 4-arity signature is clean. eps flows straight through to
# the :double FFI param with no coercion. No Card/step_bind calls, no
# FFI :str args (step_bind :str landmine 2026-05-28).
#
# This file does NOT `require_relative "tinynn"`: the loading module
# (lib/llama_seq_forward_ffi.rb) already loads the correct backend's
# TinyNNMetal before requiring this primitive. The mirror generator picks
# the backend via the monolith's require rewrite (the CUDA/Metal
# mirror of the monolith requires rms_norm_<backend>, and that
# mirror's TinyNNMetal. -> TinyNNMetal<Backend>. rename handles the rest).

module Toy
  module LLM
    module Primitives
      module RMSNorm
        NAME = :rms_norm

        # Root-mean-square normalisation: rms_norm(x) * gamma. gamma is
        # the caller-owned scale tensor (block-owned param); eps is the
        # Float epsilon added inside the rms. The primitive only consumes
        # the gamma handle — it never allocates or frees it. Returns the
        # normalised tensor handle.
        def self.build(sess, x, gamma, eps)
          TinyNNMetal.tnn_rms_norm(sess, x, gamma, eps)
        end
      end
    end
  end
end
