# lib/toy/compute_metal.rb — the Toy compute surface, Metal entry
# (macOS ONLY).
#
# ── LOCKSTEP WARNING ── hand-maintained twin of lib/toy/compute.rb /
# compute_cuda.rb (see compute_cuda.rb's header for why this is not
# mechanically mirrorable). When compute.rb changes, update all three
# entries in the same commit.
#
# DEVICE IS CHOSEN AT COMPILE TIME (toy#64 item 8): require THIS file
# instead of lib/toy/compute.rb on a Mac and the same Toy::Device-
# driven experiment body compiles into a Metal binary. Build with the
# Apple frameworks + force-link, exactly like every metal target:
#   spinel --cc='cc -Wl,-u,_tnn_metal_force_link -framework Foundation \
#                -framework Metal -framework MetalKit' <entry> -o <bin>
#   (deps: tinynn/libtinynn_ggml.a tinynn/libtinynn_ggml_metal.a)
#
# gx10 RUNTIME-UNVERIFIED (Linux cannot build or run Metal — same
# status as every *_metal target; validate on the Mac via gate-metal's
# discipline). SINGLE-TYPE BINARY: TinyNNMetal is the compute module;
# CPU TinyNN stays defined for the checkpoint write/fuse seam.
#
# Backend gaps (consumers needing more require the files directly):
#   - warm-start: NO Metal recipe exists (from-scratch only, matching
#     libexec/toy-train-metal) — Device.warm_start_recipe is absent.
#   - vit: no Metal engine. lora: no Metal recipe (a backend gap only —
#     the toy#52 exclusion is history, see compute.rb's HISTORY note).

# FFI compute layer: Metal TinyNN + the MRI-safe sugar (Mat + Card).
require_relative "ffi/tinynn_metal"
require_relative "../toy"

# Models + configs (shared).
require_relative "models/toy_smollm2"
require_relative "io/loaders/toy_smollm2_loader"
require_relative "models/toy_vit"

# Engines — the Metal mirrors (generated by prep/gen_cuda_mirror.rb).
require_relative "llm/engine/llama_seq_engine_metal"
require_relative "llm/engine/gpt2_seq_engine_metal"

# KV-cache decode engine (inference), Metal mirror.
require_relative "llm/engine/llama_kv_engine_metal"

# Recipes — from-scratch only (see the backend-gaps note above).
require_relative "llm/recipe_options"
require_relative "llm/recipes/from_scratch_metal"

# Inference I/O (shared): GGUF model loading + the BPE tokenizer.
require_relative "io/gguf_load"
require_relative "io/tokenizer"

# Training I/O + schedule (toy#73 item 2): corpus loader + image loader +
# cosine LR schedule. SHARED with the CPU entry (file I/O through C helpers
# in libtinynn_ggml.a + pure Ruby) — see compute.rb's note. The image
# loader rides along even though vit training stays CPU-only this arc
# (the loader is backend-free; the missing piece is the engine/recipe).
require_relative "io/toy_corpus_loader"
require_relative "io/toy_image_loader"
require_relative "train/toy_lr_schedule"

# AdamW + labels + the validating batch wrapper (shared, pure Ruby).
require_relative "llm/adamw"
require_relative "llm/labels"
require_relative "llm/training_batch"

# Run-bundle writer (toy#73 item 1): runs/<id>/events.jsonl in the toy/v1
# schema + the weights/ checkpoint-dir convention. SHARED (not mirrored):
# the events C symbols live in libtinynn_ggml.a, linked by every backend
# (the CPU TinyNN module is defined in this binary too — see the
# checkpoint-seam note above).
require_relative "io/run_bundle"

# ── Toy::Device, Metal arm — see the compute.rb doc block. NOTE: no
# warm_start_recipe here (no Metal recipe exists); a device-agnostic
# body that uses it will fail to compile against this entry — loudly,
# at compile time, which is the correct failure mode.
module Toy
  module Device
    def self.name
      "metal"
    end

    def self.llama_engine
      Toy::LLM::Engine::LlamaSeqEngineMetal.new
    end

    def self.gpt2_engine
      Toy::LLM::Engine::GPT2SeqEngineMetal.new
    end

    def self.from_scratch_recipe
      Toy::LLM::Recipes::FromScratchMetal.new
    end
  end
end
